// Package apispec provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apispec

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for HealthResponseStatus.
const (
	Ok HealthResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for SiteResponseCompatibilityStatus.
const (
	Compatible   SiteResponseCompatibilityStatus = "compatible"
	Incompatible SiteResponseCompatibilityStatus = "incompatible"
	Unknown      SiteResponseCompatibilityStatus = "unknown"
)

// Valid indicates whether the value is a known member of the SiteResponseCompatibilityStatus enum.
func (e SiteResponseCompatibilityStatus) Valid() bool {
	switch e {
	case Compatible:
		return true
	case Incompatible:
		return true
	case Unknown:
		return true
	default:
		return false
	}
}

// Defines values for SiteResponseStatus.
const (
	SiteResponseStatusDisabled SiteResponseStatus = "disabled"
	SiteResponseStatusEnabled  SiteResponseStatus = "enabled"
)

// Valid indicates whether the value is a known member of the SiteResponseStatus enum.
func (e SiteResponseStatus) Valid() bool {
	switch e {
	case SiteResponseStatusDisabled:
		return true
	case SiteResponseStatusEnabled:
		return true
	default:
		return false
	}
}

// Defines values for SiteSupplierResponseDesiredStatus.
const (
	SiteSupplierResponseDesiredStatusDisabled  SiteSupplierResponseDesiredStatus = "disabled"
	SiteSupplierResponseDesiredStatusEnabled   SiteSupplierResponseDesiredStatus = "enabled"
	SiteSupplierResponseDesiredStatusObserving SiteSupplierResponseDesiredStatus = "observing"
)

// Valid indicates whether the value is a known member of the SiteSupplierResponseDesiredStatus enum.
func (e SiteSupplierResponseDesiredStatus) Valid() bool {
	switch e {
	case SiteSupplierResponseDesiredStatusDisabled:
		return true
	case SiteSupplierResponseDesiredStatusEnabled:
		return true
	case SiteSupplierResponseDesiredStatusObserving:
		return true
	default:
		return false
	}
}

// Defines values for SiteSupplierResponseSyncStatus.
const (
	SiteSupplierResponseSyncStatusActive       SiteSupplierResponseSyncStatus = "active"
	SiteSupplierResponseSyncStatusFailed       SiteSupplierResponseSyncStatus = "failed"
	SiteSupplierResponseSyncStatusManualLocked SiteSupplierResponseSyncStatus = "manual_locked"
	SiteSupplierResponseSyncStatusPending      SiteSupplierResponseSyncStatus = "pending"
	SiteSupplierResponseSyncStatusSyncing      SiteSupplierResponseSyncStatus = "syncing"
)

// Valid indicates whether the value is a known member of the SiteSupplierResponseSyncStatus enum.
func (e SiteSupplierResponseSyncStatus) Valid() bool {
	switch e {
	case SiteSupplierResponseSyncStatusActive:
		return true
	case SiteSupplierResponseSyncStatusFailed:
		return true
	case SiteSupplierResponseSyncStatusManualLocked:
		return true
	case SiteSupplierResponseSyncStatusPending:
		return true
	case SiteSupplierResponseSyncStatusSyncing:
		return true
	default:
		return false
	}
}

// Defines values for SupplierResponseProtocol.
const (
	OpenaiCompatible SupplierResponseProtocol = "openai_compatible"
)

// Valid indicates whether the value is a known member of the SupplierResponseProtocol enum.
func (e SupplierResponseProtocol) Valid() bool {
	switch e {
	case OpenaiCompatible:
		return true
	default:
		return false
	}
}

// Defines values for SupplierResponseStatus.
const (
	SupplierResponseStatusDisabled SupplierResponseStatus = "disabled"
	SupplierResponseStatusDraft    SupplierResponseStatus = "draft"
	SupplierResponseStatusEnabled  SupplierResponseStatus = "enabled"
)

// Valid indicates whether the value is a known member of the SupplierResponseStatus enum.
func (e SupplierResponseStatus) Valid() bool {
	switch e {
	case SupplierResponseStatusDisabled:
		return true
	case SupplierResponseStatusDraft:
		return true
	case SupplierResponseStatusEnabled:
		return true
	default:
		return false
	}
}

// Defines values for SyncOperationResponseStatus.
const (
	SyncOperationResponseStatusManualRequired  SyncOperationResponseStatus = "manual_required"
	SyncOperationResponseStatusPending         SyncOperationResponseStatus = "pending"
	SyncOperationResponseStatusRetryableFailed SyncOperationResponseStatus = "retryable_failed"
	SyncOperationResponseStatusRunning         SyncOperationResponseStatus = "running"
	SyncOperationResponseStatusSucceeded       SyncOperationResponseStatus = "succeeded"
	SyncOperationResponseStatusUncertain       SyncOperationResponseStatus = "uncertain"
)

// Valid indicates whether the value is a known member of the SyncOperationResponseStatus enum.
func (e SyncOperationResponseStatus) Valid() bool {
	switch e {
	case SyncOperationResponseStatusManualRequired:
		return true
	case SyncOperationResponseStatusPending:
		return true
	case SyncOperationResponseStatusRetryableFailed:
		return true
	case SyncOperationResponseStatusRunning:
		return true
	case SyncOperationResponseStatusSucceeded:
		return true
	case SyncOperationResponseStatusUncertain:
		return true
	default:
		return false
	}
}

// CreateSiteRequest defines model for CreateSiteRequest.
type CreateSiteRequest struct {
	Code              string `json:"code"`
	Name              string `json:"name"`
	NewApiAccessToken string `json:"new_api_access_token"`
	NewApiBaseUrl     string `json:"new_api_base_url"`
}

// CreateSiteSupplierRequest defines model for CreateSiteSupplierRequest.
type CreateSiteSupplierRequest struct {
	GroupDisplayName string             `json:"group_display_name"`
	SaleRatio        string             `json:"sale_ratio"`
	SiteId           openapi_types.UUID `json:"site_id"`
	SupplierId       openapi_types.UUID `json:"supplier_id"`
	Visible          *bool              `json:"visible,omitempty"`
}

// CreateSupplierRequest defines model for CreateSupplierRequest.
type CreateSupplierRequest struct {
	Code            string                 `json:"code"`
	Models          []SupplierModelRequest `json:"models"`
	Name            string                 `json:"name"`
	UpstreamApiKey  string                 `json:"upstream_api_key"`
	UpstreamBaseUrl string                 `json:"upstream_base_url"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code      string `json:"code"`
	Message   string `json:"message"`
	RequestId string `json:"request_id"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status HealthResponseStatus `json:"status"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// SiteResponse defines model for SiteResponse.
type SiteResponse struct {
	Code                string                          `json:"code"`
	CompatibilityStatus SiteResponseCompatibilityStatus `json:"compatibility_status"`
	CreatedAt           time.Time                       `json:"created_at"`
	Id                  openapi_types.UUID              `json:"id"`
	Name                string                          `json:"name"`
	NewApiBaseUrl       string                          `json:"new_api_base_url"`
	Status              SiteResponseStatus              `json:"status"`
	UpdatedAt           time.Time                       `json:"updated_at"`
	Version             int64                           `json:"version"`
}

// SiteResponseCompatibilityStatus defines model for SiteResponse.CompatibilityStatus.
type SiteResponseCompatibilityStatus string

// SiteResponseStatus defines model for SiteResponse.Status.
type SiteResponseStatus string

// SiteSupplierResponse defines model for SiteSupplierResponse.
type SiteSupplierResponse struct {
	CreatedAt        time.Time                         `json:"created_at"`
	DesiredStatus    SiteSupplierResponseDesiredStatus `json:"desired_status"`
	GroupDisplayName string                            `json:"group_display_name"`
	GroupKey         string                            `json:"group_key"`
	Id               openapi_types.UUID                `json:"id"`
	LastConfirmedAt  *time.Time                        `json:"last_confirmed_at,omitempty"`
	RoutePlanVersion int64                             `json:"route_plan_version"`
	SaleRatio        string                            `json:"sale_ratio"`
	SiteId           openapi_types.UUID                `json:"site_id"`
	SupplierId       openapi_types.UUID                `json:"supplier_id"`
	SyncStatus       SiteSupplierResponseSyncStatus    `json:"sync_status"`
	UpdatedAt        time.Time                         `json:"updated_at"`
	Visible          bool                              `json:"visible"`
}

// SiteSupplierResponseDesiredStatus defines model for SiteSupplierResponse.DesiredStatus.
type SiteSupplierResponseDesiredStatus string

// SiteSupplierResponseSyncStatus defines model for SiteSupplierResponse.SyncStatus.
type SiteSupplierResponseSyncStatus string

// SupplierModelRequest defines model for SupplierModelRequest.
type SupplierModelRequest struct {
	Currency      string `json:"currency"`
	InputPrice    string `json:"input_price"`
	Model         string `json:"model"`
	OutputPrice   string `json:"output_price"`
	UpstreamModel string `json:"upstream_model"`
}

// SupplierModelResponse defines model for SupplierModelResponse.
type SupplierModelResponse struct {
	Currency      string `json:"currency"`
	Enabled       bool   `json:"enabled"`
	InputPrice    string `json:"input_price"`
	Model         string `json:"model"`
	OutputPrice   string `json:"output_price"`
	UpstreamModel string `json:"upstream_model"`
}

// SupplierResponse defines model for SupplierResponse.
type SupplierResponse struct {
	Code            string                   `json:"code"`
	CreatedAt       time.Time                `json:"created_at"`
	Id              openapi_types.UUID       `json:"id"`
	Models          []SupplierModelResponse  `json:"models"`
	Name            string                   `json:"name"`
	Protocol        SupplierResponseProtocol `json:"protocol"`
	Status          SupplierResponseStatus   `json:"status"`
	UpdatedAt       time.Time                `json:"updated_at"`
	UpstreamBaseUrl string                   `json:"upstream_base_url"`
	Version         int64                    `json:"version"`
}

// SupplierResponseProtocol defines model for SupplierResponse.Protocol.
type SupplierResponseProtocol string

// SupplierResponseStatus defines model for SupplierResponse.Status.
type SupplierResponseStatus string

// SyncOperationResponse defines model for SyncOperationResponse.
type SyncOperationResponse struct {
	Attempt          int                         `json:"attempt"`
	CompletedAt      *time.Time                  `json:"completed_at,omitempty"`
	CreatedAt        time.Time                   `json:"created_at"`
	CurrentStep      *string                     `json:"current_step,omitempty"`
	Id               openapi_types.UUID          `json:"id"`
	LastErrorCode    *string                     `json:"last_error_code,omitempty"`
	LastErrorMessage *string                     `json:"last_error_message,omitempty"`
	RelationId       openapi_types.UUID          `json:"relation_id"`
	RoutePlanId      openapi_types.UUID          `json:"route_plan_id"`
	Status           SyncOperationResponseStatus `json:"status"`
	UpdatedAt        time.Time                   `json:"updated_at"`
}

// SyncOperationResponseStatus defines model for SyncOperationResponse.Status.
type SyncOperationResponseStatus string

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// OperationId defines model for OperationId.
type OperationId = openapi_types.UUID

// RelationId defines model for RelationId.
type RelationId = openapi_types.UUID

// SiteId defines model for SiteId.
type SiteId = openapi_types.UUID

// SupplierId defines model for SupplierId.
type SupplierId = openapi_types.UUID

// Error defines model for Error.
type Error = ErrorResponse

// CreateSiteSupplierParams defines parameters for CreateSiteSupplier.
type CreateSiteSupplierParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// SyncSiteSupplierParams defines parameters for SyncSiteSupplier.
type SyncSiteSupplierParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// CreateSiteParams defines parameters for CreateSite.
type CreateSiteParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// CreateSupplierParams defines parameters for CreateSupplier.
type CreateSupplierParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// CreateSiteSupplierJSONRequestBody defines body for CreateSiteSupplier for application/json ContentType.
type CreateSiteSupplierJSONRequestBody = CreateSiteSupplierRequest

// CreateSiteJSONRequestBody defines body for CreateSite for application/json ContentType.
type CreateSiteJSONRequestBody = CreateSiteRequest

// CreateSupplierJSONRequestBody defines body for CreateSupplier for application/json ContentType.
type CreateSupplierJSONRequestBody = CreateSupplierRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /healthz)
	GetHealth(c *gin.Context)

	// (POST /site-suppliers)
	CreateSiteSupplier(c *gin.Context, params CreateSiteSupplierParams)

	// (GET /site-suppliers/{relation_id})
	GetSiteSupplier(c *gin.Context, relationId RelationId)

	// (POST /site-suppliers/{relation_id}/sync)
	SyncSiteSupplier(c *gin.Context, relationId RelationId, params SyncSiteSupplierParams)

	// (POST /sites)
	CreateSite(c *gin.Context, params CreateSiteParams)

	// (GET /sites/{site_id})
	GetSite(c *gin.Context, siteId SiteId)

	// (POST /suppliers)
	CreateSupplier(c *gin.Context, params CreateSupplierParams)

	// (GET /suppliers/{supplier_id})
	GetSupplier(c *gin.Context, supplierId SupplierId)

	// (GET /sync-operations/{operation_id})
	GetSyncOperation(c *gin.Context, operationId OperationId)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHealth(c)
}

// CreateSiteSupplier operation middleware
func (siw *ServerInterfaceWrapper) CreateSiteSupplier(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateSiteSupplierParams

	headers := c.Request.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for Idempotency-Key, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter Idempotency-Key: %w", err), http.StatusBadRequest)
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter Idempotency-Key is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateSiteSupplier(c, params)
}

// GetSiteSupplier operation middleware
func (siw *ServerInterfaceWrapper) GetSiteSupplier(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "relation_id" -------------
	var relationId RelationId

	err = runtime.BindStyledParameterWithOptions("simple", "relation_id", c.Param("relation_id"), &relationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter relation_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSiteSupplier(c, relationId)
}

// SyncSiteSupplier operation middleware
func (siw *ServerInterfaceWrapper) SyncSiteSupplier(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "relation_id" -------------
	var relationId RelationId

	err = runtime.BindStyledParameterWithOptions("simple", "relation_id", c.Param("relation_id"), &relationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter relation_id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params SyncSiteSupplierParams

	headers := c.Request.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for Idempotency-Key, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter Idempotency-Key: %w", err), http.StatusBadRequest)
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter Idempotency-Key is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SyncSiteSupplier(c, relationId, params)
}

// CreateSite operation middleware
func (siw *ServerInterfaceWrapper) CreateSite(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateSiteParams

	headers := c.Request.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for Idempotency-Key, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter Idempotency-Key: %w", err), http.StatusBadRequest)
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter Idempotency-Key is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateSite(c, params)
}

// GetSite operation middleware
func (siw *ServerInterfaceWrapper) GetSite(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "site_id" -------------
	var siteId SiteId

	err = runtime.BindStyledParameterWithOptions("simple", "site_id", c.Param("site_id"), &siteId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter site_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSite(c, siteId)
}

// CreateSupplier operation middleware
func (siw *ServerInterfaceWrapper) CreateSupplier(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateSupplierParams

	headers := c.Request.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for Idempotency-Key, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter Idempotency-Key: %w", err), http.StatusBadRequest)
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter Idempotency-Key is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateSupplier(c, params)
}

// GetSupplier operation middleware
func (siw *ServerInterfaceWrapper) GetSupplier(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "supplier_id" -------------
	var supplierId SupplierId

	err = runtime.BindStyledParameterWithOptions("simple", "supplier_id", c.Param("supplier_id"), &supplierId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter supplier_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSupplier(c, supplierId)
}

// GetSyncOperation operation middleware
func (siw *ServerInterfaceWrapper) GetSyncOperation(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "operation_id" -------------
	var operationId OperationId

	err = runtime.BindStyledParameterWithOptions("simple", "operation_id", c.Param("operation_id"), &operationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter operation_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSyncOperation(c, operationId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/healthz", wrapper.GetHealth)
	router.POST(options.BaseURL+"/sites", wrapper.CreateSite)
	router.GET(options.BaseURL+"/sites/:site_id", wrapper.GetSite)
	router.POST(options.BaseURL+"/suppliers", wrapper.CreateSupplier)
	router.GET(options.BaseURL+"/suppliers/:supplier_id", wrapper.GetSupplier)
	router.POST(options.BaseURL+"/site-suppliers", wrapper.CreateSiteSupplier)
	router.GET(options.BaseURL+"/site-suppliers/:relation_id", wrapper.GetSiteSupplier)
	router.POST(options.BaseURL+"/site-suppliers/:relation_id/sync", wrapper.SyncSiteSupplier)
	router.GET(options.BaseURL+"/sync-operations/:operation_id", wrapper.GetSyncOperation)
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"1Frdctu2En4VDU4uknNkS7JzMoluOmmn03raTDpOr2qrHJhcWYhJAAGWThlX794BQIp/oChRUtNehYyB",
	"3cXut7sflnoioUik4MBRk/kTkVTRBBCUfbuKIJECgYfZT5CZ/2GczMkKaASKjAmnCZB5ddmZWTcmCj6l",
	"TEFE5qhSGBMdriChRkBC//gZ+D2uyHx28XpMEsaL99djgpk0AjUqxu/Jej0m7yUoikzwq2ijX1JcldpF",
	"sSJg0VbVS6ESimRO0tSubCu7hni7LpUvOFzVB4bQqUYzhCOoSKWMGahuNfmCQ1WtzWYtBddgYfO9UkKZ",
	"h1BwBI7mkRpVoXXe5KMW3PxfqeGZgiWZk/9MSjRO3F/1xEq7zuU7bRHoUDFphJG5UzdS5YrCdmvMdwoo",
	"gnH3NXxKQVtrpDKoQebsDUUEDWy+uqxB86J16MKJDURPa9tmvm3wOaCSBTQMQesAxQPwhpjXszcXO8u5",
	"oxqCVMX1QClGxlWRF9OX3vQqg37j3JCfyyO/w/TFRqy4+wghGttKnxcY7PT9vRKpDCKmZUyzYKBPNY0h",
	"sEXA1TBEUAYZvz+f/nkzO3uzuL29vY3+++K5+ffcvjzNxq/WL755Rnzi8vTrh/64lkO7rH9kmt3F9pAR",
	"LGkaY5Fv+dI7IWKgvBWdsibU09bjwJpDtsSnLzbD8iIREcR2P0NIdF96F1a8M9sKU9YWvFdu//+nDgH5",
	"awkAqhTNDkjFVGpUQBML6gfX4PZNw42MU+VhW4HH8I3XfdGuF9DOKLcDCVrTe//flAtUjvqdzlOIq232",
	"2fsj0BhX3QZrpJjaJ+BpYjSIh4qgDivyXT6Frjns7R8DZorsjsUMs6BtVcofuPjMSbkyNqdnvPK68EAq",
	"tNkZBRRrWIoowhkyC4rWnh2rT5EoQ7pJu/S1Tgyc3sVgNEdMu8eFN2eivQ/4CEozRxs2GxjHVy/LxYwj",
	"3INqRd66ore55afpCGtpQC0+tbN0Qauss50QGxDxCLQ5oAd34k6DejTLxrtGxN+FO5bllXIoBmOqMQgF",
	"XzKVbD8zT+OY2mZZ65CVKiRShEDGlAf74KNJGP5WAqAzHnqCJoFHLmRmgXuiIbJH44glZS6ICeUpjYNY",
	"hA/HzK2Sk/SQEMc/tjIR1476WEmptIXkuou8Qd4zB30Mo52DqVLmBttgkDdvz35bPF2uvUSRcZliIBUL",
	"obHNcsz/1fnmbNpFOG3zbhKYN7Ne8iFSPI4BG0IxzJIGSpyQltS6vxrWj8sA7BDDspDSOH6/JPObQSSz",
	"iYGiWvYnQrGybeuiYu0QUnG65n8YMS9u193su6VQKoEiFHGtOUnglAU9FKhdHyNFl7h7QxtSBneh8ifm",
	"JRuP+Xm/h4zkQd2zImY83AzWukFqqkkisRLbSgs1EYwBD+zgQ+DuCgUGGkGaXb1K9iEmYC5LQZGevaIr",
	"eyrXpX7iUpkj7mJapQfuSjO2MAyVcu6eUh6CQsq4beZhCBCBmwWiyswJgib12AD4OFnnS4nGkLV29EoO",
	"FOjcB/rGMRCmimH2wZQ5h3M3QRbq12IWZ0ugLf9AlZ1053JWiNKNIBlfOu7I0MSZvKM8uzamqtE7yuk9",
	"JMBx9PaXq0q2zsn0fHY+tZ3blEHJyJxcnk/PL03qU1xZayYre//9YqdjgKWB+WCa/ADorsikMXe9mE6P",
	"NnVtXMI9Y9cP5pIRwsiZW/Mtmd8szPvEUMWzgiW6DwxCe47UHhhaj5TfIjr6e7lk0vhWsV5s5gzfiig7",
	"ml+6R5vrOphN5q9bAZodzRDvzdIXJoYwKkIwKnJrRHk0Ypwho/HIptjIpNgoTyV3wczHk347NgdzA3qj",
	"uh3xyVMlmdfbEH1Q7CvfbVzcT5QUw3xuKhacxqMTc1XqTivT54/m2PGwFKyF4uJ4ofBSGF8sMh6ulODs",
	"Sw78MAR5MMR3qmX//Br2FWtXb/4cpRTpyVM+ruitPntHK/+Ee/KK0+upCJCyWB/gqZ079L+jO3/lzrxL",
	"hyiaw+EoLztDZRy3He1Do1j5RcFpUb+PBw9Hf8bDs42T9OSp+ouS7Y6sNqG9vVn9actp3Tm0Vx7CXOrX",
	"gdYl62ZhjqxBPRbesgMXMqGSTR5nZL1Y/xUAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
