// Package apispec provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apispec

import (
	"encoding/json"
	"fmt"
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for OpAuditActorType.
const (
	OpAuditActorTypeOperator OpAuditActorType = "operator"
	OpAuditActorTypeSystem   OpAuditActorType = "system"
)

// Valid indicates whether the value is a known member of the OpAuditActorType enum.
func (e OpAuditActorType) Valid() bool {
	switch e {
	case OpAuditActorTypeOperator:
		return true
	case OpAuditActorTypeSystem:
		return true
	default:
		return false
	}
}

// Defines values for OpAuthUserRole.
const (
	OpAuthUserRoleOwner OpAuthUserRole = "owner"
)

// Valid indicates whether the value is a known member of the OpAuthUserRole enum.
func (e OpAuthUserRole) Valid() bool {
	switch e {
	case OpAuthUserRoleOwner:
		return true
	default:
		return false
	}
}

// Defines values for OpCreateSiteInputStatus.
const (
	OpCreateSiteInputStatusDisabled OpCreateSiteInputStatus = "disabled"
	OpCreateSiteInputStatusEnabled  OpCreateSiteInputStatus = "enabled"
)

// Valid indicates whether the value is a known member of the OpCreateSiteInputStatus enum.
func (e OpCreateSiteInputStatus) Valid() bool {
	switch e {
	case OpCreateSiteInputStatusDisabled:
		return true
	case OpCreateSiteInputStatusEnabled:
		return true
	default:
		return false
	}
}

// Defines values for OpCreateSupplierInputStatus.
const (
	OpCreateSupplierInputStatusDisabled OpCreateSupplierInputStatus = "disabled"
	OpCreateSupplierInputStatusEnabled  OpCreateSupplierInputStatus = "enabled"
)

// Valid indicates whether the value is a known member of the OpCreateSupplierInputStatus enum.
func (e OpCreateSupplierInputStatus) Valid() bool {
	switch e {
	case OpCreateSupplierInputStatusDisabled:
		return true
	case OpCreateSupplierInputStatusEnabled:
		return true
	default:
		return false
	}
}

// Defines values for OpModelInputCurrency.
const (
	OpModelInputCurrencyCNY OpModelInputCurrency = "CNY"
	OpModelInputCurrencyUSD OpModelInputCurrency = "USD"
)

// Valid indicates whether the value is a known member of the OpModelInputCurrency enum.
func (e OpModelInputCurrency) Valid() bool {
	switch e {
	case OpModelInputCurrencyCNY:
		return true
	case OpModelInputCurrencyUSD:
		return true
	default:
		return false
	}
}

// Defines values for OpPlanStatus.
const (
	OpPlanStatusApplying   OpPlanStatus = "applying"
	OpPlanStatusConfirmed  OpPlanStatus = "confirmed"
	OpPlanStatusFailed     OpPlanStatus = "failed"
	OpPlanStatusPending    OpPlanStatus = "pending"
	OpPlanStatusSuperseded OpPlanStatus = "superseded"
	OpPlanStatusUncertain  OpPlanStatus = "uncertain"
)

// Valid indicates whether the value is a known member of the OpPlanStatus enum.
func (e OpPlanStatus) Valid() bool {
	switch e {
	case OpPlanStatusApplying:
		return true
	case OpPlanStatusConfirmed:
		return true
	case OpPlanStatusFailed:
		return true
	case OpPlanStatusPending:
		return true
	case OpPlanStatusSuperseded:
		return true
	case OpPlanStatusUncertain:
		return true
	default:
		return false
	}
}

// Defines values for OpPriceStatus.
const (
	OpPriceStatusApplied    OpPriceStatus = "applied"
	OpPriceStatusDraft      OpPriceStatus = "draft"
	OpPriceStatusPublished  OpPriceStatus = "published"
	OpPriceStatusSuperseded OpPriceStatus = "superseded"
)

// Valid indicates whether the value is a known member of the OpPriceStatus enum.
func (e OpPriceStatus) Valid() bool {
	switch e {
	case OpPriceStatusApplied:
		return true
	case OpPriceStatusDraft:
		return true
	case OpPriceStatusPublished:
		return true
	case OpPriceStatusSuperseded:
		return true
	default:
		return false
	}
}

// Defines values for OpRelationDesiredStatus.
const (
	OpRelationDesiredStatusDisabled  OpRelationDesiredStatus = "disabled"
	OpRelationDesiredStatusEnabled   OpRelationDesiredStatus = "enabled"
	OpRelationDesiredStatusObserving OpRelationDesiredStatus = "observing"
)

// Valid indicates whether the value is a known member of the OpRelationDesiredStatus enum.
func (e OpRelationDesiredStatus) Valid() bool {
	switch e {
	case OpRelationDesiredStatusDisabled:
		return true
	case OpRelationDesiredStatusEnabled:
		return true
	case OpRelationDesiredStatusObserving:
		return true
	default:
		return false
	}
}

// Defines values for OpRelationSyncStatus.
const (
	OpRelationSyncStatusActive       OpRelationSyncStatus = "active"
	OpRelationSyncStatusFailed       OpRelationSyncStatus = "failed"
	OpRelationSyncStatusManualLocked OpRelationSyncStatus = "manual_locked"
	OpRelationSyncStatusPending      OpRelationSyncStatus = "pending"
	OpRelationSyncStatusSyncing      OpRelationSyncStatus = "syncing"
)

// Valid indicates whether the value is a known member of the OpRelationSyncStatus enum.
func (e OpRelationSyncStatus) Valid() bool {
	switch e {
	case OpRelationSyncStatusActive:
		return true
	case OpRelationSyncStatusFailed:
		return true
	case OpRelationSyncStatusManualLocked:
		return true
	case OpRelationSyncStatusPending:
		return true
	case OpRelationSyncStatusSyncing:
		return true
	default:
		return false
	}
}

// Defines values for OpRelationInputDesiredStatus.
const (
	OpRelationInputDesiredStatusDisabled OpRelationInputDesiredStatus = "disabled"
	OpRelationInputDesiredStatusEnabled  OpRelationInputDesiredStatus = "enabled"
)

// Valid indicates whether the value is a known member of the OpRelationInputDesiredStatus enum.
func (e OpRelationInputDesiredStatus) Valid() bool {
	switch e {
	case OpRelationInputDesiredStatusDisabled:
		return true
	case OpRelationInputDesiredStatusEnabled:
		return true
	default:
		return false
	}
}

// Defines values for OpSiteCompatibilityStatus.
const (
	OpSiteCompatibilityStatusCompatible   OpSiteCompatibilityStatus = "compatible"
	OpSiteCompatibilityStatusIncompatible OpSiteCompatibilityStatus = "incompatible"
	OpSiteCompatibilityStatusUnknown      OpSiteCompatibilityStatus = "unknown"
)

// Valid indicates whether the value is a known member of the OpSiteCompatibilityStatus enum.
func (e OpSiteCompatibilityStatus) Valid() bool {
	switch e {
	case OpSiteCompatibilityStatusCompatible:
		return true
	case OpSiteCompatibilityStatusIncompatible:
		return true
	case OpSiteCompatibilityStatusUnknown:
		return true
	default:
		return false
	}
}

// Defines values for OpSiteStatus.
const (
	OpSiteStatusDisabled OpSiteStatus = "disabled"
	OpSiteStatusEnabled  OpSiteStatus = "enabled"
)

// Valid indicates whether the value is a known member of the OpSiteStatus enum.
func (e OpSiteStatus) Valid() bool {
	switch e {
	case OpSiteStatusDisabled:
		return true
	case OpSiteStatusEnabled:
		return true
	default:
		return false
	}
}

// Defines values for OpStrategyKind.
const (
	OpStrategyKindBalanced    OpStrategyKind = "balanced"
	OpStrategyKindHighQuality OpStrategyKind = "high_quality"
	OpStrategyKindHighSla     OpStrategyKind = "high_sla"
	OpStrategyKindLowLatency  OpStrategyKind = "low_latency"
	OpStrategyKindLowestPrice OpStrategyKind = "lowest_price"
)

// Valid indicates whether the value is a known member of the OpStrategyKind enum.
func (e OpStrategyKind) Valid() bool {
	switch e {
	case OpStrategyKindBalanced:
		return true
	case OpStrategyKindHighQuality:
		return true
	case OpStrategyKindHighSla:
		return true
	case OpStrategyKindLowLatency:
		return true
	case OpStrategyKindLowestPrice:
		return true
	default:
		return false
	}
}

// Defines values for OpSupplierProtocol.
const (
	OpSupplierProtocolOpenaiCompatible OpSupplierProtocol = "openai_compatible"
)

// Valid indicates whether the value is a known member of the OpSupplierProtocol enum.
func (e OpSupplierProtocol) Valid() bool {
	switch e {
	case OpSupplierProtocolOpenaiCompatible:
		return true
	default:
		return false
	}
}

// Defines values for OpSupplierStatus.
const (
	OpSupplierStatusDisabled OpSupplierStatus = "disabled"
	OpSupplierStatusDraft    OpSupplierStatus = "draft"
	OpSupplierStatusEnabled  OpSupplierStatus = "enabled"
)

// Valid indicates whether the value is a known member of the OpSupplierStatus enum.
func (e OpSupplierStatus) Valid() bool {
	switch e {
	case OpSupplierStatusDisabled:
		return true
	case OpSupplierStatusDraft:
		return true
	case OpSupplierStatusEnabled:
		return true
	default:
		return false
	}
}

// Defines values for OpSyncOperationStatus.
const (
	OpSyncOperationStatusManualRequired  OpSyncOperationStatus = "manual_required"
	OpSyncOperationStatusPending         OpSyncOperationStatus = "pending"
	OpSyncOperationStatusRetryableFailed OpSyncOperationStatus = "retryable_failed"
	OpSyncOperationStatusRunning         OpSyncOperationStatus = "running"
	OpSyncOperationStatusSucceeded       OpSyncOperationStatus = "succeeded"
	OpSyncOperationStatusSuperseded      OpSyncOperationStatus = "superseded"
	OpSyncOperationStatusUncertain       OpSyncOperationStatus = "uncertain"
)

// Valid indicates whether the value is a known member of the OpSyncOperationStatus enum.
func (e OpSyncOperationStatus) Valid() bool {
	switch e {
	case OpSyncOperationStatusManualRequired:
		return true
	case OpSyncOperationStatusPending:
		return true
	case OpSyncOperationStatusRetryableFailed:
		return true
	case OpSyncOperationStatusRunning:
		return true
	case OpSyncOperationStatusSucceeded:
		return true
	case OpSyncOperationStatusSuperseded:
		return true
	case OpSyncOperationStatusUncertain:
		return true
	default:
		return false
	}
}

// Defines values for OpSyncStepStatus.
const (
	OpSyncStepStatusFailed    OpSyncStepStatus = "failed"
	OpSyncStepStatusPending   OpSyncStepStatus = "pending"
	OpSyncStepStatusRunning   OpSyncStepStatus = "running"
	OpSyncStepStatusSucceeded OpSyncStepStatus = "succeeded"
	OpSyncStepStatusUncertain OpSyncStepStatus = "uncertain"
)

// Valid indicates whether the value is a known member of the OpSyncStepStatus enum.
func (e OpSyncStepStatus) Valid() bool {
	switch e {
	case OpSyncStepStatusFailed:
		return true
	case OpSyncStepStatusPending:
		return true
	case OpSyncStepStatusRunning:
		return true
	case OpSyncStepStatusSucceeded:
		return true
	case OpSyncStepStatusUncertain:
		return true
	default:
		return false
	}
}

// Defines values for OpUpdateSiteInputStatus.
const (
	OpUpdateSiteInputStatusDisabled OpUpdateSiteInputStatus = "disabled"
	OpUpdateSiteInputStatusEnabled  OpUpdateSiteInputStatus = "enabled"
)

// Valid indicates whether the value is a known member of the OpUpdateSiteInputStatus enum.
func (e OpUpdateSiteInputStatus) Valid() bool {
	switch e {
	case OpUpdateSiteInputStatusDisabled:
		return true
	case OpUpdateSiteInputStatusEnabled:
		return true
	default:
		return false
	}
}

// Defines values for OpUpdateSupplierInputStatus.
const (
	OpUpdateSupplierInputStatusDisabled OpUpdateSupplierInputStatus = "disabled"
	OpUpdateSupplierInputStatusEnabled  OpUpdateSupplierInputStatus = "enabled"
)

// Valid indicates whether the value is a known member of the OpUpdateSupplierInputStatus enum.
func (e OpUpdateSupplierInputStatus) Valid() bool {
	switch e {
	case OpUpdateSupplierInputStatusDisabled:
		return true
	case OpUpdateSupplierInputStatusEnabled:
		return true
	default:
		return false
	}
}

// OpAudit defines model for OpAudit.
type OpAudit struct {
	Action      string                  `json:"action"`
	ActorId     string                  `json:"actor_id"`
	ActorType   OpAuditActorType        `json:"actor_type"`
	CreatedAt   time.Time               `json:"created_at"`
	Id          openapi_types.UUID      `json:"id"`
	NewSummary  *map[string]interface{} `json:"new_summary,omitempty"`
	ObjectId    string                  `json:"object_id"`
	ObjectType  string                  `json:"object_type"`
	OldSummary  *map[string]interface{} `json:"old_summary,omitempty"`
	OperationId *openapi_types.UUID     `json:"operation_id,omitempty"`
	Reason      string                  `json:"reason"`
	Result      string                  `json:"result"`
	SiteId      *openapi_types.UUID     `json:"site_id,omitempty"`
}

// OpAuditActorType defines model for OpAudit.ActorType.
type OpAuditActorType string

// OpAuditPage defines model for OpAuditPage.
type OpAuditPage struct {
	Items  []OpAudit `json:"items"`
	Limit  int       `json:"limit"`
	Offset int       `json:"offset"`
	Total  int64     `json:"total"`
}

// OpAuthSession defines model for OpAuthSession.
type OpAuthSession struct {
	CsrfToken string     `json:"csrf_token"`
	User      OpAuthUser `json:"user"`
}

// OpAuthStatus defines model for OpAuthStatus.
type OpAuthStatus struct {
	Initialized bool `json:"initialized"`
}

// OpAuthUser defines model for OpAuthUser.
type OpAuthUser struct {
	Id       openapi_types.UUID `json:"id"`
	Role     OpAuthUserRole     `json:"role"`
	Username string             `json:"username"`
}

// OpAuthUserRole defines model for OpAuthUser.Role.
type OpAuthUserRole string

// OpCreateSiteInput defines model for OpCreateSiteInput.
type OpCreateSiteInput struct {
	AdminUserId       *int64                   `json:"admin_user_id,omitempty"`
	Code              string                   `json:"code"`
	Name              string                   `json:"name"`
	NewApiAccessToken *string                  `json:"new_api_access_token,omitempty"`
	NewApiBaseUrl     string                   `json:"new_api_base_url"`
	Reason            *string                  `json:"reason,omitempty"`
	Status            *OpCreateSiteInputStatus `json:"status,omitempty"`
	Version           *int64                   `json:"version,omitempty"`
}

// OpCreateSiteInputStatus defines model for OpCreateSiteInput.Status.
type OpCreateSiteInputStatus string

// OpCreateSupplierInput defines model for OpCreateSupplierInput.
type OpCreateSupplierInput struct {
	Code            string                       `json:"code"`
	Models          []OpModelInput               `json:"models"`
	Name            string                       `json:"name"`
	Reason          *string                      `json:"reason,omitempty"`
	Status          *OpCreateSupplierInputStatus `json:"status,omitempty"`
	UpstreamApiKey  *string                      `json:"upstream_api_key,omitempty"`
	UpstreamBaseUrl string                       `json:"upstream_base_url"`
	Version         *int64                       `json:"version,omitempty"`
}

// OpCreateSupplierInputStatus defines model for OpCreateSupplierInput.Status.
type OpCreateSupplierInputStatus string

// OpCredentialCancelInput defines model for OpCredentialCancelInput.
type OpCredentialCancelInput struct {
	Reason  string `json:"reason"`
	Version int64  `json:"version"`
}

// OpCredentialInput defines model for OpCredentialInput.
type OpCredentialInput struct {
	ApiKey  *string `json:"api_key,omitempty"`
	Reason  string  `json:"reason"`
	Version int64   `json:"version"`
}

// OpDeploymentInput defines model for OpDeploymentInput.
type OpDeploymentInput struct {
	Reason     string               `json:"reason"`
	Sites      []OpDeploymentTarget `json:"sites"`
	SupplierId openapi_types.UUID   `json:"supplier_id"`
}

// OpDeploymentTarget defines model for OpDeploymentTarget.
type OpDeploymentTarget struct {
	GroupDisplayName string `json:"group_display_name"`

	// SaleRatio Positive decimal up to 999999.999999
	SaleRatio string             `json:"sale_ratio"`
	SiteId    openapi_types.UUID `json:"site_id"`

	// Visible Open the dedicated group entry when true. False closes the entry and rejects subsequent requests from existing API keys bound to this group after synchronization; the supplier can still serve other open Auto groups.
	Visible bool `json:"visible"`
}

// OpError defines model for OpError.
type OpError struct {
	Code      string `json:"code"`
	Message   string `json:"message"`
	RequestId string `json:"request_id"`
}

// OpLoginInput defines model for OpLoginInput.
type OpLoginInput struct {
	Password *string `json:"password,omitempty"`
	Username string  `json:"username"`
}

// OpModelInput defines model for OpModelInput.
type OpModelInput struct {
	Currency OpModelInputCurrency `json:"currency"`
	Enabled  bool                 `json:"enabled"`

	// InputPrice Nonnegative decimal with at most ten fractional digits
	InputPrice string `json:"input_price"`
	Model      string `json:"model"`

	// OutputPrice Nonnegative decimal with at most ten fractional digits
	OutputPrice   string `json:"output_price"`
	UpstreamModel string `json:"upstream_model"`
}

// OpModelInputCurrency defines model for OpModelInput.Currency.
type OpModelInputCurrency string

// OpPagination defines model for OpPagination.
type OpPagination struct {
	Limit  int   `json:"limit"`
	Offset int   `json:"offset"`
	Total  int64 `json:"total"`
}

// OpPlan defines model for OpPlan.
type OpPlan struct {
	ConfirmedAt      *time.Time              `json:"confirmed_at,omitempty"`
	ContentHash      string                  `json:"content_hash"`
	CreatedAt        time.Time               `json:"created_at"`
	Id               openapi_types.UUID      `json:"id"`
	PreviousPlanId   *openapi_types.UUID     `json:"previous_plan_id,omitempty"`
	PreviousSnapshot *map[string]interface{} `json:"previous_snapshot,omitempty"`
	Reason           string                  `json:"reason"`
	SiteId           openapi_types.UUID      `json:"site_id"`
	SiteSupplierId   openapi_types.UUID      `json:"site_supplier_id"`
	Snapshot         map[string]interface{}  `json:"snapshot"`
	Status           OpPlanStatus            `json:"status"`
	Version          int64                   `json:"version"`
}

// OpPlanStatus defines model for OpPlan.Status.
type OpPlanStatus string

// OpPlanPage defines model for OpPlanPage.
type OpPlanPage struct {
	Items  []OpPlan `json:"items"`
	Limit  int      `json:"limit"`
	Offset int      `json:"offset"`
	Total  int64    `json:"total"`
}

// OpPlanReference defines model for OpPlanReference.
type OpPlanReference struct {
	Id                   openapi_types.UUID     `json:"id"`
	SiteId               openapi_types.UUID     `json:"site_id"`
	Status               string                 `json:"status"`
	Version              int64                  `json:"version"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// OpPlanResult defines model for OpPlanResult.
type OpPlanResult struct {
	Plans []OpPlanReference `json:"plans"`
}

// OpPrice defines model for OpPrice.
type OpPrice struct {
	// AppliedAt Historical time when this price version first passed group-ratio and pricing-basis reconciliation; subsequent external changes or partial writes may require fresh confirmation.
	AppliedAt *time.Time `json:"applied_at,omitempty"`

	// BasisHash Digest of the observed pricing settings and New API version, used for configuration reconciliation.
	BasisHash string `json:"basis_hash"`

	// BillingBasis Pricing settings and New API version observed for this price; this historical evidence does not assert that an external administrator has left the live settings unchanged.
	BillingBasis map[string]interface{} `json:"billing_basis"`
	CreatedAt    time.Time              `json:"created_at"`
	GroupKey     string                 `json:"group_key"`
	Id           openapi_types.UUID     `json:"id"`

	// IsLastConfirmed True for the most recently confirmed version recorded for this site and group. A pending or partially applied newer plan can leave the current external price unknown.
	IsLastConfirmed bool                `json:"is_last_confirmed"`
	PublishedAt     *time.Time          `json:"published_at,omitempty"`
	Reason          string              `json:"reason"`
	RoutePlanId     *openapi_types.UUID `json:"route_plan_id,omitempty"`
	SaleRatio       string              `json:"sale_ratio"`
	SiteId          openapi_types.UUID  `json:"site_id"`
	Status          OpPriceStatus       `json:"status"`
	Version         int64               `json:"version"`
}

// OpPriceStatus defines model for OpPrice.Status.
type OpPriceStatus string

// OpPriceInput defines model for OpPriceInput.
type OpPriceInput struct {
	GroupKey string `json:"group_key"`
	Reason   string `json:"reason"`

	// SaleRatio Positive decimal up to 999999.999999
	SaleRatio string             `json:"sale_ratio"`
	SiteId    openapi_types.UUID `json:"site_id"`
}

// OpPricePage defines model for OpPricePage.
type OpPricePage struct {
	Items  []OpPrice `json:"items"`
	Limit  int       `json:"limit"`
	Offset int       `json:"offset"`
	Total  int64     `json:"total"`
}

// OpPublishInput defines model for OpPublishInput.
type OpPublishInput struct {
	Version int64 `json:"version"`
}

// OpRelation defines model for OpRelation.
type OpRelation struct {
	CreatedAt            time.Time               `json:"created_at"`
	CredentialVersion    *int                    `json:"credential_version,omitempty"`
	CurrentPlanId        *openapi_types.UUID     `json:"current_plan_id,omitempty"`
	DesiredStatus        OpRelationDesiredStatus `json:"desired_status"`
	ExternalChannelId    *int64                  `json:"external_channel_id,omitempty"`
	GroupDisplayName     string                  `json:"group_display_name"`
	GroupKey             string                  `json:"group_key"`
	Id                   openapi_types.UUID      `json:"id"`
	LastConfirmedAt      *time.Time              `json:"last_confirmed_at,omitempty"`
	LastConfirmedEnabled *bool                   `json:"last_confirmed_enabled,omitempty"`
	SaleRatio            string                  `json:"sale_ratio"`
	SiteId               openapi_types.UUID      `json:"site_id"`
	SiteName             string                  `json:"site_name"`
	SupplierId           openapi_types.UUID      `json:"supplier_id"`
	SupplierName         string                  `json:"supplier_name"`
	SyncStatus           OpRelationSyncStatus    `json:"sync_status"`
	UpdatedAt            time.Time               `json:"updated_at"`
	Version              int64                   `json:"version"`

	// Visible Desired dedicated group entry access, including existing group-bound API keys. Inspect synchronization state for whether the access change has completed.
	Visible bool `json:"visible"`
}

// OpRelationDesiredStatus defines model for OpRelation.DesiredStatus.
type OpRelationDesiredStatus string

// OpRelationSyncStatus defines model for OpRelation.SyncStatus.
type OpRelationSyncStatus string

// OpRelationInput defines model for OpRelationInput.
type OpRelationInput struct {
	DesiredStatus    OpRelationInputDesiredStatus `json:"desired_status"`
	GroupDisplayName string                       `json:"group_display_name"`
	Reason           string                       `json:"reason"`

	// Resume Explicitly restore a stopped deployment
	Resume  bool  `json:"resume"`
	Version int64 `json:"version"`

	// Visible Desired dedicated entry access. False closes the entry and rejects subsequent requests from existing group-bound API keys after synchronization, while preserving the channel and participation in other open Auto groups.
	Visible bool `json:"visible"`
}

// OpRelationInputDesiredStatus defines model for OpRelationInput.DesiredStatus.
type OpRelationInputDesiredStatus string

// OpRelationPage defines model for OpRelationPage.
type OpRelationPage struct {
	Items  []OpRelation `json:"items"`
	Limit  int          `json:"limit"`
	Offset int          `json:"offset"`
	Total  int64        `json:"total"`
}

// OpRestoreInput defines model for OpRestoreInput.
type OpRestoreInput struct {
	Reason string `json:"reason"`
}

// OpSetupInput defines model for OpSetupInput.
type OpSetupInput struct {
	Password   *string `json:"password,omitempty"`
	SetupToken *string `json:"setup_token,omitempty"`
	Username   string  `json:"username"`
}

// OpSite defines model for OpSite.
type OpSite struct {
	AdminUserId         int64                     `json:"admin_user_id"`
	Code                string                    `json:"code"`
	CompatibilityStatus OpSiteCompatibilityStatus `json:"compatibility_status"`
	CreatedAt           time.Time                 `json:"created_at"`
	Id                  openapi_types.UUID        `json:"id"`
	Name                string                    `json:"name"`
	NewApiBaseUrl       string                    `json:"new_api_base_url"`
	Status              OpSiteStatus              `json:"status"`
	UpdatedAt           time.Time                 `json:"updated_at"`
	Version             int64                     `json:"version"`
}

// OpSiteCompatibilityStatus defines model for OpSite.CompatibilityStatus.
type OpSiteCompatibilityStatus string

// OpSiteStatus defines model for OpSite.Status.
type OpSiteStatus string

// OpSitePage defines model for OpSitePage.
type OpSitePage struct {
	Items  []OpSite `json:"items"`
	Limit  int      `json:"limit"`
	Offset int      `json:"offset"`
	Total  int64    `json:"total"`
}

// OpStrategy defines model for OpStrategy.
type OpStrategy struct {
	CreatedAt         time.Time            `json:"created_at"`
	DisplayName       string               `json:"display_name"`
	Enabled           bool                 `json:"enabled"`
	GroupKey          string               `json:"group_key"`
	Id                openapi_types.UUID   `json:"id"`
	Kind              OpStrategyKind       `json:"kind"`
	MemberRelationIds []openapi_types.UUID `json:"member_relation_ids"`
	SaleRatio         *string              `json:"sale_ratio,omitempty"`
	SiteId            openapi_types.UUID   `json:"site_id"`
	UpdatedAt         time.Time            `json:"updated_at"`
	Version           int64                `json:"version"`

	// Visible Desired Auto group entry access, including existing group-bound API keys. Effective opening also requires an enabled strategy and eligible members.
	Visible bool `json:"visible"`
}

// OpStrategyInput defines model for OpStrategyInput.
type OpStrategyInput struct {
	DisplayName       string               `json:"display_name"`
	Enabled           bool                 `json:"enabled"`
	MemberRelationIds []openapi_types.UUID `json:"member_relation_ids"`
	Reason            string               `json:"reason"`

	// Version Zero when creating a site strategy
	Version int64 `json:"version"`

	// Visible Desired Auto entry access. False closes the entry and rejects subsequent requests from existing API keys bound to this Auto group after synchronization. Opening also requires an enabled strategy with eligible members.
	Visible bool `json:"visible"`
}

// OpStrategyKind defines model for OpStrategyKind.
type OpStrategyKind string

// OpStrategyPage defines model for OpStrategyPage.
type OpStrategyPage struct {
	Items  []OpStrategy `json:"items"`
	Limit  int          `json:"limit"`
	Offset int          `json:"offset"`
	Total  int64        `json:"total"`
}

// OpSupplier defines model for OpSupplier.
type OpSupplier struct {
	Code                     string             `json:"code"`
	CreatedAt                time.Time          `json:"created_at"`
	CredentialVersion        int                `json:"credential_version"`
	Id                       openapi_types.UUID `json:"id"`
	Models                   []OpModelInput     `json:"models"`
	Name                     string             `json:"name"`
	PendingCredentialVersion *int               `json:"pending_credential_version,omitempty"`
	Protocol                 OpSupplierProtocol `json:"protocol"`
	Status                   OpSupplierStatus   `json:"status"`
	UpdatedAt                time.Time          `json:"updated_at"`
	UpstreamBaseUrl          string             `json:"upstream_base_url"`
	Version                  int64              `json:"version"`
}

// OpSupplierProtocol defines model for OpSupplier.Protocol.
type OpSupplierProtocol string

// OpSupplierStatus defines model for OpSupplier.Status.
type OpSupplierStatus string

// OpSupplierPage defines model for OpSupplierPage.
type OpSupplierPage struct {
	Items  []OpSupplier `json:"items"`
	Limit  int          `json:"limit"`
	Offset int          `json:"offset"`
	Total  int64        `json:"total"`
}

// OpSyncOperation defines model for OpSyncOperation.
type OpSyncOperation struct {
	Attempt          int                   `json:"attempt"`
	CompletedAt      *time.Time            `json:"completed_at,omitempty"`
	CreatedAt        time.Time             `json:"created_at"`
	CurrentStep      *string               `json:"current_step,omitempty"`
	Id               openapi_types.UUID    `json:"id"`
	LastErrorCode    *string               `json:"last_error_code,omitempty"`
	LastErrorMessage *string               `json:"last_error_message,omitempty"`
	NextAttemptAt    *time.Time            `json:"next_attempt_at,omitempty"`
	RoutePlanId      openapi_types.UUID    `json:"route_plan_id"`
	SiteId           openapi_types.UUID    `json:"site_id"`
	SiteSupplierId   openapi_types.UUID    `json:"site_supplier_id"`
	Status           OpSyncOperationStatus `json:"status"`
	Steps            []OpSyncStep          `json:"steps"`
	UpdatedAt        time.Time             `json:"updated_at"`
}

// OpSyncOperationStatus defines model for OpSyncOperation.Status.
type OpSyncOperationStatus string

// OpSyncOperationPage defines model for OpSyncOperationPage.
type OpSyncOperationPage struct {
	Items  []OpSyncOperation `json:"items"`
	Limit  int               `json:"limit"`
	Offset int               `json:"offset"`
	Total  int64             `json:"total"`
}

// OpSyncStep defines model for OpSyncStep.
type OpSyncStep struct {
	AfterSummary  *map[string]interface{} `json:"after_summary,omitempty"`
	BeforeSummary *map[string]interface{} `json:"before_summary,omitempty"`
	ErrorCode     *string                 `json:"error_code,omitempty"`
	ErrorMessage  *string                 `json:"error_message,omitempty"`
	FinishedAt    *time.Time              `json:"finished_at,omitempty"`
	OperationId   openapi_types.UUID      `json:"operation_id"`
	StartedAt     *time.Time              `json:"started_at,omitempty"`
	Status        OpSyncStepStatus        `json:"status"`
	StepKey       string                  `json:"step_key"`
}

// OpSyncStepStatus defines model for OpSyncStep.Status.
type OpSyncStepStatus string

// OpUpdateSiteInput defines model for OpUpdateSiteInput.
type OpUpdateSiteInput struct {
	AdminUserId       *int64                  `json:"admin_user_id,omitempty"`
	Code              *string                 `json:"code,omitempty"`
	Name              string                  `json:"name"`
	NewApiAccessToken *string                 `json:"new_api_access_token,omitempty"`
	NewApiBaseUrl     string                  `json:"new_api_base_url"`
	Reason            string                  `json:"reason"`
	Status            OpUpdateSiteInputStatus `json:"status"`
	Version           int64                   `json:"version"`
}

// OpUpdateSiteInputStatus defines model for OpUpdateSiteInput.Status.
type OpUpdateSiteInputStatus string

// OpUpdateSupplierInput defines model for OpUpdateSupplierInput.
type OpUpdateSupplierInput struct {
	Code            *string                     `json:"code,omitempty"`
	Models          []OpModelInput              `json:"models"`
	Name            string                      `json:"name"`
	Reason          string                      `json:"reason"`
	Status          OpUpdateSupplierInputStatus `json:"status"`
	UpstreamApiKey  *string                     `json:"upstream_api_key,omitempty"`
	UpstreamBaseUrl string                      `json:"upstream_base_url"`
	Version         int64                       `json:"version"`
}

// OpUpdateSupplierInputStatus defines model for OpUpdateSupplierInput.Status.
type OpUpdateSupplierInputStatus string

// OpID defines model for OpID.
type OpID = openapi_types.UUID

// OpIdempotencyKey defines model for OpIdempotencyKey.
type OpIdempotencyKey = string

// OpLimit defines model for OpLimit.
type OpLimit = int

// OpOffset defines model for OpOffset.
type OpOffset = int

// OpQuery defines model for OpQuery.
type OpQuery = string

// OpSiteFilter defines model for OpSiteFilter.
type OpSiteFilter = openapi_types.UUID

// OpSupplierFilter defines model for OpSupplierFilter.
type OpSupplierFilter = openapi_types.UUID

// OpPlans defines model for OpPlans.
type OpPlans = OpPlanResult

// OpListAuditParams defines parameters for OpListAudit.
type OpListAuditParams struct {
	Q          *OpQuery          `form:"q,omitempty" json:"q,omitempty"`
	SiteId     *OpSiteFilter     `form:"site_id,omitempty" json:"site_id,omitempty"`
	SupplierId *OpSupplierFilter `form:"supplier_id,omitempty" json:"supplier_id,omitempty"`
	Limit      *OpLimit          `form:"limit,omitempty" json:"limit,omitempty"`
	Offset     *OpOffset         `form:"offset,omitempty" json:"offset,omitempty"`
}

// OpDeploySupplierParams defines parameters for OpDeploySupplier.
type OpDeploySupplierParams struct {
	IdempotencyKey OpIdempotencyKey `json:"Idempotency-Key"`
}

// OpListPlansParams defines parameters for OpListPlans.
type OpListPlansParams struct {
	Q          *OpQuery          `form:"q,omitempty" json:"q,omitempty"`
	SiteId     *OpSiteFilter     `form:"site_id,omitempty" json:"site_id,omitempty"`
	SupplierId *OpSupplierFilter `form:"supplier_id,omitempty" json:"supplier_id,omitempty"`
	Limit      *OpLimit          `form:"limit,omitempty" json:"limit,omitempty"`
	Offset     *OpOffset         `form:"offset,omitempty" json:"offset,omitempty"`
}

// OpRestorePlanParams defines parameters for OpRestorePlan.
type OpRestorePlanParams struct {
	IdempotencyKey OpIdempotencyKey `json:"Idempotency-Key"`
}

// OpListPricesParams defines parameters for OpListPrices.
type OpListPricesParams struct {
	Q          *OpQuery          `form:"q,omitempty" json:"q,omitempty"`
	SiteId     *OpSiteFilter     `form:"site_id,omitempty" json:"site_id,omitempty"`
	SupplierId *OpSupplierFilter `form:"supplier_id,omitempty" json:"supplier_id,omitempty"`
	Limit      *OpLimit          `form:"limit,omitempty" json:"limit,omitempty"`
	Offset     *OpOffset         `form:"offset,omitempty" json:"offset,omitempty"`
}

// OpDraftPriceParams defines parameters for OpDraftPrice.
type OpDraftPriceParams struct {
	IdempotencyKey OpIdempotencyKey `json:"Idempotency-Key"`
}

// OpPublishPriceParams defines parameters for OpPublishPrice.
type OpPublishPriceParams struct {
	IdempotencyKey OpIdempotencyKey `json:"Idempotency-Key"`
}

// OpListRelationsParams defines parameters for OpListRelations.
type OpListRelationsParams struct {
	Q          *OpQuery          `form:"q,omitempty" json:"q,omitempty"`
	SiteId     *OpSiteFilter     `form:"site_id,omitempty" json:"site_id,omitempty"`
	SupplierId *OpSupplierFilter `form:"supplier_id,omitempty" json:"supplier_id,omitempty"`
	Limit      *OpLimit          `form:"limit,omitempty" json:"limit,omitempty"`
	Offset     *OpOffset         `form:"offset,omitempty" json:"offset,omitempty"`
}

// OpUpdateRelationParams defines parameters for OpUpdateRelation.
type OpUpdateRelationParams struct {
	IdempotencyKey OpIdempotencyKey `json:"Idempotency-Key"`
}

// OpListSitesParams defines parameters for OpListSites.
type OpListSitesParams struct {
	Q          *OpQuery          `form:"q,omitempty" json:"q,omitempty"`
	SiteId     *OpSiteFilter     `form:"site_id,omitempty" json:"site_id,omitempty"`
	SupplierId *OpSupplierFilter `form:"supplier_id,omitempty" json:"supplier_id,omitempty"`
	Limit      *OpLimit          `form:"limit,omitempty" json:"limit,omitempty"`
	Offset     *OpOffset         `form:"offset,omitempty" json:"offset,omitempty"`
}

// OpCreateSiteParams defines parameters for OpCreateSite.
type OpCreateSiteParams struct {
	IdempotencyKey OpIdempotencyKey `json:"Idempotency-Key"`
}

// OpUpdateSiteParams defines parameters for OpUpdateSite.
type OpUpdateSiteParams struct {
	IdempotencyKey OpIdempotencyKey `json:"Idempotency-Key"`
}

// OpSaveStrategyParams defines parameters for OpSaveStrategy.
type OpSaveStrategyParams struct {
	IdempotencyKey OpIdempotencyKey `json:"Idempotency-Key"`
}

// OpSyncSiteJSONBody defines parameters for OpSyncSite.
type OpSyncSiteJSONBody = map[string]interface{}

// OpSyncSiteParams defines parameters for OpSyncSite.
type OpSyncSiteParams struct {
	IdempotencyKey OpIdempotencyKey `json:"Idempotency-Key"`
}

// OpListStrategiesParams defines parameters for OpListStrategies.
type OpListStrategiesParams struct {
	Q          *OpQuery          `form:"q,omitempty" json:"q,omitempty"`
	SiteId     *OpSiteFilter     `form:"site_id,omitempty" json:"site_id,omitempty"`
	SupplierId *OpSupplierFilter `form:"supplier_id,omitempty" json:"supplier_id,omitempty"`
	Limit      *OpLimit          `form:"limit,omitempty" json:"limit,omitempty"`
	Offset     *OpOffset         `form:"offset,omitempty" json:"offset,omitempty"`
}

// OpListSuppliersParams defines parameters for OpListSuppliers.
type OpListSuppliersParams struct {
	Q          *OpQuery          `form:"q,omitempty" json:"q,omitempty"`
	SiteId     *OpSiteFilter     `form:"site_id,omitempty" json:"site_id,omitempty"`
	SupplierId *OpSupplierFilter `form:"supplier_id,omitempty" json:"supplier_id,omitempty"`
	Limit      *OpLimit          `form:"limit,omitempty" json:"limit,omitempty"`
	Offset     *OpOffset         `form:"offset,omitempty" json:"offset,omitempty"`
}

// OpCreateSupplierParams defines parameters for OpCreateSupplier.
type OpCreateSupplierParams struct {
	IdempotencyKey OpIdempotencyKey `json:"Idempotency-Key"`
}

// OpUpdateSupplierParams defines parameters for OpUpdateSupplier.
type OpUpdateSupplierParams struct {
	IdempotencyKey OpIdempotencyKey `json:"Idempotency-Key"`
}

// OpRotateCredentialParams defines parameters for OpRotateCredential.
type OpRotateCredentialParams struct {
	IdempotencyKey OpIdempotencyKey `json:"Idempotency-Key"`
}

// OpCancelCredentialParams defines parameters for OpCancelCredential.
type OpCancelCredentialParams struct {
	IdempotencyKey OpIdempotencyKey `json:"Idempotency-Key"`
}

// OpListSyncOperationsParams defines parameters for OpListSyncOperations.
type OpListSyncOperationsParams struct {
	Q          *OpQuery          `form:"q,omitempty" json:"q,omitempty"`
	SiteId     *OpSiteFilter     `form:"site_id,omitempty" json:"site_id,omitempty"`
	SupplierId *OpSupplierFilter `form:"supplier_id,omitempty" json:"supplier_id,omitempty"`
	Limit      *OpLimit          `form:"limit,omitempty" json:"limit,omitempty"`
	Offset     *OpOffset         `form:"offset,omitempty" json:"offset,omitempty"`
}

// OpAuthLoginJSONRequestBody defines body for OpAuthLogin for application/json ContentType.
type OpAuthLoginJSONRequestBody = OpLoginInput

// OpAuthSetupJSONRequestBody defines body for OpAuthSetup for application/json ContentType.
type OpAuthSetupJSONRequestBody = OpSetupInput

// OpDeploySupplierJSONRequestBody defines body for OpDeploySupplier for application/json ContentType.
type OpDeploySupplierJSONRequestBody = OpDeploymentInput

// OpRestorePlanJSONRequestBody defines body for OpRestorePlan for application/json ContentType.
type OpRestorePlanJSONRequestBody = OpRestoreInput

// OpDraftPriceJSONRequestBody defines body for OpDraftPrice for application/json ContentType.
type OpDraftPriceJSONRequestBody = OpPriceInput

// OpPublishPriceJSONRequestBody defines body for OpPublishPrice for application/json ContentType.
type OpPublishPriceJSONRequestBody = OpPublishInput

// OpUpdateRelationJSONRequestBody defines body for OpUpdateRelation for application/json ContentType.
type OpUpdateRelationJSONRequestBody = OpRelationInput

// OpCreateSiteJSONRequestBody defines body for OpCreateSite for application/json ContentType.
type OpCreateSiteJSONRequestBody = OpCreateSiteInput

// OpUpdateSiteJSONRequestBody defines body for OpUpdateSite for application/json ContentType.
type OpUpdateSiteJSONRequestBody = OpUpdateSiteInput

// OpSaveStrategyJSONRequestBody defines body for OpSaveStrategy for application/json ContentType.
type OpSaveStrategyJSONRequestBody = OpStrategyInput

// OpSyncSiteJSONRequestBody defines body for OpSyncSite for application/json ContentType.
type OpSyncSiteJSONRequestBody = OpSyncSiteJSONBody

// OpCreateSupplierJSONRequestBody defines body for OpCreateSupplier for application/json ContentType.
type OpCreateSupplierJSONRequestBody = OpCreateSupplierInput

// OpUpdateSupplierJSONRequestBody defines body for OpUpdateSupplier for application/json ContentType.
type OpUpdateSupplierJSONRequestBody = OpUpdateSupplierInput

// OpRotateCredentialJSONRequestBody defines body for OpRotateCredential for application/json ContentType.
type OpRotateCredentialJSONRequestBody = OpCredentialInput

// OpCancelCredentialJSONRequestBody defines body for OpCancelCredential for application/json ContentType.
type OpCancelCredentialJSONRequestBody = OpCredentialCancelInput

// Getter for additional properties for OpPlanReference. Returns the specified
// element and whether it was found
func (a OpPlanReference) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for OpPlanReference
func (a *OpPlanReference) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for OpPlanReference to handle AdditionalProperties
func (a *OpPlanReference) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &a.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
		delete(object, "id")
	}

	if raw, found := object["site_id"]; found {
		err = json.Unmarshal(raw, &a.SiteId)
		if err != nil {
			return fmt.Errorf("error reading 'site_id': %w", err)
		}
		delete(object, "site_id")
	}

	if raw, found := object["status"]; found {
		err = json.Unmarshal(raw, &a.Status)
		if err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		delete(object, "status")
	}

	if raw, found := object["version"]; found {
		err = json.Unmarshal(raw, &a.Version)
		if err != nil {
			return fmt.Errorf("error reading 'version': %w", err)
		}
		delete(object, "version")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for OpPlanReference to handle AdditionalProperties
func (a OpPlanReference) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["id"], err = json.Marshal(a.Id)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'id': %w", err)
	}

	object["site_id"], err = json.Marshal(a.SiteId)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'site_id': %w", err)
	}

	object["status"], err = json.Marshal(a.Status)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'status': %w", err)
	}

	object["version"], err = json.Marshal(a.Version)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'version': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
