// Package apispec provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apispec

import (
	"encoding/json"
	"fmt"
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for OpAuditActorType.
const (
	OpAuditActorTypeOperator OpAuditActorType = "operator"
	OpAuditActorTypeSystem   OpAuditActorType = "system"
)

// Valid indicates whether the value is a known member of the OpAuditActorType enum.
func (e OpAuditActorType) Valid() bool {
	switch e {
	case OpAuditActorTypeOperator:
		return true
	case OpAuditActorTypeSystem:
		return true
	default:
		return false
	}
}

// Defines values for OpAuthUserRole.
const (
	OpAuthUserRoleOwner OpAuthUserRole = "owner"
)

// Valid indicates whether the value is a known member of the OpAuthUserRole enum.
func (e OpAuthUserRole) Valid() bool {
	switch e {
	case OpAuthUserRoleOwner:
		return true
	default:
		return false
	}
}

// Defines values for OpAutomationDecisionAction.
const (
	OpAutomationDecisionActionExclude OpAutomationDecisionAction = "exclude"
	OpAutomationDecisionActionExit    OpAutomationDecisionAction = "exit"
	OpAutomationDecisionActionJoin    OpAutomationDecisionAction = "join"
	OpAutomationDecisionActionKeep    OpAutomationDecisionAction = "keep"
	OpAutomationDecisionActionRecover OpAutomationDecisionAction = "recover"
	OpAutomationDecisionActionWatch   OpAutomationDecisionAction = "watch"
)

// Valid indicates whether the value is a known member of the OpAutomationDecisionAction enum.
func (e OpAutomationDecisionAction) Valid() bool {
	switch e {
	case OpAutomationDecisionActionExclude:
		return true
	case OpAutomationDecisionActionExit:
		return true
	case OpAutomationDecisionActionJoin:
		return true
	case OpAutomationDecisionActionKeep:
		return true
	case OpAutomationDecisionActionRecover:
		return true
	case OpAutomationDecisionActionWatch:
		return true
	default:
		return false
	}
}

// Defines values for OpAutomationDecisionHoldAction.
const (
	OpAutomationDecisionHoldActionApply OpAutomationDecisionHoldAction = "apply"
	OpAutomationDecisionHoldActionClear OpAutomationDecisionHoldAction = "clear"
	OpAutomationDecisionHoldActionNone  OpAutomationDecisionHoldAction = "none"
)

// Valid indicates whether the value is a known member of the OpAutomationDecisionHoldAction enum.
func (e OpAutomationDecisionHoldAction) Valid() bool {
	switch e {
	case OpAutomationDecisionHoldActionApply:
		return true
	case OpAutomationDecisionHoldActionClear:
		return true
	case OpAutomationDecisionHoldActionNone:
		return true
	default:
		return false
	}
}

// Defines values for OpAutomationMode.
const (
	OpAutomationModeAutomatic OpAutomationMode = "automatic"
	OpAutomationModeManual    OpAutomationMode = "manual"
)

// Valid indicates whether the value is a known member of the OpAutomationMode enum.
func (e OpAutomationMode) Valid() bool {
	switch e {
	case OpAutomationModeAutomatic:
		return true
	case OpAutomationModeManual:
		return true
	default:
		return false
	}
}

// Defines values for OpAutomationRunStatus.
const (
	OpAutomationRunStatusFailed      OpAutomationRunStatus = "failed"
	OpAutomationRunStatusFrozen      OpAutomationRunStatus = "frozen"
	OpAutomationRunStatusNoChange    OpAutomationRunStatus = "no_change"
	OpAutomationRunStatusPendingSync OpAutomationRunStatus = "pending_sync"
	OpAutomationRunStatusPreview     OpAutomationRunStatus = "preview"
	OpAutomationRunStatusSucceeded   OpAutomationRunStatus = "succeeded"
	OpAutomationRunStatusUncertain   OpAutomationRunStatus = "uncertain"
)

// Valid indicates whether the value is a known member of the OpAutomationRunStatus enum.
func (e OpAutomationRunStatus) Valid() bool {
	switch e {
	case OpAutomationRunStatusFailed:
		return true
	case OpAutomationRunStatusFrozen:
		return true
	case OpAutomationRunStatusNoChange:
		return true
	case OpAutomationRunStatusPendingSync:
		return true
	case OpAutomationRunStatusPreview:
		return true
	case OpAutomationRunStatusSucceeded:
		return true
	case OpAutomationRunStatusUncertain:
		return true
	default:
		return false
	}
}

// Defines values for OpAutomationRunTriggerKind.
const (
	OpAutomationRunTriggerKindOperator  OpAutomationRunTriggerKind = "operator"
	OpAutomationRunTriggerKindScheduled OpAutomationRunTriggerKind = "scheduled"
)

// Valid indicates whether the value is a known member of the OpAutomationRunTriggerKind enum.
func (e OpAutomationRunTriggerKind) Valid() bool {
	switch e {
	case OpAutomationRunTriggerKindOperator:
		return true
	case OpAutomationRunTriggerKindScheduled:
		return true
	default:
		return false
	}
}

// Defines values for OpCreateSiteInputStatus.
const (
	OpCreateSiteInputStatusDisabled OpCreateSiteInputStatus = "disabled"
	OpCreateSiteInputStatusEnabled  OpCreateSiteInputStatus = "enabled"
)

// Valid indicates whether the value is a known member of the OpCreateSiteInputStatus enum.
func (e OpCreateSiteInputStatus) Valid() bool {
	switch e {
	case OpCreateSiteInputStatusDisabled:
		return true
	case OpCreateSiteInputStatusEnabled:
		return true
	default:
		return false
	}
}

// Defines values for OpCreateSupplierInputStatus.
const (
	OpCreateSupplierInputStatusDisabled OpCreateSupplierInputStatus = "disabled"
	OpCreateSupplierInputStatusEnabled  OpCreateSupplierInputStatus = "enabled"
)

// Valid indicates whether the value is a known member of the OpCreateSupplierInputStatus enum.
func (e OpCreateSupplierInputStatus) Valid() bool {
	switch e {
	case OpCreateSupplierInputStatusDisabled:
		return true
	case OpCreateSupplierInputStatusEnabled:
		return true
	default:
		return false
	}
}

// Defines values for OpEvaluationRunPurpose.
const (
	OpEvaluationRunPurposeAuthenticity OpEvaluationRunPurpose = "authenticity"
	OpEvaluationRunPurposeHealth       OpEvaluationRunPurpose = "health"
	OpEvaluationRunPurposeQuality      OpEvaluationRunPurpose = "quality"
	OpEvaluationRunPurposeRecovery     OpEvaluationRunPurpose = "recovery"
)

// Valid indicates whether the value is a known member of the OpEvaluationRunPurpose enum.
func (e OpEvaluationRunPurpose) Valid() bool {
	switch e {
	case OpEvaluationRunPurposeAuthenticity:
		return true
	case OpEvaluationRunPurposeHealth:
		return true
	case OpEvaluationRunPurposeQuality:
		return true
	case OpEvaluationRunPurposeRecovery:
		return true
	default:
		return false
	}
}

// Defines values for OpEvaluationRunStatus.
const (
	OpEvaluationRunStatusCancelled OpEvaluationRunStatus = "cancelled"
	OpEvaluationRunStatusFailed    OpEvaluationRunStatus = "failed"
	OpEvaluationRunStatusPending   OpEvaluationRunStatus = "pending"
	OpEvaluationRunStatusRunning   OpEvaluationRunStatus = "running"
	OpEvaluationRunStatusSucceeded OpEvaluationRunStatus = "succeeded"
	OpEvaluationRunStatusUncertain OpEvaluationRunStatus = "uncertain"
)

// Valid indicates whether the value is a known member of the OpEvaluationRunStatus enum.
func (e OpEvaluationRunStatus) Valid() bool {
	switch e {
	case OpEvaluationRunStatusCancelled:
		return true
	case OpEvaluationRunStatusFailed:
		return true
	case OpEvaluationRunStatusPending:
		return true
	case OpEvaluationRunStatusRunning:
		return true
	case OpEvaluationRunStatusSucceeded:
		return true
	case OpEvaluationRunStatusUncertain:
		return true
	default:
		return false
	}
}

// Defines values for OpEvaluationRunTargetKind.
const (
	OpEvaluationRunTargetKindSiteRoute      OpEvaluationRunTargetKind = "site_route"
	OpEvaluationRunTargetKindSupplierDirect OpEvaluationRunTargetKind = "supplier_direct"
)

// Valid indicates whether the value is a known member of the OpEvaluationRunTargetKind enum.
func (e OpEvaluationRunTargetKind) Valid() bool {
	switch e {
	case OpEvaluationRunTargetKindSiteRoute:
		return true
	case OpEvaluationRunTargetKindSupplierDirect:
		return true
	default:
		return false
	}
}

// Defines values for OpEvaluationRunInputPurpose.
const (
	OpEvaluationRunInputPurposeAuthenticity OpEvaluationRunInputPurpose = "authenticity"
	OpEvaluationRunInputPurposeHealth       OpEvaluationRunInputPurpose = "health"
	OpEvaluationRunInputPurposeQuality      OpEvaluationRunInputPurpose = "quality"
	OpEvaluationRunInputPurposeRecovery     OpEvaluationRunInputPurpose = "recovery"
)

// Valid indicates whether the value is a known member of the OpEvaluationRunInputPurpose enum.
func (e OpEvaluationRunInputPurpose) Valid() bool {
	switch e {
	case OpEvaluationRunInputPurposeAuthenticity:
		return true
	case OpEvaluationRunInputPurposeHealth:
		return true
	case OpEvaluationRunInputPurposeQuality:
		return true
	case OpEvaluationRunInputPurposeRecovery:
		return true
	default:
		return false
	}
}

// Defines values for OpEvaluationRunInputTargetKind.
const (
	OpEvaluationRunInputTargetKindSupplierDirect OpEvaluationRunInputTargetKind = "supplier_direct"
)

// Valid indicates whether the value is a known member of the OpEvaluationRunInputTargetKind enum.
func (e OpEvaluationRunInputTargetKind) Valid() bool {
	switch e {
	case OpEvaluationRunInputTargetKindSupplierDirect:
		return true
	default:
		return false
	}
}

// Defines values for OpIssuedSiteProductTokenStatus.
const (
	OpIssuedSiteProductTokenStatusActive  OpIssuedSiteProductTokenStatus = "active"
	OpIssuedSiteProductTokenStatusRevoked OpIssuedSiteProductTokenStatus = "revoked"
)

// Valid indicates whether the value is a known member of the OpIssuedSiteProductTokenStatus enum.
func (e OpIssuedSiteProductTokenStatus) Valid() bool {
	switch e {
	case OpIssuedSiteProductTokenStatusActive:
		return true
	case OpIssuedSiteProductTokenStatusRevoked:
		return true
	default:
		return false
	}
}

// Defines values for OpModelInputCurrency.
const (
	OpModelInputCurrencyCNY OpModelInputCurrency = "CNY"
	OpModelInputCurrencyUSD OpModelInputCurrency = "USD"
)

// Valid indicates whether the value is a known member of the OpModelInputCurrency enum.
func (e OpModelInputCurrency) Valid() bool {
	switch e {
	case OpModelInputCurrencyCNY:
		return true
	case OpModelInputCurrencyUSD:
		return true
	default:
		return false
	}
}

// Defines values for OpPlanStatus.
const (
	OpPlanStatusApplying   OpPlanStatus = "applying"
	OpPlanStatusConfirmed  OpPlanStatus = "confirmed"
	OpPlanStatusFailed     OpPlanStatus = "failed"
	OpPlanStatusPending    OpPlanStatus = "pending"
	OpPlanStatusSuperseded OpPlanStatus = "superseded"
	OpPlanStatusUncertain  OpPlanStatus = "uncertain"
)

// Valid indicates whether the value is a known member of the OpPlanStatus enum.
func (e OpPlanStatus) Valid() bool {
	switch e {
	case OpPlanStatusApplying:
		return true
	case OpPlanStatusConfirmed:
		return true
	case OpPlanStatusFailed:
		return true
	case OpPlanStatusPending:
		return true
	case OpPlanStatusSuperseded:
		return true
	case OpPlanStatusUncertain:
		return true
	default:
		return false
	}
}

// Defines values for OpPriceStatus.
const (
	OpPriceStatusApplied    OpPriceStatus = "applied"
	OpPriceStatusDraft      OpPriceStatus = "draft"
	OpPriceStatusPublished  OpPriceStatus = "published"
	OpPriceStatusSuperseded OpPriceStatus = "superseded"
)

// Valid indicates whether the value is a known member of the OpPriceStatus enum.
func (e OpPriceStatus) Valid() bool {
	switch e {
	case OpPriceStatusApplied:
		return true
	case OpPriceStatusDraft:
		return true
	case OpPriceStatusPublished:
		return true
	case OpPriceStatusSuperseded:
		return true
	default:
		return false
	}
}

// Defines values for OpRelationDesiredStatus.
const (
	OpRelationDesiredStatusDisabled  OpRelationDesiredStatus = "disabled"
	OpRelationDesiredStatusEnabled   OpRelationDesiredStatus = "enabled"
	OpRelationDesiredStatusObserving OpRelationDesiredStatus = "observing"
)

// Valid indicates whether the value is a known member of the OpRelationDesiredStatus enum.
func (e OpRelationDesiredStatus) Valid() bool {
	switch e {
	case OpRelationDesiredStatusDisabled:
		return true
	case OpRelationDesiredStatusEnabled:
		return true
	case OpRelationDesiredStatusObserving:
		return true
	default:
		return false
	}
}

// Defines values for OpRelationSyncStatus.
const (
	OpRelationSyncStatusActive       OpRelationSyncStatus = "active"
	OpRelationSyncStatusFailed       OpRelationSyncStatus = "failed"
	OpRelationSyncStatusManualLocked OpRelationSyncStatus = "manual_locked"
	OpRelationSyncStatusPending      OpRelationSyncStatus = "pending"
	OpRelationSyncStatusSyncing      OpRelationSyncStatus = "syncing"
)

// Valid indicates whether the value is a known member of the OpRelationSyncStatus enum.
func (e OpRelationSyncStatus) Valid() bool {
	switch e {
	case OpRelationSyncStatusActive:
		return true
	case OpRelationSyncStatusFailed:
		return true
	case OpRelationSyncStatusManualLocked:
		return true
	case OpRelationSyncStatusPending:
		return true
	case OpRelationSyncStatusSyncing:
		return true
	default:
		return false
	}
}

// Defines values for OpRelationInputDesiredStatus.
const (
	OpRelationInputDesiredStatusDisabled OpRelationInputDesiredStatus = "disabled"
	OpRelationInputDesiredStatusEnabled  OpRelationInputDesiredStatus = "enabled"
)

// Valid indicates whether the value is a known member of the OpRelationInputDesiredStatus enum.
func (e OpRelationInputDesiredStatus) Valid() bool {
	switch e {
	case OpRelationInputDesiredStatusDisabled:
		return true
	case OpRelationInputDesiredStatusEnabled:
		return true
	default:
		return false
	}
}

// Defines values for OpScoreInsightAuthenticityVerdict.
const (
	OpScoreInsightAuthenticityVerdictConsistent   OpScoreInsightAuthenticityVerdict = "consistent"
	OpScoreInsightAuthenticityVerdictInconsistent OpScoreInsightAuthenticityVerdict = "inconsistent"
	OpScoreInsightAuthenticityVerdictInsufficient OpScoreInsightAuthenticityVerdict = "insufficient"
	OpScoreInsightAuthenticityVerdictSuspicious   OpScoreInsightAuthenticityVerdict = "suspicious"
)

// Valid indicates whether the value is a known member of the OpScoreInsightAuthenticityVerdict enum.
func (e OpScoreInsightAuthenticityVerdict) Valid() bool {
	switch e {
	case OpScoreInsightAuthenticityVerdictConsistent:
		return true
	case OpScoreInsightAuthenticityVerdictInconsistent:
		return true
	case OpScoreInsightAuthenticityVerdictInsufficient:
		return true
	case OpScoreInsightAuthenticityVerdictSuspicious:
		return true
	default:
		return false
	}
}

// Defines values for OpScoreInsightConfidence.
const (
	OpScoreInsightConfidenceHigh         OpScoreInsightConfidence = "high"
	OpScoreInsightConfidenceInsufficient OpScoreInsightConfidence = "insufficient"
	OpScoreInsightConfidenceLow          OpScoreInsightConfidence = "low"
	OpScoreInsightConfidenceMedium       OpScoreInsightConfidence = "medium"
)

// Valid indicates whether the value is a known member of the OpScoreInsightConfidence enum.
func (e OpScoreInsightConfidence) Valid() bool {
	switch e {
	case OpScoreInsightConfidenceHigh:
		return true
	case OpScoreInsightConfidenceInsufficient:
		return true
	case OpScoreInsightConfidenceLow:
		return true
	case OpScoreInsightConfidenceMedium:
		return true
	default:
		return false
	}
}

// Defines values for OpScoreInsightEligibility.
const (
	OpScoreInsightEligibilityEligible     OpScoreInsightEligibility = "eligible"
	OpScoreInsightEligibilityExcluded     OpScoreInsightEligibility = "excluded"
	OpScoreInsightEligibilityInsufficient OpScoreInsightEligibility = "insufficient"
)

// Valid indicates whether the value is a known member of the OpScoreInsightEligibility enum.
func (e OpScoreInsightEligibility) Valid() bool {
	switch e {
	case OpScoreInsightEligibilityEligible:
		return true
	case OpScoreInsightEligibilityExcluded:
		return true
	case OpScoreInsightEligibilityInsufficient:
		return true
	default:
		return false
	}
}

// Defines values for OpShadowRecommendationAction.
const (
	OpShadowRecommendationActionExclude OpShadowRecommendationAction = "exclude"
	OpShadowRecommendationActionExit    OpShadowRecommendationAction = "exit"
	OpShadowRecommendationActionJoin    OpShadowRecommendationAction = "join"
	OpShadowRecommendationActionKeep    OpShadowRecommendationAction = "keep"
	OpShadowRecommendationActionWatch   OpShadowRecommendationAction = "watch"
)

// Valid indicates whether the value is a known member of the OpShadowRecommendationAction enum.
func (e OpShadowRecommendationAction) Valid() bool {
	switch e {
	case OpShadowRecommendationActionExclude:
		return true
	case OpShadowRecommendationActionExit:
		return true
	case OpShadowRecommendationActionJoin:
		return true
	case OpShadowRecommendationActionKeep:
		return true
	case OpShadowRecommendationActionWatch:
		return true
	default:
		return false
	}
}

// Defines values for OpShadowRecommendationConfidence.
const (
	OpShadowRecommendationConfidenceHigh         OpShadowRecommendationConfidence = "high"
	OpShadowRecommendationConfidenceInsufficient OpShadowRecommendationConfidence = "insufficient"
	OpShadowRecommendationConfidenceLow          OpShadowRecommendationConfidence = "low"
	OpShadowRecommendationConfidenceMedium       OpShadowRecommendationConfidence = "medium"
)

// Valid indicates whether the value is a known member of the OpShadowRecommendationConfidence enum.
func (e OpShadowRecommendationConfidence) Valid() bool {
	switch e {
	case OpShadowRecommendationConfidenceHigh:
		return true
	case OpShadowRecommendationConfidenceInsufficient:
		return true
	case OpShadowRecommendationConfidenceLow:
		return true
	case OpShadowRecommendationConfidenceMedium:
		return true
	default:
		return false
	}
}

// Defines values for OpShadowRecommendationStrategyKind.
const (
	OpShadowRecommendationStrategyKindBalanced    OpShadowRecommendationStrategyKind = "balanced"
	OpShadowRecommendationStrategyKindHighQuality OpShadowRecommendationStrategyKind = "high_quality"
	OpShadowRecommendationStrategyKindHighSla     OpShadowRecommendationStrategyKind = "high_sla"
	OpShadowRecommendationStrategyKindLowLatency  OpShadowRecommendationStrategyKind = "low_latency"
	OpShadowRecommendationStrategyKindLowestPrice OpShadowRecommendationStrategyKind = "lowest_price"
)

// Valid indicates whether the value is a known member of the OpShadowRecommendationStrategyKind enum.
func (e OpShadowRecommendationStrategyKind) Valid() bool {
	switch e {
	case OpShadowRecommendationStrategyKindBalanced:
		return true
	case OpShadowRecommendationStrategyKindHighQuality:
		return true
	case OpShadowRecommendationStrategyKindHighSla:
		return true
	case OpShadowRecommendationStrategyKindLowLatency:
		return true
	case OpShadowRecommendationStrategyKindLowestPrice:
		return true
	default:
		return false
	}
}

// Defines values for OpSiteCompatibilityStatus.
const (
	OpSiteCompatibilityStatusCompatible   OpSiteCompatibilityStatus = "compatible"
	OpSiteCompatibilityStatusIncompatible OpSiteCompatibilityStatus = "incompatible"
	OpSiteCompatibilityStatusUnknown      OpSiteCompatibilityStatus = "unknown"
)

// Valid indicates whether the value is a known member of the OpSiteCompatibilityStatus enum.
func (e OpSiteCompatibilityStatus) Valid() bool {
	switch e {
	case OpSiteCompatibilityStatusCompatible:
		return true
	case OpSiteCompatibilityStatusIncompatible:
		return true
	case OpSiteCompatibilityStatusUnknown:
		return true
	default:
		return false
	}
}

// Defines values for OpSiteStatus.
const (
	OpSiteStatusDisabled OpSiteStatus = "disabled"
	OpSiteStatusEnabled  OpSiteStatus = "enabled"
)

// Valid indicates whether the value is a known member of the OpSiteStatus enum.
func (e OpSiteStatus) Valid() bool {
	switch e {
	case OpSiteStatusDisabled:
		return true
	case OpSiteStatusEnabled:
		return true
	default:
		return false
	}
}

// Defines values for OpSiteProductTokenStatus.
const (
	OpSiteProductTokenStatusActive  OpSiteProductTokenStatus = "active"
	OpSiteProductTokenStatusRevoked OpSiteProductTokenStatus = "revoked"
)

// Valid indicates whether the value is a known member of the OpSiteProductTokenStatus enum.
func (e OpSiteProductTokenStatus) Valid() bool {
	switch e {
	case OpSiteProductTokenStatusActive:
		return true
	case OpSiteProductTokenStatusRevoked:
		return true
	default:
		return false
	}
}

// Defines values for OpStrategyKind.
const (
	OpStrategyKindBalanced    OpStrategyKind = "balanced"
	OpStrategyKindHighQuality OpStrategyKind = "high_quality"
	OpStrategyKindHighSla     OpStrategyKind = "high_sla"
	OpStrategyKindLowLatency  OpStrategyKind = "low_latency"
	OpStrategyKindLowestPrice OpStrategyKind = "lowest_price"
)

// Valid indicates whether the value is a known member of the OpStrategyKind enum.
func (e OpStrategyKind) Valid() bool {
	switch e {
	case OpStrategyKindBalanced:
		return true
	case OpStrategyKindHighQuality:
		return true
	case OpStrategyKindHighSla:
		return true
	case OpStrategyKindLowLatency:
		return true
	case OpStrategyKindLowestPrice:
		return true
	default:
		return false
	}
}

// Defines values for OpSupplierProtocol.
const (
	OpSupplierProtocolOpenaiCompatible OpSupplierProtocol = "openai_compatible"
)

// Valid indicates whether the value is a known member of the OpSupplierProtocol enum.
func (e OpSupplierProtocol) Valid() bool {
	switch e {
	case OpSupplierProtocolOpenaiCompatible:
		return true
	default:
		return false
	}
}

// Defines values for OpSupplierStatus.
const (
	OpSupplierStatusDisabled OpSupplierStatus = "disabled"
	OpSupplierStatusDraft    OpSupplierStatus = "draft"
	OpSupplierStatusEnabled  OpSupplierStatus = "enabled"
)

// Valid indicates whether the value is a known member of the OpSupplierStatus enum.
func (e OpSupplierStatus) Valid() bool {
	switch e {
	case OpSupplierStatusDisabled:
		return true
	case OpSupplierStatusDraft:
		return true
	case OpSupplierStatusEnabled:
		return true
	default:
		return false
	}
}

// Defines values for OpSyncOperationStatus.
const (
	OpSyncOperationStatusManualRequired  OpSyncOperationStatus = "manual_required"
	OpSyncOperationStatusPending         OpSyncOperationStatus = "pending"
	OpSyncOperationStatusRetryableFailed OpSyncOperationStatus = "retryable_failed"
	OpSyncOperationStatusRunning         OpSyncOperationStatus = "running"
	OpSyncOperationStatusSucceeded       OpSyncOperationStatus = "succeeded"
	OpSyncOperationStatusSuperseded      OpSyncOperationStatus = "superseded"
	OpSyncOperationStatusUncertain       OpSyncOperationStatus = "uncertain"
)

// Valid indicates whether the value is a known member of the OpSyncOperationStatus enum.
func (e OpSyncOperationStatus) Valid() bool {
	switch e {
	case OpSyncOperationStatusManualRequired:
		return true
	case OpSyncOperationStatusPending:
		return true
	case OpSyncOperationStatusRetryableFailed:
		return true
	case OpSyncOperationStatusRunning:
		return true
	case OpSyncOperationStatusSucceeded:
		return true
	case OpSyncOperationStatusSuperseded:
		return true
	case OpSyncOperationStatusUncertain:
		return true
	default:
		return false
	}
}

// Defines values for OpSyncStepStatus.
const (
	OpSyncStepStatusFailed    OpSyncStepStatus = "failed"
	OpSyncStepStatusPending   OpSyncStepStatus = "pending"
	OpSyncStepStatusRunning   OpSyncStepStatus = "running"
	OpSyncStepStatusSucceeded OpSyncStepStatus = "succeeded"
	OpSyncStepStatusUncertain OpSyncStepStatus = "uncertain"
)

// Valid indicates whether the value is a known member of the OpSyncStepStatus enum.
func (e OpSyncStepStatus) Valid() bool {
	switch e {
	case OpSyncStepStatusFailed:
		return true
	case OpSyncStepStatusPending:
		return true
	case OpSyncStepStatusRunning:
		return true
	case OpSyncStepStatusSucceeded:
		return true
	case OpSyncStepStatusUncertain:
		return true
	default:
		return false
	}
}

// Defines values for OpTrustedReferenceTrust.
const (
	OpTrustedReferenceTrustCommunity       OpTrustedReferenceTrust = "community"
	OpTrustedReferenceTrustOfficial        OpTrustedReferenceTrust = "official"
	OpTrustedReferenceTrustOperatorTrusted OpTrustedReferenceTrust = "operator_trusted"
)

// Valid indicates whether the value is a known member of the OpTrustedReferenceTrust enum.
func (e OpTrustedReferenceTrust) Valid() bool {
	switch e {
	case OpTrustedReferenceTrustCommunity:
		return true
	case OpTrustedReferenceTrustOfficial:
		return true
	case OpTrustedReferenceTrustOperatorTrusted:
		return true
	default:
		return false
	}
}

// Defines values for OpTrustedReferenceInputTrust.
const (
	OpTrustedReferenceInputTrustCommunity       OpTrustedReferenceInputTrust = "community"
	OpTrustedReferenceInputTrustOfficial        OpTrustedReferenceInputTrust = "official"
	OpTrustedReferenceInputTrustOperatorTrusted OpTrustedReferenceInputTrust = "operator_trusted"
)

// Valid indicates whether the value is a known member of the OpTrustedReferenceInputTrust enum.
func (e OpTrustedReferenceInputTrust) Valid() bool {
	switch e {
	case OpTrustedReferenceInputTrustCommunity:
		return true
	case OpTrustedReferenceInputTrustOfficial:
		return true
	case OpTrustedReferenceInputTrustOperatorTrusted:
		return true
	default:
		return false
	}
}

// Defines values for OpUpdateSiteInputStatus.
const (
	OpUpdateSiteInputStatusDisabled OpUpdateSiteInputStatus = "disabled"
	OpUpdateSiteInputStatusEnabled  OpUpdateSiteInputStatus = "enabled"
)

// Valid indicates whether the value is a known member of the OpUpdateSiteInputStatus enum.
func (e OpUpdateSiteInputStatus) Valid() bool {
	switch e {
	case OpUpdateSiteInputStatusDisabled:
		return true
	case OpUpdateSiteInputStatusEnabled:
		return true
	default:
		return false
	}
}

// Defines values for OpUpdateSupplierInputStatus.
const (
	OpUpdateSupplierInputStatusDisabled OpUpdateSupplierInputStatus = "disabled"
	OpUpdateSupplierInputStatusEnabled  OpUpdateSupplierInputStatus = "enabled"
)

// Valid indicates whether the value is a known member of the OpUpdateSupplierInputStatus enum.
func (e OpUpdateSupplierInputStatus) Valid() bool {
	switch e {
	case OpUpdateSupplierInputStatusDisabled:
		return true
	case OpUpdateSupplierInputStatusEnabled:
		return true
	default:
		return false
	}
}

// Defines values for OpListEvaluationRunsParamsPurpose.
const (
	OpListEvaluationRunsParamsPurposeAuthenticity OpListEvaluationRunsParamsPurpose = "authenticity"
	OpListEvaluationRunsParamsPurposeHealth       OpListEvaluationRunsParamsPurpose = "health"
	OpListEvaluationRunsParamsPurposeQuality      OpListEvaluationRunsParamsPurpose = "quality"
	OpListEvaluationRunsParamsPurposeRecovery     OpListEvaluationRunsParamsPurpose = "recovery"
)

// Valid indicates whether the value is a known member of the OpListEvaluationRunsParamsPurpose enum.
func (e OpListEvaluationRunsParamsPurpose) Valid() bool {
	switch e {
	case OpListEvaluationRunsParamsPurposeAuthenticity:
		return true
	case OpListEvaluationRunsParamsPurposeHealth:
		return true
	case OpListEvaluationRunsParamsPurposeQuality:
		return true
	case OpListEvaluationRunsParamsPurposeRecovery:
		return true
	default:
		return false
	}
}

// Defines values for OpRefreshScores200JSONResponseBodyStatus.
const (
	OpRefreshScores200JSONResponseBodyStatusCompleted OpRefreshScores200JSONResponseBodyStatus = "completed"
)

// Valid indicates whether the value is a known member of the OpRefreshScores200JSONResponseBodyStatus enum.
func (e OpRefreshScores200JSONResponseBodyStatus) Valid() bool {
	switch e {
	case OpRefreshScores200JSONResponseBodyStatusCompleted:
		return true
	default:
		return false
	}
}

// Defines values for OpRevokeSiteProductToken200JSONResponseBodyStatus.
const (
	OpRevokeSiteProductToken200JSONResponseBodyStatusRevoked OpRevokeSiteProductToken200JSONResponseBodyStatus = "revoked"
)

// Valid indicates whether the value is a known member of the OpRevokeSiteProductToken200JSONResponseBodyStatus enum.
func (e OpRevokeSiteProductToken200JSONResponseBodyStatus) Valid() bool {
	switch e {
	case OpRevokeSiteProductToken200JSONResponseBodyStatusRevoked:
		return true
	default:
		return false
	}
}

// OpAudit defines model for OpAudit.
type OpAudit struct {
	Action      string                  `json:"action"`
	ActorId     string                  `json:"actor_id"`
	ActorType   OpAuditActorType        `json:"actor_type"`
	CreatedAt   time.Time               `json:"created_at"`
	Id          openapi_types.UUID      `json:"id"`
	NewSummary  *map[string]interface{} `json:"new_summary,omitempty"`
	ObjectId    string                  `json:"object_id"`
	ObjectType  string                  `json:"object_type"`
	OldSummary  *map[string]interface{} `json:"old_summary,omitempty"`
	OperationId *openapi_types.UUID     `json:"operation_id,omitempty"`
	Reason      string                  `json:"reason"`
	Result      string                  `json:"result"`
	SiteId      *openapi_types.UUID     `json:"site_id,omitempty"`
}

// OpAuditActorType defines model for OpAudit.ActorType.
type OpAuditActorType string

// OpAuditPage defines model for OpAuditPage.
type OpAuditPage struct {
	Items  []OpAudit `json:"items"`
	Limit  int       `json:"limit"`
	Offset int       `json:"offset"`
	Total  int64     `json:"total"`
}

// OpAuthSession defines model for OpAuthSession.
type OpAuthSession struct {
	CsrfToken string     `json:"csrf_token"`
	User      OpAuthUser `json:"user"`
}

// OpAuthStatus defines model for OpAuthStatus.
type OpAuthStatus struct {
	Initialized bool `json:"initialized"`
}

// OpAuthUser defines model for OpAuthUser.
type OpAuthUser struct {
	Id       openapi_types.UUID `json:"id"`
	Role     OpAuthUserRole     `json:"role"`
	Username string             `json:"username"`
}

// OpAuthUserRole defines model for OpAuthUser.Role.
type OpAuthUserRole string

// OpAutomationDecision defines model for OpAutomationDecision.
type OpAutomationDecision struct {
	Action        OpAutomationDecisionAction     `json:"action"`
	CreatedAt     time.Time                      `json:"created_at"`
	CurrentMember bool                           `json:"current_member"`
	HoldAction    OpAutomationDecisionHoldAction `json:"hold_action"`
	Id            openapi_types.UUID             `json:"id"`
	Reasons       []string                       `json:"reasons"`
	RelationId    openapi_types.UUID             `json:"relation_id"`
	StrategyKind  OpStrategyKind                 `json:"strategy_kind"`
	SupplierName  string                         `json:"supplier_name"`
	TargetMember  bool                           `json:"target_member"`
}

// OpAutomationDecisionAction defines model for OpAutomationDecision.Action.
type OpAutomationDecisionAction string

// OpAutomationDecisionHoldAction defines model for OpAutomationDecision.HoldAction.
type OpAutomationDecisionHoldAction string

// OpAutomationMode defines model for OpAutomationMode.
type OpAutomationMode string

// OpAutomationRun defines model for OpAutomationRun.
type OpAutomationRun struct {
	CompletedAt time.Time                  `json:"completed_at"`
	Decisions   []OpAutomationDecision     `json:"decisions"`
	Id          openapi_types.UUID         `json:"id"`
	RoutePlanId *openapi_types.UUID        `json:"route_plan_id,omitempty"`
	ScoreRunId  openapi_types.UUID         `json:"score_run_id"`
	SiteId      openapi_types.UUID         `json:"site_id"`
	StartedAt   time.Time                  `json:"started_at"`
	Status      OpAutomationRunStatus      `json:"status"`
	Summary     string                     `json:"summary"`
	TriggerKind OpAutomationRunTriggerKind `json:"trigger_kind"`
}

// OpAutomationRunStatus defines model for OpAutomationRun.Status.
type OpAutomationRunStatus string

// OpAutomationRunTriggerKind defines model for OpAutomationRun.TriggerKind.
type OpAutomationRunTriggerKind string

// OpAutomationRunInput defines model for OpAutomationRunInput.
type OpAutomationRunInput struct {
	SiteId openapi_types.UUID `json:"site_id"`
}

// OpAutomationRunPage defines model for OpAutomationRunPage.
type OpAutomationRunPage struct {
	Items  []OpAutomationRun `json:"items"`
	Limit  int               `json:"limit"`
	Offset int               `json:"offset"`
	Total  int64             `json:"total"`
}

// OpAutomationSetting defines model for OpAutomationSetting.
type OpAutomationSetting struct {
	DisplayName             string             `json:"display_name"`
	EntryClosedByAutomation bool               `json:"entry_closed_by_automation"`
	Mode                    OpAutomationMode   `json:"mode"`
	Reason                  string             `json:"reason"`
	SiteId                  openapi_types.UUID `json:"site_id"`
	StrategyId              openapi_types.UUID `json:"strategy_id"`
	StrategyKind            OpStrategyKind     `json:"strategy_kind"`
	UpdatedAt               time.Time          `json:"updated_at"`
	UpdatedBy               string             `json:"updated_by"`
	Version                 int64              `json:"version"`
}

// OpAutomationSettingInput defines model for OpAutomationSettingInput.
type OpAutomationSettingInput struct {
	Mode    OpAutomationMode `json:"mode"`
	Reason  string           `json:"reason"`
	Version int64            `json:"version"`
}

// OpAutomationSettingList defines model for OpAutomationSettingList.
type OpAutomationSettingList struct {
	Items []OpAutomationSetting `json:"items"`
}

// OpCollectionRunInput defines model for OpCollectionRunInput.
type OpCollectionRunInput struct {
	SiteId openapi_types.UUID `json:"site_id"`
}

// OpCollectionRunResult defines model for OpCollectionRunResult.
type OpCollectionRunResult struct {
	CursorTime     *time.Time         `json:"cursor_time,omitempty"`
	DataGap        bool               `json:"data_gap"`
	ErrorCode      *string            `json:"error_code,omitempty"`
	ReadRecords    int                `json:"read_records"`
	SavedAttempts  int                `json:"saved_attempts"`
	SavedRequests  int                `json:"saved_requests"`
	ScannedThrough *time.Time         `json:"scanned_through,omitempty"`
	SiteId         openapi_types.UUID `json:"site_id"`
	SiteName       string             `json:"site_name"`
	SourceLatest   *time.Time         `json:"source_latest,omitempty"`
}

// OpCollectionStatus defines model for OpCollectionStatus.
type OpCollectionStatus struct {
	ConsecutiveFailures int                `json:"consecutive_failures"`
	ContractVersion     string             `json:"contract_version"`
	CursorTime          *time.Time         `json:"cursor_time,omitempty"`
	DataGap             bool               `json:"data_gap"`
	LastErrorAt         *time.Time         `json:"last_error_at,omitempty"`
	LastErrorCode       *string            `json:"last_error_code,omitempty"`
	LastErrorMessage    *string            `json:"last_error_message,omitempty"`
	LastReadAt          *time.Time         `json:"last_read_at,omitempty"`
	LastSuccessAt       *time.Time         `json:"last_success_at,omitempty"`
	ScannedThrough      *time.Time         `json:"scanned_through,omitempty"`
	SiteId              openapi_types.UUID `json:"site_id"`
	SiteName            string             `json:"site_name"`
	SourceKind          string             `json:"source_kind"`
	SourceLatest        *time.Time         `json:"source_latest,omitempty"`
	UpdatedAt           *time.Time         `json:"updated_at,omitempty"`
}

// OpCollectionStatusList defines model for OpCollectionStatusList.
type OpCollectionStatusList struct {
	Items []OpCollectionStatus `json:"items"`
}

// OpCreateSiteInput defines model for OpCreateSiteInput.
type OpCreateSiteInput struct {
	AdminUserId       *int64                   `json:"admin_user_id,omitempty"`
	Code              string                   `json:"code"`
	Name              string                   `json:"name"`
	NewApiAccessToken *string                  `json:"new_api_access_token,omitempty"`
	NewApiBaseUrl     string                   `json:"new_api_base_url"`
	Reason            *string                  `json:"reason,omitempty"`
	Status            *OpCreateSiteInputStatus `json:"status,omitempty"`
	Version           *int64                   `json:"version,omitempty"`
}

// OpCreateSiteInputStatus defines model for OpCreateSiteInput.Status.
type OpCreateSiteInputStatus string

// OpCreateSupplierInput defines model for OpCreateSupplierInput.
type OpCreateSupplierInput struct {
	Code            string                       `json:"code"`
	Models          []OpModelInput               `json:"models"`
	Name            string                       `json:"name"`
	Reason          *string                      `json:"reason,omitempty"`
	Status          *OpCreateSupplierInputStatus `json:"status,omitempty"`
	UpstreamApiKey  *string                      `json:"upstream_api_key,omitempty"`
	UpstreamBaseUrl string                       `json:"upstream_base_url"`
	Version         *int64                       `json:"version,omitempty"`
}

// OpCreateSupplierInputStatus defines model for OpCreateSupplierInput.Status.
type OpCreateSupplierInputStatus string

// OpCredentialCancelInput defines model for OpCredentialCancelInput.
type OpCredentialCancelInput struct {
	Reason  string `json:"reason"`
	Version int64  `json:"version"`
}

// OpCredentialInput defines model for OpCredentialInput.
type OpCredentialInput struct {
	ApiKey  *string `json:"api_key,omitempty"`
	Reason  string  `json:"reason"`
	Version int64   `json:"version"`
}

// OpDeploymentInput defines model for OpDeploymentInput.
type OpDeploymentInput struct {
	Reason     string               `json:"reason"`
	Sites      []OpDeploymentTarget `json:"sites"`
	SupplierId openapi_types.UUID   `json:"supplier_id"`
}

// OpDeploymentTarget defines model for OpDeploymentTarget.
type OpDeploymentTarget struct {
	GroupDisplayName string `json:"group_display_name"`

	// SaleRatio Positive decimal up to 999999.999999
	SaleRatio string             `json:"sale_ratio"`
	SiteId    openapi_types.UUID `json:"site_id"`

	// Visible Open the dedicated group entry when true. False closes the entry and rejects subsequent requests from existing API keys bound to this group after synchronization; the supplier can still serve other open Auto groups.
	Visible bool `json:"visible"`
}

// OpError defines model for OpError.
type OpError struct {
	Code      string `json:"code"`
	Message   string `json:"message"`
	RequestId string `json:"request_id"`
}

// OpEvaluationRun defines model for OpEvaluationRun.
type OpEvaluationRun struct {
	AlgorithmVersion string                    `json:"algorithm_version"`
	CompletedAt      *time.Time                `json:"completed_at,omitempty"`
	CompletedSamples int                       `json:"completed_samples"`
	ErrorCode        *string                   `json:"error_code,omitempty"`
	ErrorMessage     *string                   `json:"error_message,omitempty"`
	Id               openapi_types.UUID        `json:"id"`
	Model            string                    `json:"model"`
	NextRetryAt      *time.Time                `json:"next_retry_at,omitempty"`
	PlannedSamples   int                       `json:"planned_samples"`
	Purpose          OpEvaluationRunPurpose    `json:"purpose"`
	ReferenceId      *openapi_types.UUID       `json:"reference_id,omitempty"`
	RelationId       *openapi_types.UUID       `json:"relation_id,omitempty"`
	RequestReason    string                    `json:"request_reason"`
	RequestedAt      time.Time                 `json:"requested_at"`
	RequestedBy      string                    `json:"requested_by"`
	SiteId           *openapi_types.UUID       `json:"site_id,omitempty"`
	StartedAt        *time.Time                `json:"started_at,omitempty"`
	Status           OpEvaluationRunStatus     `json:"status"`
	SuiteVersion     string                    `json:"suite_version"`
	SupplierId       openapi_types.UUID        `json:"supplier_id"`
	SupplierName     *string                   `json:"supplier_name,omitempty"`
	TargetKind       OpEvaluationRunTargetKind `json:"target_kind"`
	UpstreamModel    string                    `json:"upstream_model"`
}

// OpEvaluationRunPurpose defines model for OpEvaluationRun.Purpose.
type OpEvaluationRunPurpose string

// OpEvaluationRunStatus defines model for OpEvaluationRun.Status.
type OpEvaluationRunStatus string

// OpEvaluationRunTargetKind defines model for OpEvaluationRun.TargetKind.
type OpEvaluationRunTargetKind string

// OpEvaluationRunInput defines model for OpEvaluationRunInput.
type OpEvaluationRunInput struct {
	Model      string                          `json:"model"`
	Purpose    OpEvaluationRunInputPurpose     `json:"purpose"`
	Reason     string                          `json:"reason"`
	SupplierId openapi_types.UUID              `json:"supplier_id"`
	TargetKind *OpEvaluationRunInputTargetKind `json:"target_kind,omitempty"`
}

// OpEvaluationRunInputPurpose defines model for OpEvaluationRunInput.Purpose.
type OpEvaluationRunInputPurpose string

// OpEvaluationRunInputTargetKind defines model for OpEvaluationRunInput.TargetKind.
type OpEvaluationRunInputTargetKind string

// OpEvaluationRunPage defines model for OpEvaluationRunPage.
type OpEvaluationRunPage struct {
	Items  []OpEvaluationRun `json:"items"`
	Limit  int               `json:"limit"`
	Offset int               `json:"offset"`
	Total  int64             `json:"total"`
}

// OpIssuedSiteProductToken defines model for OpIssuedSiteProductToken.
type OpIssuedSiteProductToken struct {
	CreatedAt  time.Time                      `json:"created_at"`
	CreatedBy  string                         `json:"created_by"`
	Id         openapi_types.UUID             `json:"id"`
	LastUsedAt *time.Time                     `json:"last_used_at,omitempty"`
	Reason     string                         `json:"reason"`
	RevokedAt  *time.Time                     `json:"revoked_at,omitempty"`
	SiteId     openapi_types.UUID             `json:"site_id"`
	Status     OpIssuedSiteProductTokenStatus `json:"status"`
	Token      *string                        `json:"token,omitempty"`
}

// OpIssuedSiteProductTokenStatus defines model for OpIssuedSiteProductToken.Status.
type OpIssuedSiteProductTokenStatus string

// OpLoginInput defines model for OpLoginInput.
type OpLoginInput struct {
	Password *string `json:"password,omitempty"`
	Username string  `json:"username"`
}

// OpModelInput defines model for OpModelInput.
type OpModelInput struct {
	Currency OpModelInputCurrency `json:"currency"`
	Enabled  bool                 `json:"enabled"`

	// InputPrice Nonnegative decimal with at most ten fractional digits
	InputPrice string `json:"input_price"`
	Model      string `json:"model"`

	// OutputPrice Nonnegative decimal with at most ten fractional digits
	OutputPrice   string `json:"output_price"`
	UpstreamModel string `json:"upstream_model"`
}

// OpModelInputCurrency defines model for OpModelInput.Currency.
type OpModelInputCurrency string

// OpPagination defines model for OpPagination.
type OpPagination struct {
	Limit  int   `json:"limit"`
	Offset int   `json:"offset"`
	Total  int64 `json:"total"`
}

// OpPlan defines model for OpPlan.
type OpPlan struct {
	ConfirmedAt      *time.Time              `json:"confirmed_at,omitempty"`
	ContentHash      string                  `json:"content_hash"`
	CreatedAt        time.Time               `json:"created_at"`
	Id               openapi_types.UUID      `json:"id"`
	PreviousPlanId   *openapi_types.UUID     `json:"previous_plan_id,omitempty"`
	PreviousSnapshot *map[string]interface{} `json:"previous_snapshot,omitempty"`
	Reason           string                  `json:"reason"`
	SiteId           openapi_types.UUID      `json:"site_id"`
	SiteSupplierId   openapi_types.UUID      `json:"site_supplier_id"`
	Snapshot         map[string]interface{}  `json:"snapshot"`
	Status           OpPlanStatus            `json:"status"`
	Version          int64                   `json:"version"`
}

// OpPlanStatus defines model for OpPlan.Status.
type OpPlanStatus string

// OpPlanPage defines model for OpPlanPage.
type OpPlanPage struct {
	Items  []OpPlan `json:"items"`
	Limit  int      `json:"limit"`
	Offset int      `json:"offset"`
	Total  int64    `json:"total"`
}

// OpPlanReference defines model for OpPlanReference.
type OpPlanReference struct {
	Id                   openapi_types.UUID     `json:"id"`
	SiteId               openapi_types.UUID     `json:"site_id"`
	Status               string                 `json:"status"`
	Version              int64                  `json:"version"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// OpPlanResult defines model for OpPlanResult.
type OpPlanResult struct {
	Plans []OpPlanReference `json:"plans"`
}

// OpPrice defines model for OpPrice.
type OpPrice struct {
	// AppliedAt Historical time when this price version first passed group-ratio and pricing-basis reconciliation; subsequent external changes or partial writes may require fresh confirmation.
	AppliedAt *time.Time `json:"applied_at,omitempty"`

	// BasisHash Digest of the observed pricing settings and New API version, used for configuration reconciliation.
	BasisHash string `json:"basis_hash"`

	// BillingBasis Pricing settings and New API version observed for this price; this historical evidence does not assert that an external administrator has left the live settings unchanged.
	BillingBasis map[string]interface{} `json:"billing_basis"`
	CreatedAt    time.Time              `json:"created_at"`
	GroupKey     string                 `json:"group_key"`
	Id           openapi_types.UUID     `json:"id"`

	// IsLastConfirmed True for the most recently confirmed version recorded for this site and group. A pending or partially applied newer plan can leave the current external price unknown.
	IsLastConfirmed bool                `json:"is_last_confirmed"`
	PublishedAt     *time.Time          `json:"published_at,omitempty"`
	Reason          string              `json:"reason"`
	RoutePlanId     *openapi_types.UUID `json:"route_plan_id,omitempty"`
	SaleRatio       string              `json:"sale_ratio"`
	SiteId          openapi_types.UUID  `json:"site_id"`
	Status          OpPriceStatus       `json:"status"`
	Version         int64               `json:"version"`
}

// OpPriceStatus defines model for OpPrice.Status.
type OpPriceStatus string

// OpPriceInput defines model for OpPriceInput.
type OpPriceInput struct {
	GroupKey string `json:"group_key"`
	Reason   string `json:"reason"`

	// SaleRatio Positive decimal up to 999999.999999
	SaleRatio string             `json:"sale_ratio"`
	SiteId    openapi_types.UUID `json:"site_id"`
}

// OpPricePage defines model for OpPricePage.
type OpPricePage struct {
	Items  []OpPrice `json:"items"`
	Limit  int       `json:"limit"`
	Offset int       `json:"offset"`
	Total  int64     `json:"total"`
}

// OpPublishInput defines model for OpPublishInput.
type OpPublishInput struct {
	Version int64 `json:"version"`
}

// OpReasonInput defines model for OpReasonInput.
type OpReasonInput struct {
	Reason string `json:"reason"`
}

// OpRelation defines model for OpRelation.
type OpRelation struct {
	CreatedAt            time.Time               `json:"created_at"`
	CredentialVersion    *int                    `json:"credential_version,omitempty"`
	CurrentPlanId        *openapi_types.UUID     `json:"current_plan_id,omitempty"`
	DesiredStatus        OpRelationDesiredStatus `json:"desired_status"`
	ExternalChannelId    *int64                  `json:"external_channel_id,omitempty"`
	GroupDisplayName     string                  `json:"group_display_name"`
	GroupKey             string                  `json:"group_key"`
	Id                   openapi_types.UUID      `json:"id"`
	LastConfirmedAt      *time.Time              `json:"last_confirmed_at,omitempty"`
	LastConfirmedEnabled *bool                   `json:"last_confirmed_enabled,omitempty"`
	SaleRatio            string                  `json:"sale_ratio"`
	SiteId               openapi_types.UUID      `json:"site_id"`
	SiteName             string                  `json:"site_name"`
	SupplierId           openapi_types.UUID      `json:"supplier_id"`
	SupplierName         string                  `json:"supplier_name"`
	SyncStatus           OpRelationSyncStatus    `json:"sync_status"`
	UpdatedAt            time.Time               `json:"updated_at"`
	Version              int64                   `json:"version"`

	// Visible Desired dedicated group entry access, including existing group-bound API keys. Inspect synchronization state for whether the access change has completed.
	Visible bool `json:"visible"`
}

// OpRelationDesiredStatus defines model for OpRelation.DesiredStatus.
type OpRelationDesiredStatus string

// OpRelationSyncStatus defines model for OpRelation.SyncStatus.
type OpRelationSyncStatus string

// OpRelationInput defines model for OpRelationInput.
type OpRelationInput struct {
	DesiredStatus    OpRelationInputDesiredStatus `json:"desired_status"`
	GroupDisplayName string                       `json:"group_display_name"`
	Reason           string                       `json:"reason"`

	// Resume Explicitly restore a stopped deployment
	Resume  bool  `json:"resume"`
	Version int64 `json:"version"`

	// Visible Desired dedicated entry access. False closes the entry and rejects subsequent requests from existing group-bound API keys after synchronization, while preserving the channel and participation in other open Auto groups.
	Visible bool `json:"visible"`
}

// OpRelationInputDesiredStatus defines model for OpRelationInput.DesiredStatus.
type OpRelationInputDesiredStatus string

// OpRelationPage defines model for OpRelationPage.
type OpRelationPage struct {
	Items  []OpRelation `json:"items"`
	Limit  int          `json:"limit"`
	Offset int          `json:"offset"`
	Total  int64        `json:"total"`
}

// OpRestoreInput defines model for OpRestoreInput.
type OpRestoreInput struct {
	Reason string `json:"reason"`
}

// OpScoreInsight defines model for OpScoreInsight.
type OpScoreInsight struct {
	ActiveSamples       int64                             `json:"active_samples"`
	AuthenticityVerdict OpScoreInsightAuthenticityVerdict `json:"authenticity_verdict"`
	Confidence          OpScoreInsightConfidence          `json:"confidence"`
	CreatedAt           time.Time                         `json:"created_at"`
	Eligibility         OpScoreInsightEligibility         `json:"eligibility"`
	Explanation         map[string]interface{}            `json:"explanation"`
	FactsThrough        *time.Time                        `json:"facts_through,omitempty"`
	HardReasons         []string                          `json:"hard_reasons"`
	LatencyScore        *float32                          `json:"latency_score,omitempty"`
	Model               string                            `json:"model"`
	PassiveSamples      int64                             `json:"passive_samples"`
	PolicyVersion       string                            `json:"policy_version"`
	PriceScore          *float32                          `json:"price_score,omitempty"`
	QualityScore        *float32                          `json:"quality_score,omitempty"`
	Recommendations     []OpShadowRecommendation          `json:"recommendations"`
	SiteId              openapi_types.UUID                `json:"site_id"`
	SlaScore            *float32                          `json:"sla_score,omitempty"`
	SnapshotId          openapi_types.UUID                `json:"snapshot_id"`
	SupplierId          openapi_types.UUID                `json:"supplier_id"`
	SupplierName        string                            `json:"supplier_name"`
	TotalScore          *float32                          `json:"total_score,omitempty"`
	WindowEnd           time.Time                         `json:"window_end"`
	WindowStart         time.Time                         `json:"window_start"`
}

// OpScoreInsightAuthenticityVerdict defines model for OpScoreInsight.AuthenticityVerdict.
type OpScoreInsightAuthenticityVerdict string

// OpScoreInsightConfidence defines model for OpScoreInsight.Confidence.
type OpScoreInsightConfidence string

// OpScoreInsightEligibility defines model for OpScoreInsight.Eligibility.
type OpScoreInsightEligibility string

// OpScoreInsightPage defines model for OpScoreInsightPage.
type OpScoreInsightPage struct {
	Items  []OpScoreInsight `json:"items"`
	Limit  int              `json:"limit"`
	Offset int              `json:"offset"`
	Total  int64            `json:"total"`
}

// OpSetupInput defines model for OpSetupInput.
type OpSetupInput struct {
	Password   *string `json:"password,omitempty"`
	SetupToken *string `json:"setup_token,omitempty"`
	Username   string  `json:"username"`
}

// OpShadowRecommendation defines model for OpShadowRecommendation.
type OpShadowRecommendation struct {
	Action        OpShadowRecommendationAction       `json:"action"`
	Confidence    OpShadowRecommendationConfidence   `json:"confidence"`
	CurrentMember bool                               `json:"current_member"`
	Reasons       []string                           `json:"reasons"`
	Score         *float32                           `json:"score,omitempty"`
	StrategyKind  OpShadowRecommendationStrategyKind `json:"strategy_kind"`
}

// OpShadowRecommendationAction defines model for OpShadowRecommendation.Action.
type OpShadowRecommendationAction string

// OpShadowRecommendationConfidence defines model for OpShadowRecommendation.Confidence.
type OpShadowRecommendationConfidence string

// OpShadowRecommendationStrategyKind defines model for OpShadowRecommendation.StrategyKind.
type OpShadowRecommendationStrategyKind string

// OpSite defines model for OpSite.
type OpSite struct {
	AdminUserId         int64                     `json:"admin_user_id"`
	Code                string                    `json:"code"`
	CompatibilityStatus OpSiteCompatibilityStatus `json:"compatibility_status"`
	CreatedAt           time.Time                 `json:"created_at"`
	Id                  openapi_types.UUID        `json:"id"`
	Name                string                    `json:"name"`
	NewApiBaseUrl       string                    `json:"new_api_base_url"`
	Status              OpSiteStatus              `json:"status"`
	UpdatedAt           time.Time                 `json:"updated_at"`
	Version             int64                     `json:"version"`
}

// OpSiteCompatibilityStatus defines model for OpSite.CompatibilityStatus.
type OpSiteCompatibilityStatus string

// OpSiteStatus defines model for OpSite.Status.
type OpSiteStatus string

// OpSitePage defines model for OpSitePage.
type OpSitePage struct {
	Items  []OpSite `json:"items"`
	Limit  int      `json:"limit"`
	Offset int      `json:"offset"`
	Total  int64    `json:"total"`
}

// OpSiteProductToken defines model for OpSiteProductToken.
type OpSiteProductToken struct {
	CreatedAt  time.Time                `json:"created_at"`
	CreatedBy  string                   `json:"created_by"`
	Id         openapi_types.UUID       `json:"id"`
	LastUsedAt *time.Time               `json:"last_used_at,omitempty"`
	Reason     string                   `json:"reason"`
	RevokedAt  *time.Time               `json:"revoked_at,omitempty"`
	SiteId     openapi_types.UUID       `json:"site_id"`
	Status     OpSiteProductTokenStatus `json:"status"`
}

// OpSiteProductTokenStatus defines model for OpSiteProductToken.Status.
type OpSiteProductTokenStatus string

// OpSiteProductTokenList defines model for OpSiteProductTokenList.
type OpSiteProductTokenList struct {
	Items []OpSiteProductToken `json:"items"`
}

// OpStrategy defines model for OpStrategy.
type OpStrategy struct {
	CreatedAt         time.Time            `json:"created_at"`
	DisplayName       string               `json:"display_name"`
	Enabled           bool                 `json:"enabled"`
	GroupKey          string               `json:"group_key"`
	Id                openapi_types.UUID   `json:"id"`
	Kind              OpStrategyKind       `json:"kind"`
	MemberRelationIds []openapi_types.UUID `json:"member_relation_ids"`
	SaleRatio         *string              `json:"sale_ratio,omitempty"`
	SiteId            openapi_types.UUID   `json:"site_id"`
	UpdatedAt         time.Time            `json:"updated_at"`
	Version           int64                `json:"version"`

	// Visible Desired Auto group entry access, including existing group-bound API keys. Effective opening also requires an enabled strategy and eligible members.
	Visible bool `json:"visible"`
}

// OpStrategyInput defines model for OpStrategyInput.
type OpStrategyInput struct {
	DisplayName       string               `json:"display_name"`
	Enabled           bool                 `json:"enabled"`
	MemberRelationIds []openapi_types.UUID `json:"member_relation_ids"`
	Reason            string               `json:"reason"`

	// Version Zero when creating a site strategy
	Version int64 `json:"version"`

	// Visible Desired Auto entry access. False closes the entry and rejects subsequent requests from existing API keys bound to this Auto group after synchronization. Opening also requires an enabled strategy with eligible members.
	Visible bool `json:"visible"`
}

// OpStrategyKind defines model for OpStrategyKind.
type OpStrategyKind string

// OpStrategyPage defines model for OpStrategyPage.
type OpStrategyPage struct {
	Items  []OpStrategy `json:"items"`
	Limit  int          `json:"limit"`
	Offset int          `json:"offset"`
	Total  int64        `json:"total"`
}

// OpSupplier defines model for OpSupplier.
type OpSupplier struct {
	Code                     string             `json:"code"`
	CreatedAt                time.Time          `json:"created_at"`
	CredentialVersion        int                `json:"credential_version"`
	Id                       openapi_types.UUID `json:"id"`
	Models                   []OpModelInput     `json:"models"`
	Name                     string             `json:"name"`
	PendingCredentialVersion *int               `json:"pending_credential_version,omitempty"`
	Protocol                 OpSupplierProtocol `json:"protocol"`
	Status                   OpSupplierStatus   `json:"status"`
	UpdatedAt                time.Time          `json:"updated_at"`
	UpstreamBaseUrl          string             `json:"upstream_base_url"`
	Version                  int64              `json:"version"`
}

// OpSupplierProtocol defines model for OpSupplier.Protocol.
type OpSupplierProtocol string

// OpSupplierStatus defines model for OpSupplier.Status.
type OpSupplierStatus string

// OpSupplierPage defines model for OpSupplierPage.
type OpSupplierPage struct {
	Items  []OpSupplier `json:"items"`
	Limit  int          `json:"limit"`
	Offset int          `json:"offset"`
	Total  int64        `json:"total"`
}

// OpSyncOperation defines model for OpSyncOperation.
type OpSyncOperation struct {
	Attempt          int                   `json:"attempt"`
	CompletedAt      *time.Time            `json:"completed_at,omitempty"`
	CreatedAt        time.Time             `json:"created_at"`
	CurrentStep      *string               `json:"current_step,omitempty"`
	Id               openapi_types.UUID    `json:"id"`
	LastErrorCode    *string               `json:"last_error_code,omitempty"`
	LastErrorMessage *string               `json:"last_error_message,omitempty"`
	NextAttemptAt    *time.Time            `json:"next_attempt_at,omitempty"`
	RoutePlanId      openapi_types.UUID    `json:"route_plan_id"`
	SiteId           openapi_types.UUID    `json:"site_id"`
	SiteSupplierId   openapi_types.UUID    `json:"site_supplier_id"`
	Status           OpSyncOperationStatus `json:"status"`
	Steps            []OpSyncStep          `json:"steps"`
	UpdatedAt        time.Time             `json:"updated_at"`
}

// OpSyncOperationStatus defines model for OpSyncOperation.Status.
type OpSyncOperationStatus string

// OpSyncOperationPage defines model for OpSyncOperationPage.
type OpSyncOperationPage struct {
	Items  []OpSyncOperation `json:"items"`
	Limit  int               `json:"limit"`
	Offset int               `json:"offset"`
	Total  int64             `json:"total"`
}

// OpSyncStep defines model for OpSyncStep.
type OpSyncStep struct {
	AfterSummary  *map[string]interface{} `json:"after_summary,omitempty"`
	BeforeSummary *map[string]interface{} `json:"before_summary,omitempty"`
	ErrorCode     *string                 `json:"error_code,omitempty"`
	ErrorMessage  *string                 `json:"error_message,omitempty"`
	FinishedAt    *time.Time              `json:"finished_at,omitempty"`
	OperationId   openapi_types.UUID      `json:"operation_id"`
	StartedAt     *time.Time              `json:"started_at,omitempty"`
	Status        OpSyncStepStatus        `json:"status"`
	StepKey       string                  `json:"step_key"`
}

// OpSyncStepStatus defines model for OpSyncStep.Status.
type OpSyncStepStatus string

// OpTrustedReference defines model for OpTrustedReference.
type OpTrustedReference struct {
	ExpiresAt  time.Time               `json:"expires_at"`
	Id         openapi_types.UUID      `json:"id"`
	Model      string                  `json:"model"`
	SupplierId openapi_types.UUID      `json:"supplier_id"`
	Trust      OpTrustedReferenceTrust `json:"trust"`
}

// OpTrustedReferenceTrust defines model for OpTrustedReference.Trust.
type OpTrustedReferenceTrust string

// OpTrustedReferenceInput defines model for OpTrustedReferenceInput.
type OpTrustedReferenceInput struct {
	Reason    string                       `json:"reason"`
	Trust     OpTrustedReferenceInputTrust `json:"trust"`
	ValidDays int                          `json:"valid_days"`
}

// OpTrustedReferenceInputTrust defines model for OpTrustedReferenceInput.Trust.
type OpTrustedReferenceInputTrust string

// OpUpdateSiteInput defines model for OpUpdateSiteInput.
type OpUpdateSiteInput struct {
	AdminUserId       *int64                  `json:"admin_user_id,omitempty"`
	Code              *string                 `json:"code,omitempty"`
	Name              string                  `json:"name"`
	NewApiAccessToken *string                 `json:"new_api_access_token,omitempty"`
	NewApiBaseUrl     string                  `json:"new_api_base_url"`
	Reason            string                  `json:"reason"`
	Status            OpUpdateSiteInputStatus `json:"status"`
	Version           int64                   `json:"version"`
}

// OpUpdateSiteInputStatus defines model for OpUpdateSiteInput.Status.
type OpUpdateSiteInputStatus string

// OpUpdateSupplierInput defines model for OpUpdateSupplierInput.
type OpUpdateSupplierInput struct {
	Code            *string                     `json:"code,omitempty"`
	Models          []OpModelInput              `json:"models"`
	Name            string                      `json:"name"`
	Reason          string                      `json:"reason"`
	Status          OpUpdateSupplierInputStatus `json:"status"`
	UpstreamApiKey  *string                     `json:"upstream_api_key,omitempty"`
	UpstreamBaseUrl string                      `json:"upstream_base_url"`
	Version         int64                       `json:"version"`
}

// OpUpdateSupplierInputStatus defines model for OpUpdateSupplierInput.Status.
type OpUpdateSupplierInputStatus string

// OpID defines model for OpID.
type OpID = openapi_types.UUID

// OpIdempotencyKey defines model for OpIdempotencyKey.
type OpIdempotencyKey = string

// OpLimit defines model for OpLimit.
type OpLimit = int

// OpOffset defines model for OpOffset.
type OpOffset = int

// OpQuery defines model for OpQuery.
type OpQuery = string

// OpSiteFilter defines model for OpSiteFilter.
type OpSiteFilter = openapi_types.UUID

// OpSupplierFilter defines model for OpSupplierFilter.
type OpSupplierFilter = openapi_types.UUID

// OpPlans defines model for OpPlans.
type OpPlans = OpPlanResult

// OpListAuditParams defines parameters for OpListAudit.
type OpListAuditParams struct {
	Q          *OpQuery          `form:"q,omitempty" json:"q,omitempty"`
	SiteId     *OpSiteFilter     `form:"site_id,omitempty" json:"site_id,omitempty"`
	SupplierId *OpSupplierFilter `form:"supplier_id,omitempty" json:"supplier_id,omitempty"`
	Limit      *OpLimit          `form:"limit,omitempty" json:"limit,omitempty"`
	Offset     *OpOffset         `form:"offset,omitempty" json:"offset,omitempty"`
}

// OpListAutomationRunsParams defines parameters for OpListAutomationRuns.
type OpListAutomationRunsParams struct {
	SiteId *OpSiteFilter `form:"site_id,omitempty" json:"site_id,omitempty"`
	Limit  *OpLimit      `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *OpOffset     `form:"offset,omitempty" json:"offset,omitempty"`
}

// OpRunAutomationParams defines parameters for OpRunAutomation.
type OpRunAutomationParams struct {
	IdempotencyKey OpIdempotencyKey `json:"Idempotency-Key"`
}

// OpListAutomationSettingsParams defines parameters for OpListAutomationSettings.
type OpListAutomationSettingsParams struct {
	SiteId *OpSiteFilter `form:"site_id,omitempty" json:"site_id,omitempty"`
}

// OpRunCollectionParams defines parameters for OpRunCollection.
type OpRunCollectionParams struct {
	IdempotencyKey OpIdempotencyKey `json:"Idempotency-Key"`
}

// OpListCollectionStatusParams defines parameters for OpListCollectionStatus.
type OpListCollectionStatusParams struct {
	SiteId *OpSiteFilter `form:"site_id,omitempty" json:"site_id,omitempty"`
}

// OpDeploySupplierParams defines parameters for OpDeploySupplier.
type OpDeploySupplierParams struct {
	IdempotencyKey OpIdempotencyKey `json:"Idempotency-Key"`
}

// OpListEvaluationRunsParams defines parameters for OpListEvaluationRuns.
type OpListEvaluationRunsParams struct {
	SiteId     *OpSiteFilter                      `form:"site_id,omitempty" json:"site_id,omitempty"`
	SupplierId *OpSupplierFilter                  `form:"supplier_id,omitempty" json:"supplier_id,omitempty"`
	Model      *string                            `form:"model,omitempty" json:"model,omitempty"`
	Purpose    *OpListEvaluationRunsParamsPurpose `form:"purpose,omitempty" json:"purpose,omitempty"`
	Limit      *OpLimit                           `form:"limit,omitempty" json:"limit,omitempty"`
	Offset     *OpOffset                          `form:"offset,omitempty" json:"offset,omitempty"`
}

// OpListEvaluationRunsParamsPurpose defines parameters for OpListEvaluationRuns.
type OpListEvaluationRunsParamsPurpose string

// OpRequestEvaluationRunParams defines parameters for OpRequestEvaluationRun.
type OpRequestEvaluationRunParams struct {
	IdempotencyKey OpIdempotencyKey `json:"Idempotency-Key"`
}

// OpPromoteEvaluationReferenceParams defines parameters for OpPromoteEvaluationReference.
type OpPromoteEvaluationReferenceParams struct {
	IdempotencyKey OpIdempotencyKey `json:"Idempotency-Key"`
}

// OpListPlansParams defines parameters for OpListPlans.
type OpListPlansParams struct {
	Q          *OpQuery          `form:"q,omitempty" json:"q,omitempty"`
	SiteId     *OpSiteFilter     `form:"site_id,omitempty" json:"site_id,omitempty"`
	SupplierId *OpSupplierFilter `form:"supplier_id,omitempty" json:"supplier_id,omitempty"`
	Limit      *OpLimit          `form:"limit,omitempty" json:"limit,omitempty"`
	Offset     *OpOffset         `form:"offset,omitempty" json:"offset,omitempty"`
}

// OpRestorePlanParams defines parameters for OpRestorePlan.
type OpRestorePlanParams struct {
	IdempotencyKey OpIdempotencyKey `json:"Idempotency-Key"`
}

// OpListPricesParams defines parameters for OpListPrices.
type OpListPricesParams struct {
	Q          *OpQuery          `form:"q,omitempty" json:"q,omitempty"`
	SiteId     *OpSiteFilter     `form:"site_id,omitempty" json:"site_id,omitempty"`
	SupplierId *OpSupplierFilter `form:"supplier_id,omitempty" json:"supplier_id,omitempty"`
	Limit      *OpLimit          `form:"limit,omitempty" json:"limit,omitempty"`
	Offset     *OpOffset         `form:"offset,omitempty" json:"offset,omitempty"`
}

// OpDraftPriceParams defines parameters for OpDraftPrice.
type OpDraftPriceParams struct {
	IdempotencyKey OpIdempotencyKey `json:"Idempotency-Key"`
}

// OpPublishPriceParams defines parameters for OpPublishPrice.
type OpPublishPriceParams struct {
	IdempotencyKey OpIdempotencyKey `json:"Idempotency-Key"`
}

// OpListRelationsParams defines parameters for OpListRelations.
type OpListRelationsParams struct {
	Q          *OpQuery          `form:"q,omitempty" json:"q,omitempty"`
	SiteId     *OpSiteFilter     `form:"site_id,omitempty" json:"site_id,omitempty"`
	SupplierId *OpSupplierFilter `form:"supplier_id,omitempty" json:"supplier_id,omitempty"`
	Limit      *OpLimit          `form:"limit,omitempty" json:"limit,omitempty"`
	Offset     *OpOffset         `form:"offset,omitempty" json:"offset,omitempty"`
}

// OpUpdateRelationParams defines parameters for OpUpdateRelation.
type OpUpdateRelationParams struct {
	IdempotencyKey OpIdempotencyKey `json:"Idempotency-Key"`
}

// OpListScoreInsightsParams defines parameters for OpListScoreInsights.
type OpListScoreInsightsParams struct {
	SiteId     *OpSiteFilter     `form:"site_id,omitempty" json:"site_id,omitempty"`
	SupplierId *OpSupplierFilter `form:"supplier_id,omitempty" json:"supplier_id,omitempty"`
	Model      *string           `form:"model,omitempty" json:"model,omitempty"`
	Limit      *OpLimit          `form:"limit,omitempty" json:"limit,omitempty"`
	Offset     *OpOffset         `form:"offset,omitempty" json:"offset,omitempty"`
}

// OpRefreshScoresJSONBody defines parameters for OpRefreshScores.
type OpRefreshScoresJSONBody = map[string]interface{}

// OpRefreshScoresParams defines parameters for OpRefreshScores.
type OpRefreshScoresParams struct {
	IdempotencyKey OpIdempotencyKey `json:"Idempotency-Key"`
}

// OpRefreshScores200JSONResponseBodyStatus defines parameters for OpRefreshScores.
type OpRefreshScores200JSONResponseBodyStatus string

// OpListSiteProductTokensParams defines parameters for OpListSiteProductTokens.
type OpListSiteProductTokensParams struct {
	SiteId *OpSiteFilter `form:"site_id,omitempty" json:"site_id,omitempty"`
}

// OpListSitesParams defines parameters for OpListSites.
type OpListSitesParams struct {
	Q          *OpQuery          `form:"q,omitempty" json:"q,omitempty"`
	SiteId     *OpSiteFilter     `form:"site_id,omitempty" json:"site_id,omitempty"`
	SupplierId *OpSupplierFilter `form:"supplier_id,omitempty" json:"supplier_id,omitempty"`
	Limit      *OpLimit          `form:"limit,omitempty" json:"limit,omitempty"`
	Offset     *OpOffset         `form:"offset,omitempty" json:"offset,omitempty"`
}

// OpCreateSiteParams defines parameters for OpCreateSite.
type OpCreateSiteParams struct {
	IdempotencyKey OpIdempotencyKey `json:"Idempotency-Key"`
}

// OpUpdateSiteParams defines parameters for OpUpdateSite.
type OpUpdateSiteParams struct {
	IdempotencyKey OpIdempotencyKey `json:"Idempotency-Key"`
}

// OpUpdateAutomationSettingParams defines parameters for OpUpdateAutomationSetting.
type OpUpdateAutomationSettingParams struct {
	IdempotencyKey OpIdempotencyKey `json:"Idempotency-Key"`
}

// OpCreateSiteProductTokenParams defines parameters for OpCreateSiteProductToken.
type OpCreateSiteProductTokenParams struct {
	IdempotencyKey OpIdempotencyKey `json:"Idempotency-Key"`
}

// OpRevokeSiteProductTokenParams defines parameters for OpRevokeSiteProductToken.
type OpRevokeSiteProductTokenParams struct {
	IdempotencyKey OpIdempotencyKey `json:"Idempotency-Key"`
}

// OpRevokeSiteProductToken200JSONResponseBodyStatus defines parameters for OpRevokeSiteProductToken.
type OpRevokeSiteProductToken200JSONResponseBodyStatus string

// OpSaveStrategyParams defines parameters for OpSaveStrategy.
type OpSaveStrategyParams struct {
	IdempotencyKey OpIdempotencyKey `json:"Idempotency-Key"`
}

// OpSyncSiteJSONBody defines parameters for OpSyncSite.
type OpSyncSiteJSONBody = map[string]interface{}

// OpSyncSiteParams defines parameters for OpSyncSite.
type OpSyncSiteParams struct {
	IdempotencyKey OpIdempotencyKey `json:"Idempotency-Key"`
}

// OpListStrategiesParams defines parameters for OpListStrategies.
type OpListStrategiesParams struct {
	Q          *OpQuery          `form:"q,omitempty" json:"q,omitempty"`
	SiteId     *OpSiteFilter     `form:"site_id,omitempty" json:"site_id,omitempty"`
	SupplierId *OpSupplierFilter `form:"supplier_id,omitempty" json:"supplier_id,omitempty"`
	Limit      *OpLimit          `form:"limit,omitempty" json:"limit,omitempty"`
	Offset     *OpOffset         `form:"offset,omitempty" json:"offset,omitempty"`
}

// OpListSuppliersParams defines parameters for OpListSuppliers.
type OpListSuppliersParams struct {
	Q          *OpQuery          `form:"q,omitempty" json:"q,omitempty"`
	SiteId     *OpSiteFilter     `form:"site_id,omitempty" json:"site_id,omitempty"`
	SupplierId *OpSupplierFilter `form:"supplier_id,omitempty" json:"supplier_id,omitempty"`
	Limit      *OpLimit          `form:"limit,omitempty" json:"limit,omitempty"`
	Offset     *OpOffset         `form:"offset,omitempty" json:"offset,omitempty"`
}

// OpCreateSupplierParams defines parameters for OpCreateSupplier.
type OpCreateSupplierParams struct {
	IdempotencyKey OpIdempotencyKey `json:"Idempotency-Key"`
}

// OpUpdateSupplierParams defines parameters for OpUpdateSupplier.
type OpUpdateSupplierParams struct {
	IdempotencyKey OpIdempotencyKey `json:"Idempotency-Key"`
}

// OpRotateCredentialParams defines parameters for OpRotateCredential.
type OpRotateCredentialParams struct {
	IdempotencyKey OpIdempotencyKey `json:"Idempotency-Key"`
}

// OpCancelCredentialParams defines parameters for OpCancelCredential.
type OpCancelCredentialParams struct {
	IdempotencyKey OpIdempotencyKey `json:"Idempotency-Key"`
}

// OpListSyncOperationsParams defines parameters for OpListSyncOperations.
type OpListSyncOperationsParams struct {
	Q          *OpQuery          `form:"q,omitempty" json:"q,omitempty"`
	SiteId     *OpSiteFilter     `form:"site_id,omitempty" json:"site_id,omitempty"`
	SupplierId *OpSupplierFilter `form:"supplier_id,omitempty" json:"supplier_id,omitempty"`
	Limit      *OpLimit          `form:"limit,omitempty" json:"limit,omitempty"`
	Offset     *OpOffset         `form:"offset,omitempty" json:"offset,omitempty"`
}

// OpAuthLoginJSONRequestBody defines body for OpAuthLogin for application/json ContentType.
type OpAuthLoginJSONRequestBody = OpLoginInput

// OpAuthSetupJSONRequestBody defines body for OpAuthSetup for application/json ContentType.
type OpAuthSetupJSONRequestBody = OpSetupInput

// OpRunAutomationJSONRequestBody defines body for OpRunAutomation for application/json ContentType.
type OpRunAutomationJSONRequestBody = OpAutomationRunInput

// OpRunCollectionJSONRequestBody defines body for OpRunCollection for application/json ContentType.
type OpRunCollectionJSONRequestBody = OpCollectionRunInput

// OpDeploySupplierJSONRequestBody defines body for OpDeploySupplier for application/json ContentType.
type OpDeploySupplierJSONRequestBody = OpDeploymentInput

// OpRequestEvaluationRunJSONRequestBody defines body for OpRequestEvaluationRun for application/json ContentType.
type OpRequestEvaluationRunJSONRequestBody = OpEvaluationRunInput

// OpPromoteEvaluationReferenceJSONRequestBody defines body for OpPromoteEvaluationReference for application/json ContentType.
type OpPromoteEvaluationReferenceJSONRequestBody = OpTrustedReferenceInput

// OpRestorePlanJSONRequestBody defines body for OpRestorePlan for application/json ContentType.
type OpRestorePlanJSONRequestBody = OpRestoreInput

// OpDraftPriceJSONRequestBody defines body for OpDraftPrice for application/json ContentType.
type OpDraftPriceJSONRequestBody = OpPriceInput

// OpPublishPriceJSONRequestBody defines body for OpPublishPrice for application/json ContentType.
type OpPublishPriceJSONRequestBody = OpPublishInput

// OpUpdateRelationJSONRequestBody defines body for OpUpdateRelation for application/json ContentType.
type OpUpdateRelationJSONRequestBody = OpRelationInput

// OpRefreshScoresJSONRequestBody defines body for OpRefreshScores for application/json ContentType.
type OpRefreshScoresJSONRequestBody = OpRefreshScoresJSONBody

// OpCreateSiteJSONRequestBody defines body for OpCreateSite for application/json ContentType.
type OpCreateSiteJSONRequestBody = OpCreateSiteInput

// OpUpdateSiteJSONRequestBody defines body for OpUpdateSite for application/json ContentType.
type OpUpdateSiteJSONRequestBody = OpUpdateSiteInput

// OpUpdateAutomationSettingJSONRequestBody defines body for OpUpdateAutomationSetting for application/json ContentType.
type OpUpdateAutomationSettingJSONRequestBody = OpAutomationSettingInput

// OpCreateSiteProductTokenJSONRequestBody defines body for OpCreateSiteProductToken for application/json ContentType.
type OpCreateSiteProductTokenJSONRequestBody = OpReasonInput

// OpRevokeSiteProductTokenJSONRequestBody defines body for OpRevokeSiteProductToken for application/json ContentType.
type OpRevokeSiteProductTokenJSONRequestBody = OpReasonInput

// OpSaveStrategyJSONRequestBody defines body for OpSaveStrategy for application/json ContentType.
type OpSaveStrategyJSONRequestBody = OpStrategyInput

// OpSyncSiteJSONRequestBody defines body for OpSyncSite for application/json ContentType.
type OpSyncSiteJSONRequestBody = OpSyncSiteJSONBody

// OpCreateSupplierJSONRequestBody defines body for OpCreateSupplier for application/json ContentType.
type OpCreateSupplierJSONRequestBody = OpCreateSupplierInput

// OpUpdateSupplierJSONRequestBody defines body for OpUpdateSupplier for application/json ContentType.
type OpUpdateSupplierJSONRequestBody = OpUpdateSupplierInput

// OpRotateCredentialJSONRequestBody defines body for OpRotateCredential for application/json ContentType.
type OpRotateCredentialJSONRequestBody = OpCredentialInput

// OpCancelCredentialJSONRequestBody defines body for OpCancelCredential for application/json ContentType.
type OpCancelCredentialJSONRequestBody = OpCredentialCancelInput

// Getter for additional properties for OpPlanReference. Returns the specified
// element and whether it was found
func (a OpPlanReference) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for OpPlanReference
func (a *OpPlanReference) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for OpPlanReference to handle AdditionalProperties
func (a *OpPlanReference) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &a.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
		delete(object, "id")
	}

	if raw, found := object["site_id"]; found {
		err = json.Unmarshal(raw, &a.SiteId)
		if err != nil {
			return fmt.Errorf("error reading 'site_id': %w", err)
		}
		delete(object, "site_id")
	}

	if raw, found := object["status"]; found {
		err = json.Unmarshal(raw, &a.Status)
		if err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		delete(object, "status")
	}

	if raw, found := object["version"]; found {
		err = json.Unmarshal(raw, &a.Version)
		if err != nil {
			return fmt.Errorf("error reading 'version': %w", err)
		}
		delete(object, "version")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for OpPlanReference to handle AdditionalProperties
func (a OpPlanReference) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["id"], err = json.Marshal(a.Id)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'id': %w", err)
	}

	object["site_id"], err = json.Marshal(a.SiteId)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'site_id': %w", err)
	}

	object["status"], err = json.Marshal(a.Status)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'status': %w", err)
	}

	object["version"], err = json.Marshal(a.Version)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'version': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
