// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const authInitialized = `-- name: AuthInitialized :one
SELECT EXISTS(SELECT 1 FROM operators)
`

func (q *Queries) AuthInitialized(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, authInitialized)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const consumeAuthAttempt = `-- name: ConsumeAuthAttempt :one
INSERT INTO auth_login_attempts (key, attempts, window_start)
VALUES ($1, 1, $2)
ON CONFLICT (key) DO UPDATE
SET attempts = CASE
        WHEN auth_login_attempts.window_start <= $3::timestamptz THEN 1
        ELSE LEAST(auth_login_attempts.attempts + 1, 1000)
    END,
    window_start = CASE
        WHEN auth_login_attempts.window_start <= $3::timestamptz THEN $2::timestamptz
        ELSE auth_login_attempts.window_start
    END
RETURNING attempts
`

type ConsumeAuthAttemptParams struct {
	Key    string             `json:"key"`
	NowAt  pgtype.Timestamptz `json:"now_at"`
	Cutoff pgtype.Timestamptz `json:"cutoff"`
}

func (q *Queries) ConsumeAuthAttempt(ctx context.Context, arg ConsumeAuthAttemptParams) (int32, error) {
	row := q.db.QueryRow(ctx, consumeAuthAttempt, arg.Key, arg.NowAt, arg.Cutoff)
	var attempts int32
	err := row.Scan(&attempts)
	return attempts, err
}

const createInitialOperator = `-- name: CreateInitialOperator :exec
INSERT INTO operators (id, username, password_hash, role, enabled, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateInitialOperatorParams struct {
	ID           uuid.UUID          `json:"id"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	Enabled      bool               `json:"enabled"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateInitialOperator(ctx context.Context, arg CreateInitialOperatorParams) error {
	_, err := q.db.Exec(ctx, createInitialOperator,
		arg.ID,
		arg.Username,
		arg.PasswordHash,
		arg.Role,
		arg.Enabled,
		arg.CreatedAt,
	)
	return err
}

const deleteOperatorSession = `-- name: DeleteOperatorSession :exec
WITH deleted AS (
    DELETE FROM operator_sessions WHERE token_hash = $3
    RETURNING operator_id
)
INSERT INTO audit_events (
    id, actor_type, actor_id, object_type, object_id, action, reason, result, created_at
)
SELECT $1, 'operator', operator_id::text, 'operator', operator_id::text,
       'operator.logout', 'operator logout', 'succeeded', $2
FROM deleted
`

type DeleteOperatorSessionParams struct {
	ID        uuid.UUID          `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	TokenHash string             `json:"token_hash"`
}

func (q *Queries) DeleteOperatorSession(ctx context.Context, arg DeleteOperatorSessionParams) error {
	_, err := q.db.Exec(ctx, deleteOperatorSession, arg.ID, arg.CreatedAt, arg.TokenHash)
	return err
}

const findOperator = `-- name: FindOperator :one
SELECT id, username, password_hash, role, enabled, created_at FROM operators WHERE username = $1
`

func (q *Queries) FindOperator(ctx context.Context, username string) (Operator, error) {
	row := q.db.QueryRow(ctx, findOperator, username)
	var i Operator
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const findOperatorSession = `-- name: FindOperatorSession :one
SELECT s.token_hash, s.csrf_hash, s.expires_at, s.created_at,
       o.id, o.username, o.role, o.enabled
FROM operator_sessions s
JOIN operators o ON o.id = s.operator_id
WHERE s.token_hash = $1
`

type FindOperatorSessionRow struct {
	TokenHash string             `json:"token_hash"`
	CsrfHash  string             `json:"csrf_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ID        uuid.UUID          `json:"id"`
	Username  string             `json:"username"`
	Role      string             `json:"role"`
	Enabled   bool               `json:"enabled"`
}

func (q *Queries) FindOperatorSession(ctx context.Context, tokenHash string) (FindOperatorSessionRow, error) {
	row := q.db.QueryRow(ctx, findOperatorSession, tokenHash)
	var i FindOperatorSessionRow
	err := row.Scan(
		&i.TokenHash,
		&i.CsrfHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.ID,
		&i.Username,
		&i.Role,
		&i.Enabled,
	)
	return i, err
}

const lockOperatorSetup = `-- name: LockOperatorSetup :exec
SELECT pg_advisory_xact_lock(7192210801)
`

func (q *Queries) LockOperatorSetup(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockOperatorSetup)
	return err
}

const saveOperatorSession = `-- name: SaveOperatorSession :exec
INSERT INTO operator_sessions (token_hash, operator_id, csrf_hash, expires_at, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type SaveOperatorSessionParams struct {
	TokenHash  string             `json:"token_hash"`
	OperatorID uuid.UUID          `json:"operator_id"`
	CsrfHash   string             `json:"csrf_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) SaveOperatorSession(ctx context.Context, arg SaveOperatorSessionParams) error {
	_, err := q.db.Exec(ctx, saveOperatorSession,
		arg.TokenHash,
		arg.OperatorID,
		arg.CsrfHash,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}
