// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: credentials.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCredential = `-- name: CreateCredential :one
INSERT INTO credentials (
    id, purpose, ciphertext, nonce, key_version, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, purpose, ciphertext, nonce, key_version, created_at, revoked_at
`

type CreateCredentialParams struct {
	ID         uuid.UUID          `json:"id"`
	Purpose    string             `json:"purpose"`
	Ciphertext []byte             `json:"ciphertext"`
	Nonce      []byte             `json:"nonce"`
	KeyVersion int32              `json:"key_version"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) (Credential, error) {
	row := q.db.QueryRow(ctx, createCredential,
		arg.ID,
		arg.Purpose,
		arg.Ciphertext,
		arg.Nonce,
		arg.KeyVersion,
		arg.CreatedAt,
	)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.Purpose,
		&i.Ciphertext,
		&i.Nonce,
		&i.KeyVersion,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getCredential = `-- name: GetCredential :one
SELECT id, purpose, ciphertext, nonce, key_version, created_at, revoked_at
FROM credentials
WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) GetCredential(ctx context.Context, id uuid.UUID) (Credential, error) {
	row := q.db.QueryRow(ctx, getCredential, id)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.Purpose,
		&i.Ciphertext,
		&i.Nonce,
		&i.KeyVersion,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}
