// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: measurement.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const ensureCollectionCursor = `-- name: EnsureCollectionCursor :exec
INSERT INTO collection_cursors (site_id)
VALUES ($1)
ON CONFLICT (site_id) DO NOTHING
`

func (q *Queries) EnsureCollectionCursor(ctx context.Context, siteID uuid.UUID) error {
	_, err := q.db.Exec(ctx, ensureCollectionCursor, siteID)
	return err
}

const getCollectionCursor = `-- name: GetCollectionCursor :one
SELECT site_id, source_kind, contract_version, committed_created_at, committed_source_id, scanned_through_at, overlap_seconds, source_latest_created_at, last_read_at, last_success_at, last_error_at, last_error_code, last_error_message, consecutive_failures, data_gap, updated_at
FROM collection_cursors
WHERE site_id = $1
`

func (q *Queries) GetCollectionCursor(ctx context.Context, siteID uuid.UUID) (CollectionCursor, error) {
	row := q.db.QueryRow(ctx, getCollectionCursor, siteID)
	var i CollectionCursor
	err := row.Scan(
		&i.SiteID,
		&i.SourceKind,
		&i.ContractVersion,
		&i.CommittedCreatedAt,
		&i.CommittedSourceID,
		&i.ScannedThroughAt,
		&i.OverlapSeconds,
		&i.SourceLatestCreatedAt,
		&i.LastReadAt,
		&i.LastSuccessAt,
		&i.LastErrorAt,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.ConsecutiveFailures,
		&i.DataGap,
		&i.UpdatedAt,
	)
	return i, err
}

const getCollectionSite = `-- name: GetCollectionSite :one
SELECT
    s.id AS site_id,
    s.code AS site_code,
    s.name AS site_name,
    s.new_api_base_url,
    s.admin_user_id,
    c.id AS credential_id,
    c.purpose AS credential_purpose,
    c.ciphertext,
    c.nonce,
    c.key_version
FROM sites s
JOIN credentials c ON c.id = s.admin_credential_id
WHERE s.id = $1
  AND s.status = 'enabled'
  AND c.revoked_at IS NULL
`

type GetCollectionSiteRow struct {
	SiteID            uuid.UUID `json:"site_id"`
	SiteCode          string    `json:"site_code"`
	SiteName          string    `json:"site_name"`
	NewApiBaseUrl     string    `json:"new_api_base_url"`
	AdminUserID       int64     `json:"admin_user_id"`
	CredentialID      uuid.UUID `json:"credential_id"`
	CredentialPurpose string    `json:"credential_purpose"`
	Ciphertext        []byte    `json:"ciphertext"`
	Nonce             []byte    `json:"nonce"`
	KeyVersion        int32     `json:"key_version"`
}

func (q *Queries) GetCollectionSite(ctx context.Context, id uuid.UUID) (GetCollectionSiteRow, error) {
	row := q.db.QueryRow(ctx, getCollectionSite, id)
	var i GetCollectionSiteRow
	err := row.Scan(
		&i.SiteID,
		&i.SiteCode,
		&i.SiteName,
		&i.NewApiBaseUrl,
		&i.AdminUserID,
		&i.CredentialID,
		&i.CredentialPurpose,
		&i.Ciphertext,
		&i.Nonce,
		&i.KeyVersion,
	)
	return i, err
}

const getCurrentMeasurementRequestRevision = `-- name: GetCurrentMeasurementRequestRevision :one
SELECT id, revision, source_event_key, terminal_created_at, terminal_source_id
FROM measurement_requests
WHERE site_id IS NOT DISTINCT FROM $1::uuid
  AND source = $2
  AND request_hash = $3
  AND is_current
FOR UPDATE
`

type GetCurrentMeasurementRequestRevisionParams struct {
	SiteID      pgtype.UUID `json:"site_id"`
	Source      string      `json:"source"`
	RequestHash string      `json:"request_hash"`
}

type GetCurrentMeasurementRequestRevisionRow struct {
	ID                uuid.UUID `json:"id"`
	Revision          int32     `json:"revision"`
	SourceEventKey    string    `json:"source_event_key"`
	TerminalCreatedAt int64     `json:"terminal_created_at"`
	TerminalSourceID  string    `json:"terminal_source_id"`
}

func (q *Queries) GetCurrentMeasurementRequestRevision(ctx context.Context, arg GetCurrentMeasurementRequestRevisionParams) (GetCurrentMeasurementRequestRevisionRow, error) {
	row := q.db.QueryRow(ctx, getCurrentMeasurementRequestRevision, arg.SiteID, arg.Source, arg.RequestHash)
	var i GetCurrentMeasurementRequestRevisionRow
	err := row.Scan(
		&i.ID,
		&i.Revision,
		&i.SourceEventKey,
		&i.TerminalCreatedAt,
		&i.TerminalSourceID,
	)
	return i, err
}

const insertMeasurementAttempt = `-- name: InsertMeasurementAttempt :execrows
INSERT INTO measurement_attempts (
    id, request_measurement_id, attempt_index, relation_id, supplier_id,
    external_channel_id, attribution_status, model, outcome, is_final,
    is_stream, stream_completed, produced_visible_output, ttft_ms, duration_ms, duration_resolution_ms, upstream_status_code,
    error_category, error_responsibility, error_code, classification_version, observed_at, recorded_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16, $17,
    $18, $19, $20, $21, $22, $23
)
ON CONFLICT (request_measurement_id, attempt_index) DO NOTHING
`

type InsertMeasurementAttemptParams struct {
	ID                    uuid.UUID          `json:"id"`
	RequestMeasurementID  uuid.UUID          `json:"request_measurement_id"`
	AttemptIndex          int32              `json:"attempt_index"`
	RelationID            pgtype.UUID        `json:"relation_id"`
	SupplierID            pgtype.UUID        `json:"supplier_id"`
	ExternalChannelID     pgtype.Int8        `json:"external_channel_id"`
	AttributionStatus     string             `json:"attribution_status"`
	Model                 string             `json:"model"`
	Outcome               string             `json:"outcome"`
	IsFinal               bool               `json:"is_final"`
	IsStream              bool               `json:"is_stream"`
	StreamCompleted       pgtype.Bool        `json:"stream_completed"`
	ProducedVisibleOutput pgtype.Bool        `json:"produced_visible_output"`
	TtftMs                pgtype.Int8        `json:"ttft_ms"`
	DurationMs            pgtype.Int8        `json:"duration_ms"`
	DurationResolutionMs  pgtype.Int4        `json:"duration_resolution_ms"`
	UpstreamStatusCode    pgtype.Int4        `json:"upstream_status_code"`
	ErrorCategory         pgtype.Text        `json:"error_category"`
	ErrorResponsibility   pgtype.Text        `json:"error_responsibility"`
	ErrorCode             pgtype.Text        `json:"error_code"`
	ClassificationVersion string             `json:"classification_version"`
	ObservedAt            pgtype.Timestamptz `json:"observed_at"`
	RecordedAt            pgtype.Timestamptz `json:"recorded_at"`
}

func (q *Queries) InsertMeasurementAttempt(ctx context.Context, arg InsertMeasurementAttemptParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertMeasurementAttempt,
		arg.ID,
		arg.RequestMeasurementID,
		arg.AttemptIndex,
		arg.RelationID,
		arg.SupplierID,
		arg.ExternalChannelID,
		arg.AttributionStatus,
		arg.Model,
		arg.Outcome,
		arg.IsFinal,
		arg.IsStream,
		arg.StreamCompleted,
		arg.ProducedVisibleOutput,
		arg.TtftMs,
		arg.DurationMs,
		arg.DurationResolutionMs,
		arg.UpstreamStatusCode,
		arg.ErrorCategory,
		arg.ErrorResponsibility,
		arg.ErrorCode,
		arg.ClassificationVersion,
		arg.ObservedAt,
		arg.RecordedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertMeasurementQuarantine = `-- name: InsertMeasurementQuarantine :execrows
INSERT INTO measurement_quarantines (
    id, site_id, source, source_event_key, source_created_at,
    source_id, reason_code, recorded_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (site_id, source, source_event_key) DO NOTHING
`

type InsertMeasurementQuarantineParams struct {
	ID              uuid.UUID          `json:"id"`
	SiteID          uuid.UUID          `json:"site_id"`
	Source          string             `json:"source"`
	SourceEventKey  string             `json:"source_event_key"`
	SourceCreatedAt int64              `json:"source_created_at"`
	SourceID        string             `json:"source_id"`
	ReasonCode      string             `json:"reason_code"`
	RecordedAt      pgtype.Timestamptz `json:"recorded_at"`
}

func (q *Queries) InsertMeasurementQuarantine(ctx context.Context, arg InsertMeasurementQuarantineParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertMeasurementQuarantine,
		arg.ID,
		arg.SiteID,
		arg.Source,
		arg.SourceEventKey,
		arg.SourceCreatedAt,
		arg.SourceID,
		arg.ReasonCode,
		arg.RecordedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertMeasurementRequest = `-- name: InsertMeasurementRequest :execrows
INSERT INTO measurement_requests (
    id, site_id, source, request_hash, revision,
    source_contract, source_event_key, source_event_id, source_created_at,
    terminal_created_at, terminal_source_id,
    request_id, observed_at, model, request_group, outcome,
    final_relation_id, final_supplier_id, final_external_channel_id,
    attribution_status, is_stream, stream_completed, ttft_ms, duration_ms, duration_resolution_ms,
    input_tokens, output_tokens, upstream_status_code, error_category, error_responsibility, error_code,
    classification_version, completeness, missing_reason, recorded_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9,
    $10, $11,
    $12, $13, $14, $15, $16,
    $17, $18, $19,
    $20, $21, $22, $23, $24, $25,
    $26, $27, $28, $29, $30, $31,
    $32, $33, $34, $35
)
ON CONFLICT (site_id, source, source_event_key) DO NOTHING
`

type InsertMeasurementRequestParams struct {
	ID                     uuid.UUID          `json:"id"`
	SiteID                 pgtype.UUID        `json:"site_id"`
	Source                 string             `json:"source"`
	RequestHash            string             `json:"request_hash"`
	Revision               int32              `json:"revision"`
	SourceContract         string             `json:"source_contract"`
	SourceEventKey         string             `json:"source_event_key"`
	SourceEventID          pgtype.Int8        `json:"source_event_id"`
	SourceCreatedAt        pgtype.Int8        `json:"source_created_at"`
	TerminalCreatedAt      int64              `json:"terminal_created_at"`
	TerminalSourceID       string             `json:"terminal_source_id"`
	RequestID              pgtype.Text        `json:"request_id"`
	ObservedAt             pgtype.Timestamptz `json:"observed_at"`
	Model                  string             `json:"model"`
	RequestGroup           string             `json:"request_group"`
	Outcome                string             `json:"outcome"`
	FinalRelationID        pgtype.UUID        `json:"final_relation_id"`
	FinalSupplierID        pgtype.UUID        `json:"final_supplier_id"`
	FinalExternalChannelID pgtype.Int8        `json:"final_external_channel_id"`
	AttributionStatus      string             `json:"attribution_status"`
	IsStream               bool               `json:"is_stream"`
	StreamCompleted        pgtype.Bool        `json:"stream_completed"`
	TtftMs                 pgtype.Int8        `json:"ttft_ms"`
	DurationMs             pgtype.Int8        `json:"duration_ms"`
	DurationResolutionMs   pgtype.Int4        `json:"duration_resolution_ms"`
	InputTokens            pgtype.Int8        `json:"input_tokens"`
	OutputTokens           pgtype.Int8        `json:"output_tokens"`
	UpstreamStatusCode     pgtype.Int4        `json:"upstream_status_code"`
	ErrorCategory          pgtype.Text        `json:"error_category"`
	ErrorResponsibility    pgtype.Text        `json:"error_responsibility"`
	ErrorCode              pgtype.Text        `json:"error_code"`
	ClassificationVersion  string             `json:"classification_version"`
	Completeness           string             `json:"completeness"`
	MissingReason          pgtype.Text        `json:"missing_reason"`
	RecordedAt             pgtype.Timestamptz `json:"recorded_at"`
}

func (q *Queries) InsertMeasurementRequest(ctx context.Context, arg InsertMeasurementRequestParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertMeasurementRequest,
		arg.ID,
		arg.SiteID,
		arg.Source,
		arg.RequestHash,
		arg.Revision,
		arg.SourceContract,
		arg.SourceEventKey,
		arg.SourceEventID,
		arg.SourceCreatedAt,
		arg.TerminalCreatedAt,
		arg.TerminalSourceID,
		arg.RequestID,
		arg.ObservedAt,
		arg.Model,
		arg.RequestGroup,
		arg.Outcome,
		arg.FinalRelationID,
		arg.FinalSupplierID,
		arg.FinalExternalChannelID,
		arg.AttributionStatus,
		arg.IsStream,
		arg.StreamCompleted,
		arg.TtftMs,
		arg.DurationMs,
		arg.DurationResolutionMs,
		arg.InputTokens,
		arg.OutputTokens,
		arg.UpstreamStatusCode,
		arg.ErrorCategory,
		arg.ErrorResponsibility,
		arg.ErrorCode,
		arg.ClassificationVersion,
		arg.Completeness,
		arg.MissingReason,
		arg.RecordedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listChannelBindingHistory = `-- name: ListChannelBindingHistory :many
SELECT site_id, external_channel_id, relation_id, supplier_id, managed_tag, valid_from, valid_to
FROM channel_binding_history
WHERE site_id = $1
  AND valid_from < $2
  AND (valid_to IS NULL OR valid_to > $3)
ORDER BY external_channel_id, valid_from
`

type ListChannelBindingHistoryParams struct {
	SiteID      uuid.UUID          `json:"site_id"`
	WindowEnd   pgtype.Timestamptz `json:"window_end"`
	WindowStart pgtype.Timestamptz `json:"window_start"`
}

func (q *Queries) ListChannelBindingHistory(ctx context.Context, arg ListChannelBindingHistoryParams) ([]ChannelBindingHistory, error) {
	rows, err := q.db.Query(ctx, listChannelBindingHistory, arg.SiteID, arg.WindowEnd, arg.WindowStart)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChannelBindingHistory{}
	for rows.Next() {
		var i ChannelBindingHistory
		if err := rows.Scan(
			&i.SiteID,
			&i.ExternalChannelID,
			&i.RelationID,
			&i.SupplierID,
			&i.ManagedTag,
			&i.ValidFrom,
			&i.ValidTo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollectionSites = `-- name: ListCollectionSites :many
SELECT
    s.id AS site_id,
    s.code AS site_code,
    s.name AS site_name,
    s.new_api_base_url,
    s.admin_user_id,
    c.id AS credential_id,
    c.purpose AS credential_purpose,
    c.ciphertext,
    c.nonce,
    c.key_version
FROM sites s
JOIN credentials c ON c.id = s.admin_credential_id
WHERE s.status = 'enabled'
  AND c.revoked_at IS NULL
ORDER BY s.code
`

type ListCollectionSitesRow struct {
	SiteID            uuid.UUID `json:"site_id"`
	SiteCode          string    `json:"site_code"`
	SiteName          string    `json:"site_name"`
	NewApiBaseUrl     string    `json:"new_api_base_url"`
	AdminUserID       int64     `json:"admin_user_id"`
	CredentialID      uuid.UUID `json:"credential_id"`
	CredentialPurpose string    `json:"credential_purpose"`
	Ciphertext        []byte    `json:"ciphertext"`
	Nonce             []byte    `json:"nonce"`
	KeyVersion        int32     `json:"key_version"`
}

func (q *Queries) ListCollectionSites(ctx context.Context) ([]ListCollectionSitesRow, error) {
	rows, err := q.db.Query(ctx, listCollectionSites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCollectionSitesRow{}
	for rows.Next() {
		var i ListCollectionSitesRow
		if err := rows.Scan(
			&i.SiteID,
			&i.SiteCode,
			&i.SiteName,
			&i.NewApiBaseUrl,
			&i.AdminUserID,
			&i.CredentialID,
			&i.CredentialPurpose,
			&i.Ciphertext,
			&i.Nonce,
			&i.KeyVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollectionStatus = `-- name: ListCollectionStatus :many
SELECT
    s.id AS site_id,
    s.name AS site_name,
    c.source_kind,
    c.contract_version,
    c.committed_created_at,
    c.committed_source_id,
    c.scanned_through_at,
    c.source_latest_created_at,
    c.last_read_at,
    c.last_success_at,
    c.last_error_at,
    c.last_error_code,
    c.last_error_message,
    c.consecutive_failures,
    c.data_gap,
    c.updated_at
FROM sites s
LEFT JOIN collection_cursors c ON c.site_id = s.id
WHERE ($1::uuid IS NULL OR s.id = $1::uuid)
ORDER BY s.name, s.id
`

type ListCollectionStatusRow struct {
	SiteID                uuid.UUID          `json:"site_id"`
	SiteName              string             `json:"site_name"`
	SourceKind            pgtype.Text        `json:"source_kind"`
	ContractVersion       pgtype.Text        `json:"contract_version"`
	CommittedCreatedAt    pgtype.Int8        `json:"committed_created_at"`
	CommittedSourceID     pgtype.Text        `json:"committed_source_id"`
	ScannedThroughAt      pgtype.Int8        `json:"scanned_through_at"`
	SourceLatestCreatedAt pgtype.Int8        `json:"source_latest_created_at"`
	LastReadAt            pgtype.Timestamptz `json:"last_read_at"`
	LastSuccessAt         pgtype.Timestamptz `json:"last_success_at"`
	LastErrorAt           pgtype.Timestamptz `json:"last_error_at"`
	LastErrorCode         pgtype.Text        `json:"last_error_code"`
	LastErrorMessage      pgtype.Text        `json:"last_error_message"`
	ConsecutiveFailures   pgtype.Int4        `json:"consecutive_failures"`
	DataGap               pgtype.Bool        `json:"data_gap"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListCollectionStatus(ctx context.Context, siteID pgtype.UUID) ([]ListCollectionStatusRow, error) {
	rows, err := q.db.Query(ctx, listCollectionStatus, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCollectionStatusRow{}
	for rows.Next() {
		var i ListCollectionStatusRow
		if err := rows.Scan(
			&i.SiteID,
			&i.SiteName,
			&i.SourceKind,
			&i.ContractVersion,
			&i.CommittedCreatedAt,
			&i.CommittedSourceID,
			&i.ScannedThroughAt,
			&i.SourceLatestCreatedAt,
			&i.LastReadAt,
			&i.LastSuccessAt,
			&i.LastErrorAt,
			&i.LastErrorCode,
			&i.LastErrorMessage,
			&i.ConsecutiveFailures,
			&i.DataGap,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCollectionCursor = `-- name: LockCollectionCursor :one
SELECT site_id, source_kind, contract_version, committed_created_at, committed_source_id, scanned_through_at, overlap_seconds, source_latest_created_at, last_read_at, last_success_at, last_error_at, last_error_code, last_error_message, consecutive_failures, data_gap, updated_at
FROM collection_cursors
WHERE site_id = $1
FOR UPDATE
`

func (q *Queries) LockCollectionCursor(ctx context.Context, siteID uuid.UUID) (CollectionCursor, error) {
	row := q.db.QueryRow(ctx, lockCollectionCursor, siteID)
	var i CollectionCursor
	err := row.Scan(
		&i.SiteID,
		&i.SourceKind,
		&i.ContractVersion,
		&i.CommittedCreatedAt,
		&i.CommittedSourceID,
		&i.ScannedThroughAt,
		&i.OverlapSeconds,
		&i.SourceLatestCreatedAt,
		&i.LastReadAt,
		&i.LastSuccessAt,
		&i.LastErrorAt,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.ConsecutiveFailures,
		&i.DataGap,
		&i.UpdatedAt,
	)
	return i, err
}

const markCollectionFailure = `-- name: MarkCollectionFailure :exec
UPDATE collection_cursors
SET last_read_at = $2,
    last_error_at = $2,
    last_error_code = $3,
    last_error_message = $4,
    consecutive_failures = consecutive_failures + 1,
    data_gap = true,
    updated_at = $2
WHERE collection_cursors.site_id = $1
`

type MarkCollectionFailureParams struct {
	SiteID           uuid.UUID          `json:"site_id"`
	LastReadAt       pgtype.Timestamptz `json:"last_read_at"`
	LastErrorCode    pgtype.Text        `json:"last_error_code"`
	LastErrorMessage pgtype.Text        `json:"last_error_message"`
}

func (q *Queries) MarkCollectionFailure(ctx context.Context, arg MarkCollectionFailureParams) error {
	_, err := q.db.Exec(ctx, markCollectionFailure,
		arg.SiteID,
		arg.LastReadAt,
		arg.LastErrorCode,
		arg.LastErrorMessage,
	)
	return err
}

const markCollectionSuccess = `-- name: MarkCollectionSuccess :exec
UPDATE collection_cursors
SET committed_created_at = $2,
    committed_source_id = $3,
    scanned_through_at = $4,
    source_latest_created_at = CASE
        WHEN $5::bigint IS NULL THEN source_latest_created_at
        ELSE GREATEST(COALESCE(source_latest_created_at, 0), $5::bigint)
    END,
    last_read_at = $6,
    last_success_at = $6,
    last_error_code = NULL,
    last_error_message = NULL,
    consecutive_failures = 0,
    data_gap = $7 OR EXISTS (
        SELECT 1
        FROM measurement_quarantines quarantine
        WHERE quarantine.site_id = collection_cursors.site_id
          AND quarantine.resolved_at IS NULL
    ),
    updated_at = $6
WHERE collection_cursors.site_id = $1
`

type MarkCollectionSuccessParams struct {
	SiteID                uuid.UUID          `json:"site_id"`
	CommittedCreatedAt    int64              `json:"committed_created_at"`
	CommittedSourceID     string             `json:"committed_source_id"`
	ScannedThroughAt      int64              `json:"scanned_through_at"`
	SourceLatestCreatedAt pgtype.Int8        `json:"source_latest_created_at"`
	LastReadAt            pgtype.Timestamptz `json:"last_read_at"`
	DataGap               bool               `json:"data_gap"`
}

func (q *Queries) MarkCollectionSuccess(ctx context.Context, arg MarkCollectionSuccessParams) error {
	_, err := q.db.Exec(ctx, markCollectionSuccess,
		arg.SiteID,
		arg.CommittedCreatedAt,
		arg.CommittedSourceID,
		arg.ScannedThroughAt,
		arg.SourceLatestCreatedAt,
		arg.LastReadAt,
		arg.DataGap,
	)
	return err
}

const refreshCollectionDataGap = `-- name: RefreshCollectionDataGap :exec
UPDATE collection_cursors
SET data_gap = EXISTS (
        SELECT 1
        FROM measurement_quarantines quarantine
        WHERE quarantine.site_id = collection_cursors.site_id
          AND quarantine.resolved_at IS NULL
    ),
    updated_at = $2
WHERE collection_cursors.site_id = $1
`

type RefreshCollectionDataGapParams struct {
	SiteID    uuid.UUID          `json:"site_id"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) RefreshCollectionDataGap(ctx context.Context, arg RefreshCollectionDataGapParams) error {
	_, err := q.db.Exec(ctx, refreshCollectionDataGap, arg.SiteID, arg.UpdatedAt)
	return err
}

const resolveChannelBinding = `-- name: ResolveChannelBinding :one
SELECT relation_id, supplier_id, managed_tag
FROM channel_binding_history
WHERE site_id = $1
  AND external_channel_id = $2
  AND valid_from <= $3
  AND (valid_to IS NULL OR valid_to > $3)
ORDER BY valid_from DESC
LIMIT 1
`

type ResolveChannelBindingParams struct {
	SiteID            uuid.UUID          `json:"site_id"`
	ExternalChannelID int64              `json:"external_channel_id"`
	ValidFrom         pgtype.Timestamptz `json:"valid_from"`
}

type ResolveChannelBindingRow struct {
	RelationID uuid.UUID `json:"relation_id"`
	SupplierID uuid.UUID `json:"supplier_id"`
	ManagedTag string    `json:"managed_tag"`
}

func (q *Queries) ResolveChannelBinding(ctx context.Context, arg ResolveChannelBindingParams) (ResolveChannelBindingRow, error) {
	row := q.db.QueryRow(ctx, resolveChannelBinding, arg.SiteID, arg.ExternalChannelID, arg.ValidFrom)
	var i ResolveChannelBindingRow
	err := row.Scan(&i.RelationID, &i.SupplierID, &i.ManagedTag)
	return i, err
}

const resolveMeasurementQuarantine = `-- name: ResolveMeasurementQuarantine :execrows
UPDATE measurement_quarantines
SET resolved_at = $3
WHERE site_id = $1 AND source_event_key = $2 AND resolved_at IS NULL
`

type ResolveMeasurementQuarantineParams struct {
	SiteID         uuid.UUID          `json:"site_id"`
	SourceEventKey string             `json:"source_event_key"`
	ResolvedAt     pgtype.Timestamptz `json:"resolved_at"`
}

func (q *Queries) ResolveMeasurementQuarantine(ctx context.Context, arg ResolveMeasurementQuarantineParams) (int64, error) {
	result, err := q.db.Exec(ctx, resolveMeasurementQuarantine, arg.SiteID, arg.SourceEventKey, arg.ResolvedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const supersedeMeasurementRequest = `-- name: SupersedeMeasurementRequest :execrows
UPDATE measurement_requests
SET is_current = FALSE,
    superseded_at = $2
WHERE id = $1 AND is_current
`

type SupersedeMeasurementRequestParams struct {
	ID           uuid.UUID          `json:"id"`
	SupersededAt pgtype.Timestamptz `json:"superseded_at"`
}

func (q *Queries) SupersedeMeasurementRequest(ctx context.Context, arg SupersedeMeasurementRequestParams) (int64, error) {
	result, err := q.db.Exec(ctx, supersedeMeasurementRequest, arg.ID, arg.SupersededAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
