// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type AttemptLatencyHistograms1m struct {
	BucketStart  pgtype.Timestamptz `json:"bucket_start"`
	SiteID       uuid.UUID          `json:"site_id"`
	SupplierID   uuid.UUID          `json:"supplier_id"`
	Model        string             `json:"model"`
	Source       string             `json:"source"`
	Metric       string             `json:"metric"`
	UpperBoundMs int64              `json:"upper_bound_ms"`
	SampleCount  int64              `json:"sample_count"`
}

type AttemptMetrics1m struct {
	BucketStart          pgtype.Timestamptz `json:"bucket_start"`
	SiteID               uuid.UUID          `json:"site_id"`
	SupplierID           uuid.UUID          `json:"supplier_id"`
	Model                string             `json:"model"`
	Source               string             `json:"source"`
	AttemptCount         int64              `json:"attempt_count"`
	SlaAttemptCount      int64              `json:"sla_attempt_count"`
	SuccessCount         int64              `json:"success_count"`
	FailureCount         int64              `json:"failure_count"`
	SlaFailureCount      int64              `json:"sla_failure_count"`
	RateLimitedCount     int64              `json:"rate_limited_count"`
	AuthenticationCount  int64              `json:"authentication_count"`
	BalanceCount         int64              `json:"balance_count"`
	TimeoutCount         int64              `json:"timeout_count"`
	TransportCount       int64              `json:"transport_count"`
	UpstreamCount        int64              `json:"upstream_count"`
	StreamCount          int64              `json:"stream_count"`
	StreamCompletedCount int64              `json:"stream_completed_count"`
	TtftSumMs            int64              `json:"ttft_sum_ms"`
	TtftCount            int64              `json:"ttft_count"`
	SuccessDurationSumMs int64              `json:"success_duration_sum_ms"`
	SuccessDurationCount int64              `json:"success_duration_count"`
	FailureDurationSumMs int64              `json:"failure_duration_sum_ms"`
	FailureDurationCount int64              `json:"failure_duration_count"`
	CoarseDurationCount  int64              `json:"coarse_duration_count"`
	ComputedAt           pgtype.Timestamptz `json:"computed_at"`
}

type AuditEvent struct {
	ID          uuid.UUID          `json:"id"`
	ActorType   string             `json:"actor_type"`
	ActorID     string             `json:"actor_id"`
	SiteID      pgtype.UUID        `json:"site_id"`
	ObjectType  string             `json:"object_type"`
	ObjectID    string             `json:"object_id"`
	Action      string             `json:"action"`
	Reason      string             `json:"reason"`
	OperationID pgtype.UUID        `json:"operation_id"`
	OldSummary  []byte             `json:"old_summary"`
	NewSummary  []byte             `json:"new_summary"`
	Result      string             `json:"result"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type AuthLoginAttempt struct {
	Key         string             `json:"key"`
	Attempts    int32              `json:"attempts"`
	WindowStart pgtype.Timestamptz `json:"window_start"`
}

type AuthenticityAssessment struct {
	ID               uuid.UUID          `json:"id"`
	RunID            uuid.UUID          `json:"run_id"`
	SupplierID       uuid.UUID          `json:"supplier_id"`
	SiteID           pgtype.UUID        `json:"site_id"`
	Model            string             `json:"model"`
	Verdict          string             `json:"verdict"`
	Confidence       decimal.Decimal    `json:"confidence"`
	ReferenceID      pgtype.UUID        `json:"reference_id"`
	MeanDistance     pgtype.Numeric     `json:"mean_distance"`
	SelfDistance     pgtype.Numeric     `json:"self_distance"`
	ComparableCells  int32              `json:"comparable_cells"`
	EvidenceConflict bool               `json:"evidence_conflict"`
	Evidence         []byte             `json:"evidence"`
	AlgorithmVersion string             `json:"algorithm_version"`
	CheckedAt        pgtype.Timestamptz `json:"checked_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

type AutomationDecision struct {
	ID               uuid.UUID          `json:"id"`
	RunID            uuid.UUID          `json:"run_id"`
	StrategyID       uuid.UUID          `json:"strategy_id"`
	RelationID       uuid.UUID          `json:"relation_id"`
	Action           string             `json:"action"`
	CurrentMember    bool               `json:"current_member"`
	TargetMember     bool               `json:"target_member"`
	HoldAction       string             `json:"hold_action"`
	Reasons          []byte             `json:"reasons"`
	ScoreSnapshotIds []uuid.UUID        `json:"score_snapshot_ids"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type AutomationRun struct {
	ID          uuid.UUID          `json:"id"`
	SiteID      uuid.UUID          `json:"site_id"`
	ScoreRunID  uuid.UUID          `json:"score_run_id"`
	Status      string             `json:"status"`
	TriggerKind string             `json:"trigger_kind"`
	RoutePlanID pgtype.UUID        `json:"route_plan_id"`
	Summary     string             `json:"summary"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

type CapabilityAssessment struct {
	ID              uuid.UUID          `json:"id"`
	RunID           uuid.UUID          `json:"run_id"`
	SupplierID      uuid.UUID          `json:"supplier_id"`
	SiteID          pgtype.UUID        `json:"site_id"`
	Model           string             `json:"model"`
	Score           decimal.Decimal    `json:"score"`
	Confidence      decimal.Decimal    `json:"confidence"`
	CompletedChecks int32              `json:"completed_checks"`
	TotalChecks     int32              `json:"total_checks"`
	SuiteVersion    string             `json:"suite_version"`
	CheckedAt       pgtype.Timestamptz `json:"checked_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
}

type ChannelBindingHistory struct {
	SiteID            uuid.UUID          `json:"site_id"`
	ExternalChannelID int64              `json:"external_channel_id"`
	RelationID        uuid.UUID          `json:"relation_id"`
	SupplierID        uuid.UUID          `json:"supplier_id"`
	ManagedTag        string             `json:"managed_tag"`
	ValidFrom         pgtype.Timestamptz `json:"valid_from"`
	ValidTo           pgtype.Timestamptz `json:"valid_to"`
}

type CollectionCursor struct {
	SiteID                uuid.UUID          `json:"site_id"`
	SourceKind            string             `json:"source_kind"`
	ContractVersion       string             `json:"contract_version"`
	CommittedCreatedAt    int64              `json:"committed_created_at"`
	CommittedSourceID     string             `json:"committed_source_id"`
	ScannedThroughAt      int64              `json:"scanned_through_at"`
	OverlapSeconds        int32              `json:"overlap_seconds"`
	SourceLatestCreatedAt pgtype.Int8        `json:"source_latest_created_at"`
	LastReadAt            pgtype.Timestamptz `json:"last_read_at"`
	LastSuccessAt         pgtype.Timestamptz `json:"last_success_at"`
	LastErrorAt           pgtype.Timestamptz `json:"last_error_at"`
	LastErrorCode         pgtype.Text        `json:"last_error_code"`
	LastErrorMessage      pgtype.Text        `json:"last_error_message"`
	ConsecutiveFailures   int32              `json:"consecutive_failures"`
	DataGap               bool               `json:"data_gap"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type Credential struct {
	ID         uuid.UUID          `json:"id"`
	Purpose    string             `json:"purpose"`
	Ciphertext []byte             `json:"ciphertext"`
	Nonce      []byte             `json:"nonce"`
	KeyVersion int32              `json:"key_version"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
}

type EvaluationBudgetReservation struct {
	RunID          uuid.UUID          `json:"run_id"`
	SupplierID     uuid.UUID          `json:"supplier_id"`
	Model          string             `json:"model"`
	BucketDate     pgtype.Date        `json:"bucket_date"`
	PlannedSamples int32              `json:"planned_samples"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type EvaluationDailyBudget struct {
	SupplierID      uuid.UUID          `json:"supplier_id"`
	Model           string             `json:"model"`
	BucketDate      pgtype.Date        `json:"bucket_date"`
	ReservedSamples int32              `json:"reserved_samples"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type EvaluationFingerprint struct {
	RunID           uuid.UUID          `json:"run_id"`
	ProtocolVersion string             `json:"protocol_version"`
	Cells           []byte             `json:"cells"`
	ValidCells      int32              `json:"valid_cells"`
	ValidSamples    int32              `json:"valid_samples"`
	SelfDistance    pgtype.Numeric     `json:"self_distance"`
	Stable          bool               `json:"stable"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type EvaluationRun struct {
	ID               uuid.UUID          `json:"id"`
	SupplierID       uuid.UUID          `json:"supplier_id"`
	RelationID       pgtype.UUID        `json:"relation_id"`
	SiteID           pgtype.UUID        `json:"site_id"`
	Model            string             `json:"model"`
	UpstreamModel    string             `json:"upstream_model"`
	TargetKind       string             `json:"target_kind"`
	Purpose          string             `json:"purpose"`
	Status           string             `json:"status"`
	SuiteVersion     string             `json:"suite_version"`
	AlgorithmVersion string             `json:"algorithm_version"`
	RandomSeed       int64              `json:"random_seed"`
	ReferenceID      pgtype.UUID        `json:"reference_id"`
	PlannedSamples   int32              `json:"planned_samples"`
	CompletedSamples int32              `json:"completed_samples"`
	RequestedBy      string             `json:"requested_by"`
	RequestReason    string             `json:"request_reason"`
	ErrorCode        pgtype.Text        `json:"error_code"`
	ErrorMessage     pgtype.Text        `json:"error_message"`
	RequestedAt      pgtype.Timestamptz `json:"requested_at"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	NextRetryAt      pgtype.Timestamptz `json:"next_retry_at"`
	RequestKey       pgtype.Text        `json:"request_key"`
	RequestHash      pgtype.Text        `json:"request_hash"`
}

type EvaluationSample struct {
	RunID                 uuid.UUID          `json:"run_id"`
	ProbeKey              string             `json:"probe_key"`
	SampleIndex           int32              `json:"sample_index"`
	PromptVariant         int32              `json:"prompt_variant"`
	Outcome               string             `json:"outcome"`
	NormalizedAnswer      pgtype.Text        `json:"normalized_answer"`
	AnswerDigest          pgtype.Text        `json:"answer_digest"`
	ResponseModel         pgtype.Text        `json:"response_model"`
	ResponseShape         []byte             `json:"response_shape"`
	TtftMs                pgtype.Int8        `json:"ttft_ms"`
	DurationMs            pgtype.Int8        `json:"duration_ms"`
	InputTokens           pgtype.Int8        `json:"input_tokens"`
	OutputTokens          pgtype.Int8        `json:"output_tokens"`
	StreamCompleted       pgtype.Bool        `json:"stream_completed"`
	UpstreamStatusCode    pgtype.Int4        `json:"upstream_status_code"`
	ErrorCategory         pgtype.Text        `json:"error_category"`
	ErrorCode             pgtype.Text        `json:"error_code"`
	ClassificationVersion string             `json:"classification_version"`
	MeasurementRequestID  pgtype.UUID        `json:"measurement_request_id"`
	CollectedAt           pgtype.Timestamptz `json:"collected_at"`
}

type IdempotencyRecord struct {
	Scope          string             `json:"scope"`
	IdempotencyKey string             `json:"idempotency_key"`
	RequestHash    string             `json:"request_hash"`
	StatusCode     int32              `json:"status_code"`
	ResponseBody   []byte             `json:"response_body"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

type MeasurementAttempt struct {
	ID                    uuid.UUID          `json:"id"`
	RequestMeasurementID  uuid.UUID          `json:"request_measurement_id"`
	AttemptIndex          int32              `json:"attempt_index"`
	RelationID            pgtype.UUID        `json:"relation_id"`
	SupplierID            pgtype.UUID        `json:"supplier_id"`
	ExternalChannelID     pgtype.Int8        `json:"external_channel_id"`
	AttributionStatus     string             `json:"attribution_status"`
	Model                 string             `json:"model"`
	Outcome               string             `json:"outcome"`
	IsFinal               bool               `json:"is_final"`
	IsStream              bool               `json:"is_stream"`
	StreamCompleted       pgtype.Bool        `json:"stream_completed"`
	ProducedVisibleOutput pgtype.Bool        `json:"produced_visible_output"`
	TtftMs                pgtype.Int8        `json:"ttft_ms"`
	DurationMs            pgtype.Int8        `json:"duration_ms"`
	DurationResolutionMs  pgtype.Int4        `json:"duration_resolution_ms"`
	UpstreamStatusCode    pgtype.Int4        `json:"upstream_status_code"`
	ErrorCategory         pgtype.Text        `json:"error_category"`
	ErrorResponsibility   pgtype.Text        `json:"error_responsibility"`
	ErrorCode             pgtype.Text        `json:"error_code"`
	ClassificationVersion string             `json:"classification_version"`
	ObservedAt            pgtype.Timestamptz `json:"observed_at"`
	RecordedAt            pgtype.Timestamptz `json:"recorded_at"`
}

type MeasurementQuarantine struct {
	ID              uuid.UUID          `json:"id"`
	SiteID          uuid.UUID          `json:"site_id"`
	Source          string             `json:"source"`
	SourceEventKey  string             `json:"source_event_key"`
	SourceCreatedAt int64              `json:"source_created_at"`
	SourceID        string             `json:"source_id"`
	ReasonCode      string             `json:"reason_code"`
	RecordedAt      pgtype.Timestamptz `json:"recorded_at"`
	ResolvedAt      pgtype.Timestamptz `json:"resolved_at"`
}

type MeasurementRequest struct {
	ID                     uuid.UUID          `json:"id"`
	SiteID                 pgtype.UUID        `json:"site_id"`
	Source                 string             `json:"source"`
	RequestHash            string             `json:"request_hash"`
	Revision               int32              `json:"revision"`
	IsCurrent              bool               `json:"is_current"`
	SupersededAt           pgtype.Timestamptz `json:"superseded_at"`
	SourceContract         string             `json:"source_contract"`
	SourceEventKey         string             `json:"source_event_key"`
	SourceEventID          pgtype.Int8        `json:"source_event_id"`
	SourceCreatedAt        pgtype.Int8        `json:"source_created_at"`
	TerminalCreatedAt      int64              `json:"terminal_created_at"`
	TerminalSourceID       string             `json:"terminal_source_id"`
	RequestID              pgtype.Text        `json:"request_id"`
	ObservedAt             pgtype.Timestamptz `json:"observed_at"`
	Model                  string             `json:"model"`
	RequestGroup           string             `json:"request_group"`
	Outcome                string             `json:"outcome"`
	FinalRelationID        pgtype.UUID        `json:"final_relation_id"`
	FinalSupplierID        pgtype.UUID        `json:"final_supplier_id"`
	FinalExternalChannelID pgtype.Int8        `json:"final_external_channel_id"`
	AttributionStatus      string             `json:"attribution_status"`
	IsStream               bool               `json:"is_stream"`
	StreamCompleted        pgtype.Bool        `json:"stream_completed"`
	TtftMs                 pgtype.Int8        `json:"ttft_ms"`
	DurationMs             pgtype.Int8        `json:"duration_ms"`
	DurationResolutionMs   pgtype.Int4        `json:"duration_resolution_ms"`
	InputTokens            pgtype.Int8        `json:"input_tokens"`
	OutputTokens           pgtype.Int8        `json:"output_tokens"`
	UpstreamStatusCode     pgtype.Int4        `json:"upstream_status_code"`
	ErrorCategory          pgtype.Text        `json:"error_category"`
	ErrorResponsibility    pgtype.Text        `json:"error_responsibility"`
	ErrorCode              pgtype.Text        `json:"error_code"`
	ClassificationVersion  string             `json:"classification_version"`
	Completeness           string             `json:"completeness"`
	MissingReason          pgtype.Text        `json:"missing_reason"`
	RecordedAt             pgtype.Timestamptz `json:"recorded_at"`
}

type Operator struct {
	ID           uuid.UUID          `json:"id"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	Enabled      bool               `json:"enabled"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type OperatorSession struct {
	TokenHash  string             `json:"token_hash"`
	OperatorID uuid.UUID          `json:"operator_id"`
	CsrfHash   string             `json:"csrf_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type PriceVersion struct {
	ID           uuid.UUID          `json:"id"`
	SiteID       uuid.UUID          `json:"site_id"`
	GroupKey     string             `json:"group_key"`
	Version      int64              `json:"version"`
	SaleRatio    decimal.Decimal    `json:"sale_ratio"`
	Reason       string             `json:"reason"`
	Status       string             `json:"status"`
	BillingBasis []byte             `json:"billing_basis"`
	BasisHash    string             `json:"basis_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	PublishedAt  pgtype.Timestamptz `json:"published_at"`
	AppliedAt    pgtype.Timestamptz `json:"applied_at"`
	RoutePlanID  pgtype.UUID        `json:"route_plan_id"`
}

type RequestLatencyHistograms1m struct {
	BucketStart  pgtype.Timestamptz `json:"bucket_start"`
	SiteID       uuid.UUID          `json:"site_id"`
	Model        string             `json:"model"`
	Source       string             `json:"source"`
	Metric       string             `json:"metric"`
	UpperBoundMs int64              `json:"upper_bound_ms"`
	SampleCount  int64              `json:"sample_count"`
}

type RequestMetrics1m struct {
	BucketStart          pgtype.Timestamptz `json:"bucket_start"`
	SiteID               uuid.UUID          `json:"site_id"`
	Model                string             `json:"model"`
	Source               string             `json:"source"`
	RequestCount         int64              `json:"request_count"`
	SuccessCount         int64              `json:"success_count"`
	FailureCount         int64              `json:"failure_count"`
	MappedCount          int64              `json:"mapped_count"`
	StreamCount          int64              `json:"stream_count"`
	StreamCompletedCount int64              `json:"stream_completed_count"`
	InputTokens          int64              `json:"input_tokens"`
	OutputTokens         int64              `json:"output_tokens"`
	TtftSumMs            int64              `json:"ttft_sum_ms"`
	TtftCount            int64              `json:"ttft_count"`
	SuccessDurationSumMs int64              `json:"success_duration_sum_ms"`
	SuccessDurationCount int64              `json:"success_duration_count"`
	FailureDurationSumMs int64              `json:"failure_duration_sum_ms"`
	FailureDurationCount int64              `json:"failure_duration_count"`
	CoarseDurationCount  int64              `json:"coarse_duration_count"`
	ComputedAt           pgtype.Timestamptz `json:"computed_at"`
}

type RoutePlanVersion struct {
	ID             uuid.UUID          `json:"id"`
	SiteID         uuid.UUID          `json:"site_id"`
	SiteSupplierID uuid.UUID          `json:"site_supplier_id"`
	Version        int64              `json:"version"`
	PreviousPlanID pgtype.UUID        `json:"previous_plan_id"`
	Reason         string             `json:"reason"`
	Snapshot       []byte             `json:"snapshot"`
	ContentHash    string             `json:"content_hash"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ConfirmedAt    pgtype.Timestamptz `json:"confirmed_at"`
}

type ScoreRun struct {
	ID               uuid.UUID          `json:"id"`
	SiteID           uuid.UUID          `json:"site_id"`
	PolicyVersion    string             `json:"policy_version"`
	WindowEnd        pgtype.Timestamptz `json:"window_end"`
	ExpectedTargets  int32              `json:"expected_targets"`
	CompletedTargets int32              `json:"completed_targets"`
	Status           string             `json:"status"`
	ErrorSummary     pgtype.Text        `json:"error_summary"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
}

type ScoreSnapshot struct {
	ID                       uuid.UUID          `json:"id"`
	SiteID                   uuid.UUID          `json:"site_id"`
	SupplierID               uuid.UUID          `json:"supplier_id"`
	Model                    string             `json:"model"`
	PolicyVersion            string             `json:"policy_version"`
	WindowStart              pgtype.Timestamptz `json:"window_start"`
	WindowEnd                pgtype.Timestamptz `json:"window_end"`
	FactsThrough             pgtype.Timestamptz `json:"facts_through"`
	PassiveSamples           int64              `json:"passive_samples"`
	ActiveSamples            int64              `json:"active_samples"`
	PriceScore               pgtype.Numeric     `json:"price_score"`
	LatencyScore             pgtype.Numeric     `json:"latency_score"`
	SlaScore                 pgtype.Numeric     `json:"sla_score"`
	QualityScore             pgtype.Numeric     `json:"quality_score"`
	TotalScore               pgtype.Numeric     `json:"total_score"`
	Confidence               string             `json:"confidence"`
	Eligibility              string             `json:"eligibility"`
	HardReasons              []byte             `json:"hard_reasons"`
	Explanation              []byte             `json:"explanation"`
	AuthenticityAssessmentID pgtype.UUID        `json:"authenticity_assessment_id"`
	CapabilityAssessmentID   pgtype.UUID        `json:"capability_assessment_id"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	ScoreRunID               pgtype.UUID        `json:"score_run_id"`
}

type ScoringAggregationState struct {
	Name          string             `json:"name"`
	InitializedAt pgtype.Timestamptz `json:"initialized_at"`
	FactsThrough  pgtype.Timestamptz `json:"facts_through"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type ScoringPolicyVersion struct {
	Version               string             `json:"version"`
	MinimumPassiveSamples int32              `json:"minimum_passive_samples"`
	WindowWeights         []byte             `json:"window_weights"`
	StrategyWeights       []byte             `json:"strategy_weights"`
	Thresholds            []byte             `json:"thresholds"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
}

type ShadowRecommendation struct {
	ID              uuid.UUID          `json:"id"`
	ScoreSnapshotID uuid.UUID          `json:"score_snapshot_id"`
	SiteID          uuid.UUID          `json:"site_id"`
	SupplierID      uuid.UUID          `json:"supplier_id"`
	Model           string             `json:"model"`
	StrategyKind    string             `json:"strategy_kind"`
	Action          string             `json:"action"`
	CurrentMember   bool               `json:"current_member"`
	Score           pgtype.Numeric     `json:"score"`
	Confidence      string             `json:"confidence"`
	Reasons         []byte             `json:"reasons"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Site struct {
	ID                  uuid.UUID          `json:"id"`
	Code                string             `json:"code"`
	Name                string             `json:"name"`
	NewApiBaseUrl       string             `json:"new_api_base_url"`
	AdminCredentialID   uuid.UUID          `json:"admin_credential_id"`
	Status              string             `json:"status"`
	CompatibilityStatus string             `json:"compatibility_status"`
	Version             int64              `json:"version"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	AdminUserID         int64              `json:"admin_user_id"`
}

type SiteProductSnapshot struct {
	ID           uuid.UUID          `json:"id"`
	SiteID       uuid.UUID          `json:"site_id"`
	Version      int64              `json:"version"`
	RoutePlanID  uuid.UUID          `json:"route_plan_id"`
	ScoreRunID   pgtype.UUID        `json:"score_run_id"`
	Content      []byte             `json:"content"`
	ContentHash  string             `json:"content_hash"`
	FactsThrough pgtype.Timestamptz `json:"facts_through"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type SiteProductToken struct {
	ID         uuid.UUID          `json:"id"`
	SiteID     uuid.UUID          `json:"site_id"`
	TokenHash  string             `json:"token_hash"`
	Status     string             `json:"status"`
	Reason     string             `json:"reason"`
	CreatedBy  string             `json:"created_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
}

type SiteStrategy struct {
	ID          uuid.UUID          `json:"id"`
	SiteID      uuid.UUID          `json:"site_id"`
	Kind        string             `json:"kind"`
	GroupKey    string             `json:"group_key"`
	DisplayName string             `json:"display_name"`
	Enabled     bool               `json:"enabled"`
	Visible     bool               `json:"visible"`
	Version     int64              `json:"version"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type SiteSupplier struct {
	ID               uuid.UUID          `json:"id"`
	SiteID           uuid.UUID          `json:"site_id"`
	SupplierID       uuid.UUID          `json:"supplier_id"`
	GroupKey         string             `json:"group_key"`
	GroupDisplayName string             `json:"group_display_name"`
	SaleRatio        decimal.Decimal    `json:"sale_ratio"`
	Visible          bool               `json:"visible"`
	DesiredStatus    string             `json:"desired_status"`
	SyncStatus       string             `json:"sync_status"`
	Version          int64              `json:"version"`
	CurrentPlanID    pgtype.UUID        `json:"current_plan_id"`
	LastConfirmedAt  pgtype.Timestamptz `json:"last_confirmed_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type SiteSupplierAutomationHold struct {
	RelationID  uuid.UUID          `json:"relation_id"`
	Active      bool               `json:"active"`
	ReasonCodes []byte             `json:"reason_codes"`
	SourceRunID uuid.UUID          `json:"source_run_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ClearedAt   pgtype.Timestamptz `json:"cleared_at"`
}

type SiteSupplierChannel struct {
	ID                             uuid.UUID          `json:"id"`
	SiteSupplierID                 uuid.UUID          `json:"site_supplier_id"`
	ManagedTag                     string             `json:"managed_tag"`
	ExternalChannelID              pgtype.Int8        `json:"external_channel_id"`
	LastConfirmedPlanVersion       pgtype.Int8        `json:"last_confirmed_plan_version"`
	CreatedAt                      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                      pgtype.Timestamptz `json:"updated_at"`
	LastConfirmedCredentialID      pgtype.UUID        `json:"last_confirmed_credential_id"`
	LastConfirmedCredentialVersion pgtype.Int4        `json:"last_confirmed_credential_version"`
	LastConfirmedEnabled           pgtype.Bool        `json:"last_confirmed_enabled"`
}

type StrategyAutomationSetting struct {
	StrategyID              uuid.UUID          `json:"strategy_id"`
	Mode                    string             `json:"mode"`
	Version                 int64              `json:"version"`
	EntryClosedByAutomation bool               `json:"entry_closed_by_automation"`
	Reason                  string             `json:"reason"`
	UpdatedBy               string             `json:"updated_by"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

type StrategyMember struct {
	StrategyID uuid.UUID `json:"strategy_id"`
	RelationID uuid.UUID `json:"relation_id"`
}

type StrategyVersion struct {
	StrategyID uuid.UUID          `json:"strategy_id"`
	Version    int64              `json:"version"`
	Snapshot   []byte             `json:"snapshot"`
	Reason     string             `json:"reason"`
	ActorID    string             `json:"actor_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Supplier struct {
	ID                       uuid.UUID          `json:"id"`
	Code                     string             `json:"code"`
	Name                     string             `json:"name"`
	Protocol                 string             `json:"protocol"`
	UpstreamBaseUrl          string             `json:"upstream_base_url"`
	CredentialID             uuid.UUID          `json:"credential_id"`
	CredentialVersion        int32              `json:"credential_version"`
	Status                   string             `json:"status"`
	Version                  int64              `json:"version"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	PendingCredentialID      pgtype.UUID        `json:"pending_credential_id"`
	PendingCredentialVersion pgtype.Int4        `json:"pending_credential_version"`
}

type SupplierModel struct {
	SupplierID    uuid.UUID          `json:"supplier_id"`
	Model         string             `json:"model"`
	UpstreamModel string             `json:"upstream_model"`
	InputPrice    decimal.Decimal    `json:"input_price"`
	OutputPrice   decimal.Decimal    `json:"output_price"`
	Currency      string             `json:"currency"`
	Enabled       bool               `json:"enabled"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type SupplierModelPriceHistory struct {
	SupplierID  uuid.UUID          `json:"supplier_id"`
	Model       string             `json:"model"`
	Version     int64              `json:"version"`
	InputPrice  decimal.Decimal    `json:"input_price"`
	OutputPrice decimal.Decimal    `json:"output_price"`
	Currency    string             `json:"currency"`
	ValidFrom   pgtype.Timestamptz `json:"valid_from"`
	ValidTo     pgtype.Timestamptz `json:"valid_to"`
}

type SyncOperation struct {
	ID               uuid.UUID          `json:"id"`
	SiteID           uuid.UUID          `json:"site_id"`
	SiteSupplierID   uuid.UUID          `json:"site_supplier_id"`
	RoutePlanID      uuid.UUID          `json:"route_plan_id"`
	Status           string             `json:"status"`
	CurrentStep      pgtype.Text        `json:"current_step"`
	Attempt          int32              `json:"attempt"`
	LastErrorCode    pgtype.Text        `json:"last_error_code"`
	LastErrorMessage pgtype.Text        `json:"last_error_message"`
	NextAttemptAt    pgtype.Timestamptz `json:"next_attempt_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
}

type SyncStep struct {
	OperationID   uuid.UUID          `json:"operation_id"`
	StepKey       string             `json:"step_key"`
	Status        string             `json:"status"`
	BeforeSummary []byte             `json:"before_summary"`
	AfterSummary  []byte             `json:"after_summary"`
	ErrorCode     pgtype.Text        `json:"error_code"`
	ErrorMessage  pgtype.Text        `json:"error_message"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	FinishedAt    pgtype.Timestamptz `json:"finished_at"`
}

type TrustedModelReference struct {
	ID               uuid.UUID          `json:"id"`
	Model            string             `json:"model"`
	SupplierID       uuid.UUID          `json:"supplier_id"`
	FingerprintRunID uuid.UUID          `json:"fingerprint_run_id"`
	TrustLevel       string             `json:"trust_level"`
	ProtocolVersion  string             `json:"protocol_version"`
	Reason           string             `json:"reason"`
	CreatedBy        string             `json:"created_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	RequestKey       pgtype.Text        `json:"request_key"`
	RequestHash      pgtype.Text        `json:"request_hash"`
}
