// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type AuditEvent struct {
	ID          uuid.UUID          `json:"id"`
	ActorType   string             `json:"actor_type"`
	ActorID     string             `json:"actor_id"`
	SiteID      pgtype.UUID        `json:"site_id"`
	ObjectType  string             `json:"object_type"`
	ObjectID    string             `json:"object_id"`
	Action      string             `json:"action"`
	Reason      string             `json:"reason"`
	OperationID pgtype.UUID        `json:"operation_id"`
	OldSummary  []byte             `json:"old_summary"`
	NewSummary  []byte             `json:"new_summary"`
	Result      string             `json:"result"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type AuthLoginAttempt struct {
	Key         string             `json:"key"`
	Attempts    int32              `json:"attempts"`
	WindowStart pgtype.Timestamptz `json:"window_start"`
}

type Credential struct {
	ID         uuid.UUID          `json:"id"`
	Purpose    string             `json:"purpose"`
	Ciphertext []byte             `json:"ciphertext"`
	Nonce      []byte             `json:"nonce"`
	KeyVersion int32              `json:"key_version"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
}

type IdempotencyRecord struct {
	Scope          string             `json:"scope"`
	IdempotencyKey string             `json:"idempotency_key"`
	RequestHash    string             `json:"request_hash"`
	StatusCode     int32              `json:"status_code"`
	ResponseBody   []byte             `json:"response_body"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

type Operator struct {
	ID           uuid.UUID          `json:"id"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	Enabled      bool               `json:"enabled"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type OperatorSession struct {
	TokenHash  string             `json:"token_hash"`
	OperatorID uuid.UUID          `json:"operator_id"`
	CsrfHash   string             `json:"csrf_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type PriceVersion struct {
	ID           uuid.UUID          `json:"id"`
	SiteID       uuid.UUID          `json:"site_id"`
	GroupKey     string             `json:"group_key"`
	Version      int64              `json:"version"`
	SaleRatio    decimal.Decimal    `json:"sale_ratio"`
	Reason       string             `json:"reason"`
	Status       string             `json:"status"`
	BillingBasis []byte             `json:"billing_basis"`
	BasisHash    string             `json:"basis_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	PublishedAt  pgtype.Timestamptz `json:"published_at"`
	AppliedAt    pgtype.Timestamptz `json:"applied_at"`
	RoutePlanID  pgtype.UUID        `json:"route_plan_id"`
}

type RoutePlanVersion struct {
	ID             uuid.UUID          `json:"id"`
	SiteID         uuid.UUID          `json:"site_id"`
	SiteSupplierID uuid.UUID          `json:"site_supplier_id"`
	Version        int64              `json:"version"`
	PreviousPlanID pgtype.UUID        `json:"previous_plan_id"`
	Reason         string             `json:"reason"`
	Snapshot       []byte             `json:"snapshot"`
	ContentHash    string             `json:"content_hash"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ConfirmedAt    pgtype.Timestamptz `json:"confirmed_at"`
}

type Site struct {
	ID                  uuid.UUID          `json:"id"`
	Code                string             `json:"code"`
	Name                string             `json:"name"`
	NewApiBaseUrl       string             `json:"new_api_base_url"`
	AdminCredentialID   uuid.UUID          `json:"admin_credential_id"`
	Status              string             `json:"status"`
	CompatibilityStatus string             `json:"compatibility_status"`
	Version             int64              `json:"version"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	AdminUserID         int64              `json:"admin_user_id"`
}

type SiteStrategy struct {
	ID          uuid.UUID          `json:"id"`
	SiteID      uuid.UUID          `json:"site_id"`
	Kind        string             `json:"kind"`
	GroupKey    string             `json:"group_key"`
	DisplayName string             `json:"display_name"`
	Enabled     bool               `json:"enabled"`
	Visible     bool               `json:"visible"`
	Version     int64              `json:"version"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type SiteSupplier struct {
	ID               uuid.UUID          `json:"id"`
	SiteID           uuid.UUID          `json:"site_id"`
	SupplierID       uuid.UUID          `json:"supplier_id"`
	GroupKey         string             `json:"group_key"`
	GroupDisplayName string             `json:"group_display_name"`
	SaleRatio        decimal.Decimal    `json:"sale_ratio"`
	Visible          bool               `json:"visible"`
	DesiredStatus    string             `json:"desired_status"`
	SyncStatus       string             `json:"sync_status"`
	Version          int64              `json:"version"`
	CurrentPlanID    pgtype.UUID        `json:"current_plan_id"`
	LastConfirmedAt  pgtype.Timestamptz `json:"last_confirmed_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type SiteSupplierChannel struct {
	ID                             uuid.UUID          `json:"id"`
	SiteSupplierID                 uuid.UUID          `json:"site_supplier_id"`
	ManagedTag                     string             `json:"managed_tag"`
	ExternalChannelID              pgtype.Int8        `json:"external_channel_id"`
	LastConfirmedPlanVersion       pgtype.Int8        `json:"last_confirmed_plan_version"`
	CreatedAt                      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                      pgtype.Timestamptz `json:"updated_at"`
	LastConfirmedCredentialID      pgtype.UUID        `json:"last_confirmed_credential_id"`
	LastConfirmedCredentialVersion pgtype.Int4        `json:"last_confirmed_credential_version"`
	LastConfirmedEnabled           pgtype.Bool        `json:"last_confirmed_enabled"`
}

type StrategyMember struct {
	StrategyID uuid.UUID `json:"strategy_id"`
	RelationID uuid.UUID `json:"relation_id"`
}

type StrategyVersion struct {
	StrategyID uuid.UUID          `json:"strategy_id"`
	Version    int64              `json:"version"`
	Snapshot   []byte             `json:"snapshot"`
	Reason     string             `json:"reason"`
	ActorID    string             `json:"actor_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Supplier struct {
	ID                       uuid.UUID          `json:"id"`
	Code                     string             `json:"code"`
	Name                     string             `json:"name"`
	Protocol                 string             `json:"protocol"`
	UpstreamBaseUrl          string             `json:"upstream_base_url"`
	CredentialID             uuid.UUID          `json:"credential_id"`
	CredentialVersion        int32              `json:"credential_version"`
	Status                   string             `json:"status"`
	Version                  int64              `json:"version"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	PendingCredentialID      pgtype.UUID        `json:"pending_credential_id"`
	PendingCredentialVersion pgtype.Int4        `json:"pending_credential_version"`
}

type SupplierModel struct {
	SupplierID    uuid.UUID          `json:"supplier_id"`
	Model         string             `json:"model"`
	UpstreamModel string             `json:"upstream_model"`
	InputPrice    decimal.Decimal    `json:"input_price"`
	OutputPrice   decimal.Decimal    `json:"output_price"`
	Currency      string             `json:"currency"`
	Enabled       bool               `json:"enabled"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type SyncOperation struct {
	ID               uuid.UUID          `json:"id"`
	SiteID           uuid.UUID          `json:"site_id"`
	SiteSupplierID   uuid.UUID          `json:"site_supplier_id"`
	RoutePlanID      uuid.UUID          `json:"route_plan_id"`
	Status           string             `json:"status"`
	CurrentStep      pgtype.Text        `json:"current_step"`
	Attempt          int32              `json:"attempt"`
	LastErrorCode    pgtype.Text        `json:"last_error_code"`
	LastErrorMessage pgtype.Text        `json:"last_error_message"`
	NextAttemptAt    pgtype.Timestamptz `json:"next_attempt_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
}

type SyncStep struct {
	OperationID   uuid.UUID          `json:"operation_id"`
	StepKey       string             `json:"step_key"`
	Status        string             `json:"status"`
	BeforeSummary []byte             `json:"before_summary"`
	AfterSummary  []byte             `json:"after_summary"`
	ErrorCode     pgtype.Text        `json:"error_code"`
	ErrorMessage  pgtype.Text        `json:"error_message"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	FinishedAt    pgtype.Timestamptz `json:"finished_at"`
}
