// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: routing.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const bindExternalChannel = `-- name: BindExternalChannel :exec
UPDATE site_supplier_channels
SET external_channel_id = $2,
    updated_at = $3
WHERE id = $1
`

type BindExternalChannelParams struct {
	ID                uuid.UUID          `json:"id"`
	ExternalChannelID pgtype.Int8        `json:"external_channel_id"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) BindExternalChannel(ctx context.Context, arg BindExternalChannelParams) error {
	_, err := q.db.Exec(ctx, bindExternalChannel, arg.ID, arg.ExternalChannelID, arg.UpdatedAt)
	return err
}

const confirmChannelBinding = `-- name: ConfirmChannelBinding :exec
UPDATE site_supplier_channels
SET external_channel_id = $2,
    last_confirmed_plan_version = $3,
    updated_at = $4
WHERE id = $1
`

type ConfirmChannelBindingParams struct {
	ID                       uuid.UUID          `json:"id"`
	ExternalChannelID        pgtype.Int8        `json:"external_channel_id"`
	LastConfirmedPlanVersion pgtype.Int8        `json:"last_confirmed_plan_version"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ConfirmChannelBinding(ctx context.Context, arg ConfirmChannelBindingParams) error {
	_, err := q.db.Exec(ctx, confirmChannelBinding,
		arg.ID,
		arg.ExternalChannelID,
		arg.LastConfirmedPlanVersion,
		arg.UpdatedAt,
	)
	return err
}

const confirmRoutePlan = `-- name: ConfirmRoutePlan :exec
UPDATE route_plan_versions
SET status = 'confirmed', confirmed_at = $2
WHERE id = $1
`

type ConfirmRoutePlanParams struct {
	ID          uuid.UUID          `json:"id"`
	ConfirmedAt pgtype.Timestamptz `json:"confirmed_at"`
}

func (q *Queries) ConfirmRoutePlan(ctx context.Context, arg ConfirmRoutePlanParams) error {
	_, err := q.db.Exec(ctx, confirmRoutePlan, arg.ID, arg.ConfirmedAt)
	return err
}

const confirmSiteSupplier = `-- name: ConfirmSiteSupplier :exec
UPDATE site_suppliers
SET sync_status = 'active',
    desired_status = 'enabled',
    last_confirmed_at = $2,
    updated_at = $2,
    version = version + 1
WHERE id = $1
`

type ConfirmSiteSupplierParams struct {
	ID              uuid.UUID          `json:"id"`
	LastConfirmedAt pgtype.Timestamptz `json:"last_confirmed_at"`
}

func (q *Queries) ConfirmSiteSupplier(ctx context.Context, arg ConfirmSiteSupplierParams) error {
	_, err := q.db.Exec(ctx, confirmSiteSupplier, arg.ID, arg.LastConfirmedAt)
	return err
}

const createRoutePlan = `-- name: CreateRoutePlan :one
INSERT INTO route_plan_versions (
    id, site_id, site_supplier_id, version, previous_plan_id,
    reason, snapshot, content_hash, status, created_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10
)
RETURNING id, site_id, site_supplier_id, version, previous_plan_id, reason, snapshot, content_hash, status, created_at, confirmed_at
`

type CreateRoutePlanParams struct {
	ID             uuid.UUID          `json:"id"`
	SiteID         uuid.UUID          `json:"site_id"`
	SiteSupplierID uuid.UUID          `json:"site_supplier_id"`
	Version        int64              `json:"version"`
	PreviousPlanID pgtype.UUID        `json:"previous_plan_id"`
	Reason         string             `json:"reason"`
	Snapshot       []byte             `json:"snapshot"`
	ContentHash    string             `json:"content_hash"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateRoutePlan(ctx context.Context, arg CreateRoutePlanParams) (RoutePlanVersion, error) {
	row := q.db.QueryRow(ctx, createRoutePlan,
		arg.ID,
		arg.SiteID,
		arg.SiteSupplierID,
		arg.Version,
		arg.PreviousPlanID,
		arg.Reason,
		arg.Snapshot,
		arg.ContentHash,
		arg.Status,
		arg.CreatedAt,
	)
	var i RoutePlanVersion
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.SiteSupplierID,
		&i.Version,
		&i.PreviousPlanID,
		&i.Reason,
		&i.Snapshot,
		&i.ContentHash,
		&i.Status,
		&i.CreatedAt,
		&i.ConfirmedAt,
	)
	return i, err
}

const createSiteSupplier = `-- name: CreateSiteSupplier :one
INSERT INTO site_suppliers (
    id, site_id, supplier_id, group_key, group_display_name,
    sale_ratio, visible, desired_status, sync_status, version,
    created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    $11, $12
)
RETURNING id, site_id, supplier_id, group_key, group_display_name, sale_ratio, visible, desired_status, sync_status, version, current_plan_id, last_confirmed_at, created_at, updated_at
`

type CreateSiteSupplierParams struct {
	ID               uuid.UUID          `json:"id"`
	SiteID           uuid.UUID          `json:"site_id"`
	SupplierID       uuid.UUID          `json:"supplier_id"`
	GroupKey         string             `json:"group_key"`
	GroupDisplayName string             `json:"group_display_name"`
	SaleRatio        decimal.Decimal    `json:"sale_ratio"`
	Visible          bool               `json:"visible"`
	DesiredStatus    string             `json:"desired_status"`
	SyncStatus       string             `json:"sync_status"`
	Version          int64              `json:"version"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateSiteSupplier(ctx context.Context, arg CreateSiteSupplierParams) (SiteSupplier, error) {
	row := q.db.QueryRow(ctx, createSiteSupplier,
		arg.ID,
		arg.SiteID,
		arg.SupplierID,
		arg.GroupKey,
		arg.GroupDisplayName,
		arg.SaleRatio,
		arg.Visible,
		arg.DesiredStatus,
		arg.SyncStatus,
		arg.Version,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i SiteSupplier
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.SupplierID,
		&i.GroupKey,
		&i.GroupDisplayName,
		&i.SaleRatio,
		&i.Visible,
		&i.DesiredStatus,
		&i.SyncStatus,
		&i.Version,
		&i.CurrentPlanID,
		&i.LastConfirmedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSiteSupplierChannel = `-- name: CreateSiteSupplierChannel :one
INSERT INTO site_supplier_channels (
    id, site_supplier_id, managed_tag, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, site_supplier_id, managed_tag, external_channel_id, last_confirmed_plan_version, created_at, updated_at, last_confirmed_credential_id, last_confirmed_credential_version, last_confirmed_enabled
`

type CreateSiteSupplierChannelParams struct {
	ID             uuid.UUID          `json:"id"`
	SiteSupplierID uuid.UUID          `json:"site_supplier_id"`
	ManagedTag     string             `json:"managed_tag"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateSiteSupplierChannel(ctx context.Context, arg CreateSiteSupplierChannelParams) (SiteSupplierChannel, error) {
	row := q.db.QueryRow(ctx, createSiteSupplierChannel,
		arg.ID,
		arg.SiteSupplierID,
		arg.ManagedTag,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i SiteSupplierChannel
	err := row.Scan(
		&i.ID,
		&i.SiteSupplierID,
		&i.ManagedTag,
		&i.ExternalChannelID,
		&i.LastConfirmedPlanVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastConfirmedCredentialID,
		&i.LastConfirmedCredentialVersion,
		&i.LastConfirmedEnabled,
	)
	return i, err
}

const findRoutePlanByHash = `-- name: FindRoutePlanByHash :one
SELECT id, site_id, site_supplier_id, version, previous_plan_id, reason, snapshot, content_hash, status, created_at, confirmed_at
FROM route_plan_versions
WHERE site_id = $1 AND content_hash = $2
ORDER BY version DESC
LIMIT 1
`

type FindRoutePlanByHashParams struct {
	SiteID      uuid.UUID `json:"site_id"`
	ContentHash string    `json:"content_hash"`
}

func (q *Queries) FindRoutePlanByHash(ctx context.Context, arg FindRoutePlanByHashParams) (RoutePlanVersion, error) {
	row := q.db.QueryRow(ctx, findRoutePlanByHash, arg.SiteID, arg.ContentHash)
	var i RoutePlanVersion
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.SiteSupplierID,
		&i.Version,
		&i.PreviousPlanID,
		&i.Reason,
		&i.Snapshot,
		&i.ContentHash,
		&i.Status,
		&i.CreatedAt,
		&i.ConfirmedAt,
	)
	return i, err
}

const getCurrentRoutePlan = `-- name: GetCurrentRoutePlan :one
SELECT rp.id, rp.site_id, rp.site_supplier_id, rp.version, rp.previous_plan_id, rp.reason, rp.snapshot, rp.content_hash, rp.status, rp.created_at, rp.confirmed_at
FROM route_plan_versions rp
JOIN site_suppliers ss ON ss.current_plan_id = rp.id
WHERE ss.id = $1
`

func (q *Queries) GetCurrentRoutePlan(ctx context.Context, id uuid.UUID) (RoutePlanVersion, error) {
	row := q.db.QueryRow(ctx, getCurrentRoutePlan, id)
	var i RoutePlanVersion
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.SiteSupplierID,
		&i.Version,
		&i.PreviousPlanID,
		&i.Reason,
		&i.Snapshot,
		&i.ContentHash,
		&i.Status,
		&i.CreatedAt,
		&i.ConfirmedAt,
	)
	return i, err
}

const getMaxSitePlanVersion = `-- name: GetMaxSitePlanVersion :one
SELECT COALESCE(MAX(version), 0)::bigint AS max_version
FROM route_plan_versions
WHERE site_id = $1
`

func (q *Queries) GetMaxSitePlanVersion(ctx context.Context, siteID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getMaxSitePlanVersion, siteID)
	var max_version int64
	err := row.Scan(&max_version)
	return max_version, err
}

const getRoutePlan = `-- name: GetRoutePlan :one
SELECT id, site_id, site_supplier_id, version, previous_plan_id, reason, snapshot, content_hash, status, created_at, confirmed_at
FROM route_plan_versions
WHERE id = $1
`

func (q *Queries) GetRoutePlan(ctx context.Context, id uuid.UUID) (RoutePlanVersion, error) {
	row := q.db.QueryRow(ctx, getRoutePlan, id)
	var i RoutePlanVersion
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.SiteSupplierID,
		&i.Version,
		&i.PreviousPlanID,
		&i.Reason,
		&i.Snapshot,
		&i.ContentHash,
		&i.Status,
		&i.CreatedAt,
		&i.ConfirmedAt,
	)
	return i, err
}

const getSiteSupplier = `-- name: GetSiteSupplier :one
SELECT id, site_id, supplier_id, group_key, group_display_name, sale_ratio, visible, desired_status, sync_status, version, current_plan_id, last_confirmed_at, created_at, updated_at
FROM site_suppliers
WHERE id = $1
`

func (q *Queries) GetSiteSupplier(ctx context.Context, id uuid.UUID) (SiteSupplier, error) {
	row := q.db.QueryRow(ctx, getSiteSupplier, id)
	var i SiteSupplier
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.SupplierID,
		&i.GroupKey,
		&i.GroupDisplayName,
		&i.SaleRatio,
		&i.Visible,
		&i.DesiredStatus,
		&i.SyncStatus,
		&i.Version,
		&i.CurrentPlanID,
		&i.LastConfirmedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSiteSupplierChannel = `-- name: GetSiteSupplierChannel :one
SELECT id, site_supplier_id, managed_tag, external_channel_id, last_confirmed_plan_version, created_at, updated_at, last_confirmed_credential_id, last_confirmed_credential_version, last_confirmed_enabled
FROM site_supplier_channels
WHERE site_supplier_id = $1
ORDER BY created_at
LIMIT 1
`

func (q *Queries) GetSiteSupplierChannel(ctx context.Context, siteSupplierID uuid.UUID) (SiteSupplierChannel, error) {
	row := q.db.QueryRow(ctx, getSiteSupplierChannel, siteSupplierID)
	var i SiteSupplierChannel
	err := row.Scan(
		&i.ID,
		&i.SiteSupplierID,
		&i.ManagedTag,
		&i.ExternalChannelID,
		&i.LastConfirmedPlanVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastConfirmedCredentialID,
		&i.LastConfirmedCredentialVersion,
		&i.LastConfirmedEnabled,
	)
	return i, err
}

const getSiteSupplierDetails = `-- name: GetSiteSupplierDetails :one
SELECT
    ss.id,
    ss.site_id,
    ss.supplier_id,
    ss.group_key,
    ss.group_display_name,
    ss.sale_ratio,
    ss.visible,
    ss.desired_status,
    ss.sync_status,
    ss.version,
    ss.current_plan_id,
    ss.last_confirmed_at,
    ss.created_at,
    ss.updated_at,
    COALESCE(rp.version, 0)::bigint AS route_plan_version
FROM site_suppliers ss
LEFT JOIN route_plan_versions rp ON rp.id = ss.current_plan_id
WHERE ss.id = $1
`

type GetSiteSupplierDetailsRow struct {
	ID               uuid.UUID          `json:"id"`
	SiteID           uuid.UUID          `json:"site_id"`
	SupplierID       uuid.UUID          `json:"supplier_id"`
	GroupKey         string             `json:"group_key"`
	GroupDisplayName string             `json:"group_display_name"`
	SaleRatio        decimal.Decimal    `json:"sale_ratio"`
	Visible          bool               `json:"visible"`
	DesiredStatus    string             `json:"desired_status"`
	SyncStatus       string             `json:"sync_status"`
	Version          int64              `json:"version"`
	CurrentPlanID    pgtype.UUID        `json:"current_plan_id"`
	LastConfirmedAt  pgtype.Timestamptz `json:"last_confirmed_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	RoutePlanVersion int64              `json:"route_plan_version"`
}

func (q *Queries) GetSiteSupplierDetails(ctx context.Context, id uuid.UUID) (GetSiteSupplierDetailsRow, error) {
	row := q.db.QueryRow(ctx, getSiteSupplierDetails, id)
	var i GetSiteSupplierDetailsRow
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.SupplierID,
		&i.GroupKey,
		&i.GroupDisplayName,
		&i.SaleRatio,
		&i.Visible,
		&i.DesiredStatus,
		&i.SyncStatus,
		&i.Version,
		&i.CurrentPlanID,
		&i.LastConfirmedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RoutePlanVersion,
	)
	return i, err
}

const lockSitePlanVersion = `-- name: LockSitePlanVersion :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text, 0))
`

func (q *Queries) LockSitePlanVersion(ctx context.Context, dollar_1 string) error {
	_, err := q.db.Exec(ctx, lockSitePlanVersion, dollar_1)
	return err
}

const setCurrentRoutePlan = `-- name: SetCurrentRoutePlan :exec
UPDATE site_suppliers
SET current_plan_id = $2,
    sync_status = 'pending',
    updated_at = $3,
    version = version + 1
WHERE id = $1
`

type SetCurrentRoutePlanParams struct {
	ID            uuid.UUID          `json:"id"`
	CurrentPlanID pgtype.UUID        `json:"current_plan_id"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) SetCurrentRoutePlan(ctx context.Context, arg SetCurrentRoutePlanParams) error {
	_, err := q.db.Exec(ctx, setCurrentRoutePlan, arg.ID, arg.CurrentPlanID, arg.UpdatedAt)
	return err
}

const setRoutePlanApplying = `-- name: SetRoutePlanApplying :exec
UPDATE route_plan_versions
SET status = 'applying'
WHERE id = $1 AND status IN ('pending', 'failed', 'uncertain')
`

func (q *Queries) SetRoutePlanApplying(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setRoutePlanApplying, id)
	return err
}

const setRoutePlanFailed = `-- name: SetRoutePlanFailed :exec
UPDATE route_plan_versions
SET status = $2
WHERE id = $1
`

type SetRoutePlanFailedParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) SetRoutePlanFailed(ctx context.Context, arg SetRoutePlanFailedParams) error {
	_, err := q.db.Exec(ctx, setRoutePlanFailed, arg.ID, arg.Status)
	return err
}

const setSiteSupplierSyncFailure = `-- name: SetSiteSupplierSyncFailure :exec
UPDATE site_suppliers
SET sync_status = $2, updated_at = $3
WHERE id = $1
`

type SetSiteSupplierSyncFailureParams struct {
	ID         uuid.UUID          `json:"id"`
	SyncStatus string             `json:"sync_status"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) SetSiteSupplierSyncFailure(ctx context.Context, arg SetSiteSupplierSyncFailureParams) error {
	_, err := q.db.Exec(ctx, setSiteSupplierSyncFailure, arg.ID, arg.SyncStatus, arg.UpdatedAt)
	return err
}

const setSiteSupplierSyncing = `-- name: SetSiteSupplierSyncing :exec
UPDATE site_suppliers
SET sync_status = 'syncing', updated_at = $2
WHERE id = $1
`

type SetSiteSupplierSyncingParams struct {
	ID        uuid.UUID          `json:"id"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) SetSiteSupplierSyncing(ctx context.Context, arg SetSiteSupplierSyncingParams) error {
	_, err := q.db.Exec(ctx, setSiteSupplierSyncing, arg.ID, arg.UpdatedAt)
	return err
}
