// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scoring.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const aggregateAttemptHistogramsRange = `-- name: AggregateAttemptHistogramsRange :exec
INSERT INTO attempt_latency_histograms_1m (
    bucket_start, site_id, supplier_id, model, source, metric, upper_bound_ms, sample_count
)
SELECT
    date_trunc('minute', attempt.observed_at), request.site_id, attempt.supplier_id,
    attempt.model, request.source, latency.metric,
    CASE
        WHEN latency.value_ms <= 50 THEN 50 WHEN latency.value_ms <= 100 THEN 100
        WHEN latency.value_ms <= 250 THEN 250 WHEN latency.value_ms <= 500 THEN 500
        WHEN latency.value_ms <= 1000 THEN 1000 WHEN latency.value_ms <= 2000 THEN 2000
        WHEN latency.value_ms <= 3000 THEN 3000 WHEN latency.value_ms <= 5000 THEN 5000
        WHEN latency.value_ms <= 8000 THEN 8000 WHEN latency.value_ms <= 10000 THEN 10000
        WHEN latency.value_ms <= 15000 THEN 15000 WHEN latency.value_ms <= 30000 THEN 30000
        WHEN latency.value_ms <= 60000 THEN 60000 WHEN latency.value_ms <= 120000 THEN 120000
        WHEN latency.value_ms <= 300000 THEN 300000 WHEN latency.value_ms <= 600000 THEN 600000
        ELSE 9223372036854775807
    END,
    COUNT(*)
FROM measurement_attempts attempt
JOIN measurement_requests request ON request.id = attempt.request_measurement_id
CROSS JOIN LATERAL (
    VALUES
        ('ttft'::text, attempt.ttft_ms),
        ('duration_success'::text, CASE WHEN attempt.outcome = 'succeeded' THEN attempt.duration_ms END),
        ('duration_failure'::text, CASE WHEN attempt.outcome <> 'succeeded' THEN attempt.duration_ms END)
) latency(metric, value_ms)
WHERE request.site_id IS NOT NULL
  AND request.is_current
  AND attempt.supplier_id IS NOT NULL
  AND attempt.observed_at >= $1 AND attempt.observed_at < $2
  AND latency.value_ms IS NOT NULL AND latency.value_ms >= 0
GROUP BY 1, 2, 3, 4, 5, 6, 7
`

type AggregateAttemptHistogramsRangeParams struct {
	ObservedAt   pgtype.Timestamptz `json:"observed_at"`
	ObservedAt_2 pgtype.Timestamptz `json:"observed_at_2"`
}

func (q *Queries) AggregateAttemptHistogramsRange(ctx context.Context, arg AggregateAttemptHistogramsRangeParams) error {
	_, err := q.db.Exec(ctx, aggregateAttemptHistogramsRange, arg.ObservedAt, arg.ObservedAt_2)
	return err
}

const aggregateAttemptMetricsRange = `-- name: AggregateAttemptMetricsRange :exec
INSERT INTO attempt_metrics_1m (
    bucket_start, site_id, supplier_id, model, source,
    attempt_count, sla_attempt_count, success_count, failure_count, sla_failure_count, rate_limited_count,
    authentication_count, balance_count, timeout_count, transport_count,
    upstream_count, stream_count, stream_completed_count,
    ttft_sum_ms, ttft_count, success_duration_sum_ms, success_duration_count,
    failure_duration_sum_ms, failure_duration_count, coarse_duration_count, computed_at
)
SELECT
    date_trunc('minute', attempt.observed_at), request.site_id, attempt.supplier_id,
    attempt.model, request.source,
    COUNT(*),
    COUNT(*) FILTER (WHERE attempt.outcome = 'succeeded' OR attempt.error_responsibility = 'supplier'),
    COUNT(*) FILTER (WHERE attempt.outcome = 'succeeded'),
    COUNT(*) FILTER (WHERE attempt.outcome <> 'succeeded'),
    COUNT(*) FILTER (WHERE attempt.outcome <> 'succeeded' AND attempt.error_responsibility = 'supplier'),
    COUNT(*) FILTER (WHERE attempt.error_category = 'rate_limited' AND attempt.error_responsibility = 'supplier'),
    COUNT(*) FILTER (WHERE attempt.error_category = 'authentication' AND attempt.error_responsibility = 'supplier'),
    COUNT(*) FILTER (WHERE attempt.error_category = 'balance_exhausted' AND attempt.error_responsibility = 'supplier'),
    COUNT(*) FILTER (WHERE attempt.error_category = 'timeout' AND attempt.error_responsibility = 'supplier'),
    COUNT(*) FILTER (WHERE attempt.error_category = 'stream_incomplete' AND attempt.error_responsibility = 'supplier'),
    COUNT(*) FILTER (WHERE attempt.error_category IN ('upstream_unavailable', 'unknown') AND attempt.error_responsibility = 'supplier'),
    COUNT(*) FILTER (WHERE attempt.is_stream AND attempt.produced_visible_output),
    COUNT(*) FILTER (WHERE attempt.is_stream AND attempt.produced_visible_output AND attempt.stream_completed IS TRUE),
    COALESCE(SUM(attempt.ttft_ms) FILTER (WHERE attempt.ttft_ms IS NOT NULL), 0),
    COUNT(attempt.ttft_ms),
    COALESCE(SUM(attempt.duration_ms) FILTER (WHERE attempt.duration_ms IS NOT NULL AND attempt.outcome = 'succeeded'), 0),
    COUNT(attempt.duration_ms) FILTER (WHERE attempt.outcome = 'succeeded'),
    COALESCE(SUM(attempt.duration_ms) FILTER (WHERE attempt.duration_ms IS NOT NULL AND attempt.outcome <> 'succeeded'), 0),
    COUNT(attempt.duration_ms) FILTER (WHERE attempt.outcome <> 'succeeded'),
    COUNT(attempt.duration_ms) FILTER (WHERE attempt.duration_resolution_ms > 1),
    $3
FROM measurement_attempts attempt
JOIN measurement_requests request ON request.id = attempt.request_measurement_id
WHERE request.site_id IS NOT NULL
  AND request.is_current
  AND attempt.supplier_id IS NOT NULL
  AND attempt.observed_at >= $1 AND attempt.observed_at < $2
GROUP BY 1, 2, 3, 4, 5
`

type AggregateAttemptMetricsRangeParams struct {
	ObservedAt   pgtype.Timestamptz `json:"observed_at"`
	ObservedAt_2 pgtype.Timestamptz `json:"observed_at_2"`
	ComputedAt   pgtype.Timestamptz `json:"computed_at"`
}

func (q *Queries) AggregateAttemptMetricsRange(ctx context.Context, arg AggregateAttemptMetricsRangeParams) error {
	_, err := q.db.Exec(ctx, aggregateAttemptMetricsRange, arg.ObservedAt, arg.ObservedAt_2, arg.ComputedAt)
	return err
}

const aggregateRequestHistogramsRange = `-- name: AggregateRequestHistogramsRange :exec
INSERT INTO request_latency_histograms_1m (
    bucket_start, site_id, model, source, metric, upper_bound_ms, sample_count
)
SELECT
    date_trunc('minute', request.observed_at), request.site_id, request.model, request.source,
    latency.metric,
    CASE
        WHEN latency.value_ms <= 50 THEN 50 WHEN latency.value_ms <= 100 THEN 100
        WHEN latency.value_ms <= 250 THEN 250 WHEN latency.value_ms <= 500 THEN 500
        WHEN latency.value_ms <= 1000 THEN 1000 WHEN latency.value_ms <= 2000 THEN 2000
        WHEN latency.value_ms <= 3000 THEN 3000 WHEN latency.value_ms <= 5000 THEN 5000
        WHEN latency.value_ms <= 8000 THEN 8000 WHEN latency.value_ms <= 10000 THEN 10000
        WHEN latency.value_ms <= 15000 THEN 15000 WHEN latency.value_ms <= 30000 THEN 30000
        WHEN latency.value_ms <= 60000 THEN 60000 WHEN latency.value_ms <= 120000 THEN 120000
        WHEN latency.value_ms <= 300000 THEN 300000 WHEN latency.value_ms <= 600000 THEN 600000
        ELSE 9223372036854775807
    END,
    COUNT(*)
FROM measurement_requests request
CROSS JOIN LATERAL (
    VALUES
        ('ttft'::text, request.ttft_ms),
        ('duration_success'::text, CASE WHEN request.outcome = 'succeeded' THEN request.duration_ms END),
        ('duration_failure'::text, CASE WHEN request.outcome <> 'succeeded' THEN request.duration_ms END)
) latency(metric, value_ms)
WHERE request.site_id IS NOT NULL
  AND request.is_current
  AND request.observed_at >= $1 AND request.observed_at < $2
  AND latency.value_ms IS NOT NULL AND latency.value_ms >= 0
GROUP BY 1, 2, 3, 4, 5, 6
`

type AggregateRequestHistogramsRangeParams struct {
	ObservedAt   pgtype.Timestamptz `json:"observed_at"`
	ObservedAt_2 pgtype.Timestamptz `json:"observed_at_2"`
}

func (q *Queries) AggregateRequestHistogramsRange(ctx context.Context, arg AggregateRequestHistogramsRangeParams) error {
	_, err := q.db.Exec(ctx, aggregateRequestHistogramsRange, arg.ObservedAt, arg.ObservedAt_2)
	return err
}

const aggregateRequestMetricsRange = `-- name: AggregateRequestMetricsRange :exec
INSERT INTO request_metrics_1m (
    bucket_start, site_id, model, source, request_count, success_count,
    failure_count, mapped_count, stream_count, stream_completed_count,
    input_tokens, output_tokens, ttft_sum_ms, ttft_count,
    success_duration_sum_ms, success_duration_count,
    failure_duration_sum_ms, failure_duration_count, coarse_duration_count, computed_at
)
SELECT
    date_trunc('minute', observed_at), site_id, model, source,
    COUNT(*),
    COUNT(*) FILTER (WHERE outcome = 'succeeded'),
    COUNT(*) FILTER (WHERE outcome <> 'succeeded'),
    COUNT(*) FILTER (WHERE attribution_status = 'mapped'),
    COUNT(*) FILTER (WHERE is_stream AND ttft_ms IS NOT NULL),
    COUNT(*) FILTER (WHERE is_stream AND ttft_ms IS NOT NULL AND stream_completed IS TRUE),
    COALESCE(SUM(input_tokens), 0),
    COALESCE(SUM(output_tokens), 0),
    COALESCE(SUM(ttft_ms) FILTER (WHERE ttft_ms IS NOT NULL), 0),
    COUNT(ttft_ms),
    COALESCE(SUM(duration_ms) FILTER (WHERE duration_ms IS NOT NULL AND outcome = 'succeeded'), 0),
    COUNT(duration_ms) FILTER (WHERE outcome = 'succeeded'),
    COALESCE(SUM(duration_ms) FILTER (WHERE duration_ms IS NOT NULL AND outcome <> 'succeeded'), 0),
    COUNT(duration_ms) FILTER (WHERE outcome <> 'succeeded'),
    COUNT(duration_ms) FILTER (WHERE duration_resolution_ms > 1),
    $3
FROM measurement_requests
WHERE site_id IS NOT NULL AND is_current AND observed_at >= $1 AND observed_at < $2
GROUP BY 1, 2, 3, 4
`

type AggregateRequestMetricsRangeParams struct {
	ObservedAt   pgtype.Timestamptz `json:"observed_at"`
	ObservedAt_2 pgtype.Timestamptz `json:"observed_at_2"`
	ComputedAt   pgtype.Timestamptz `json:"computed_at"`
}

func (q *Queries) AggregateRequestMetricsRange(ctx context.Context, arg AggregateRequestMetricsRangeParams) error {
	_, err := q.db.Exec(ctx, aggregateRequestMetricsRange, arg.ObservedAt, arg.ObservedAt_2, arg.ComputedAt)
	return err
}

const countPendingAttribution = `-- name: CountPendingAttribution :one
SELECT COUNT(*)::bigint
FROM measurement_attempts attempt
JOIN measurement_requests request ON request.id = attempt.request_measurement_id
WHERE request.site_id = $1
  AND request.is_current
  AND attempt.model = $2
  AND request.source = 'real_traffic'
  AND (
      attempt.attribution_status = 'pending'
      OR (attempt.outcome <> 'succeeded' AND attempt.error_responsibility = 'unknown')
  )
  AND attempt.observed_at >= $3 AND attempt.observed_at < $4
`

type CountPendingAttributionParams struct {
	SiteID       pgtype.UUID        `json:"site_id"`
	Model        string             `json:"model"`
	ObservedAt   pgtype.Timestamptz `json:"observed_at"`
	ObservedAt_2 pgtype.Timestamptz `json:"observed_at_2"`
}

func (q *Queries) CountPendingAttribution(ctx context.Context, arg CountPendingAttributionParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingAttribution,
		arg.SiteID,
		arg.Model,
		arg.ObservedAt,
		arg.ObservedAt_2,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createScoreSnapshot = `-- name: CreateScoreSnapshot :exec
INSERT INTO score_snapshots (
    id, site_id, supplier_id, model, policy_version, window_start, window_end,
    facts_through, passive_samples, active_samples, price_score, latency_score,
    sla_score, quality_score, total_score, confidence, eligibility,
    hard_reasons, explanation, authenticity_assessment_id,
    capability_assessment_id, score_run_id, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12,
    $13, $14, $15, $16, $17,
    $18, $19, $20,
    $21, $22, $23
)
ON CONFLICT (site_id, supplier_id, model, policy_version, window_end) DO NOTHING
`

type CreateScoreSnapshotParams struct {
	ID                       uuid.UUID          `json:"id"`
	SiteID                   uuid.UUID          `json:"site_id"`
	SupplierID               uuid.UUID          `json:"supplier_id"`
	Model                    string             `json:"model"`
	PolicyVersion            string             `json:"policy_version"`
	WindowStart              pgtype.Timestamptz `json:"window_start"`
	WindowEnd                pgtype.Timestamptz `json:"window_end"`
	FactsThrough             pgtype.Timestamptz `json:"facts_through"`
	PassiveSamples           int64              `json:"passive_samples"`
	ActiveSamples            int64              `json:"active_samples"`
	PriceScore               pgtype.Numeric     `json:"price_score"`
	LatencyScore             pgtype.Numeric     `json:"latency_score"`
	SlaScore                 pgtype.Numeric     `json:"sla_score"`
	QualityScore             pgtype.Numeric     `json:"quality_score"`
	TotalScore               pgtype.Numeric     `json:"total_score"`
	Confidence               string             `json:"confidence"`
	Eligibility              string             `json:"eligibility"`
	HardReasons              []byte             `json:"hard_reasons"`
	Explanation              []byte             `json:"explanation"`
	AuthenticityAssessmentID pgtype.UUID        `json:"authenticity_assessment_id"`
	CapabilityAssessmentID   pgtype.UUID        `json:"capability_assessment_id"`
	ScoreRunID               pgtype.UUID        `json:"score_run_id"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateScoreSnapshot(ctx context.Context, arg CreateScoreSnapshotParams) error {
	_, err := q.db.Exec(ctx, createScoreSnapshot,
		arg.ID,
		arg.SiteID,
		arg.SupplierID,
		arg.Model,
		arg.PolicyVersion,
		arg.WindowStart,
		arg.WindowEnd,
		arg.FactsThrough,
		arg.PassiveSamples,
		arg.ActiveSamples,
		arg.PriceScore,
		arg.LatencyScore,
		arg.SlaScore,
		arg.QualityScore,
		arg.TotalScore,
		arg.Confidence,
		arg.Eligibility,
		arg.HardReasons,
		arg.Explanation,
		arg.AuthenticityAssessmentID,
		arg.CapabilityAssessmentID,
		arg.ScoreRunID,
		arg.CreatedAt,
	)
	return err
}

const createShadowRecommendation = `-- name: CreateShadowRecommendation :exec
INSERT INTO shadow_recommendations (
    id, score_snapshot_id, site_id, supplier_id, model, strategy_kind,
    action, current_member, score, confidence, reasons, created_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (score_snapshot_id, strategy_kind) DO NOTHING
`

type CreateShadowRecommendationParams struct {
	ID              uuid.UUID          `json:"id"`
	ScoreSnapshotID uuid.UUID          `json:"score_snapshot_id"`
	SiteID          uuid.UUID          `json:"site_id"`
	SupplierID      uuid.UUID          `json:"supplier_id"`
	Model           string             `json:"model"`
	StrategyKind    string             `json:"strategy_kind"`
	Action          string             `json:"action"`
	CurrentMember   bool               `json:"current_member"`
	Score           pgtype.Numeric     `json:"score"`
	Confidence      string             `json:"confidence"`
	Reasons         []byte             `json:"reasons"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateShadowRecommendation(ctx context.Context, arg CreateShadowRecommendationParams) error {
	_, err := q.db.Exec(ctx, createShadowRecommendation,
		arg.ID,
		arg.ScoreSnapshotID,
		arg.SiteID,
		arg.SupplierID,
		arg.Model,
		arg.StrategyKind,
		arg.Action,
		arg.CurrentMember,
		arg.Score,
		arg.Confidence,
		arg.Reasons,
		arg.CreatedAt,
	)
	return err
}

const deleteAttemptHistogramsRange = `-- name: DeleteAttemptHistogramsRange :exec
DELETE FROM attempt_latency_histograms_1m
WHERE bucket_start >= $1 AND bucket_start < $2
`

type DeleteAttemptHistogramsRangeParams struct {
	BucketStart   pgtype.Timestamptz `json:"bucket_start"`
	BucketStart_2 pgtype.Timestamptz `json:"bucket_start_2"`
}

func (q *Queries) DeleteAttemptHistogramsRange(ctx context.Context, arg DeleteAttemptHistogramsRangeParams) error {
	_, err := q.db.Exec(ctx, deleteAttemptHistogramsRange, arg.BucketStart, arg.BucketStart_2)
	return err
}

const deleteAttemptMetricsRange = `-- name: DeleteAttemptMetricsRange :exec
DELETE FROM attempt_metrics_1m
WHERE bucket_start >= $1 AND bucket_start < $2
`

type DeleteAttemptMetricsRangeParams struct {
	BucketStart   pgtype.Timestamptz `json:"bucket_start"`
	BucketStart_2 pgtype.Timestamptz `json:"bucket_start_2"`
}

func (q *Queries) DeleteAttemptMetricsRange(ctx context.Context, arg DeleteAttemptMetricsRangeParams) error {
	_, err := q.db.Exec(ctx, deleteAttemptMetricsRange, arg.BucketStart, arg.BucketStart_2)
	return err
}

const deleteRequestHistogramsRange = `-- name: DeleteRequestHistogramsRange :exec
DELETE FROM request_latency_histograms_1m
WHERE bucket_start >= $1 AND bucket_start < $2
`

type DeleteRequestHistogramsRangeParams struct {
	BucketStart   pgtype.Timestamptz `json:"bucket_start"`
	BucketStart_2 pgtype.Timestamptz `json:"bucket_start_2"`
}

func (q *Queries) DeleteRequestHistogramsRange(ctx context.Context, arg DeleteRequestHistogramsRangeParams) error {
	_, err := q.db.Exec(ctx, deleteRequestHistogramsRange, arg.BucketStart, arg.BucketStart_2)
	return err
}

const deleteRequestMetricsRange = `-- name: DeleteRequestMetricsRange :exec
DELETE FROM request_metrics_1m
WHERE bucket_start >= $1 AND bucket_start < $2
`

type DeleteRequestMetricsRangeParams struct {
	BucketStart   pgtype.Timestamptz `json:"bucket_start"`
	BucketStart_2 pgtype.Timestamptz `json:"bucket_start_2"`
}

func (q *Queries) DeleteRequestMetricsRange(ctx context.Context, arg DeleteRequestMetricsRangeParams) error {
	_, err := q.db.Exec(ctx, deleteRequestMetricsRange, arg.BucketStart, arg.BucketStart_2)
	return err
}

const findPreviousShadowRecommendation = `-- name: FindPreviousShadowRecommendation :one
SELECT recommendation.id, recommendation.score_snapshot_id, recommendation.site_id, recommendation.supplier_id, recommendation.model, recommendation.strategy_kind, recommendation.action, recommendation.current_member, recommendation.score, recommendation.confidence, recommendation.reasons, recommendation.created_at
FROM shadow_recommendations recommendation
JOIN score_snapshots snapshot ON snapshot.id = recommendation.score_snapshot_id
WHERE recommendation.site_id = $1
  AND recommendation.supplier_id = $2
  AND recommendation.model = $3
  AND recommendation.strategy_kind = $4
  AND recommendation.created_at < $5
  AND snapshot.policy_version = $6
ORDER BY recommendation.created_at DESC, recommendation.id DESC
LIMIT 1
`

type FindPreviousShadowRecommendationParams struct {
	SiteID        uuid.UUID          `json:"site_id"`
	SupplierID    uuid.UUID          `json:"supplier_id"`
	Model         string             `json:"model"`
	StrategyKind  string             `json:"strategy_kind"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	PolicyVersion string             `json:"policy_version"`
}

func (q *Queries) FindPreviousShadowRecommendation(ctx context.Context, arg FindPreviousShadowRecommendationParams) (ShadowRecommendation, error) {
	row := q.db.QueryRow(ctx, findPreviousShadowRecommendation,
		arg.SiteID,
		arg.SupplierID,
		arg.Model,
		arg.StrategyKind,
		arg.CreatedAt,
		arg.PolicyVersion,
	)
	var i ShadowRecommendation
	err := row.Scan(
		&i.ID,
		&i.ScoreSnapshotID,
		&i.SiteID,
		&i.SupplierID,
		&i.Model,
		&i.StrategyKind,
		&i.Action,
		&i.CurrentMember,
		&i.Score,
		&i.Confidence,
		&i.Reasons,
		&i.CreatedAt,
	)
	return i, err
}

const getAttemptLatencyHistogram = `-- name: GetAttemptLatencyHistogram :many
SELECT upper_bound_ms, COALESCE(SUM(sample_count), 0)::bigint AS sample_count
FROM attempt_latency_histograms_1m
WHERE site_id = $1 AND supplier_id = $2 AND model = $3 AND source = $4
  AND metric = $5 AND bucket_start >= $6 AND bucket_start < $7
GROUP BY upper_bound_ms
ORDER BY upper_bound_ms
`

type GetAttemptLatencyHistogramParams struct {
	SiteID        uuid.UUID          `json:"site_id"`
	SupplierID    uuid.UUID          `json:"supplier_id"`
	Model         string             `json:"model"`
	Source        string             `json:"source"`
	Metric        string             `json:"metric"`
	BucketStart   pgtype.Timestamptz `json:"bucket_start"`
	BucketStart_2 pgtype.Timestamptz `json:"bucket_start_2"`
}

type GetAttemptLatencyHistogramRow struct {
	UpperBoundMs int64 `json:"upper_bound_ms"`
	SampleCount  int64 `json:"sample_count"`
}

func (q *Queries) GetAttemptLatencyHistogram(ctx context.Context, arg GetAttemptLatencyHistogramParams) ([]GetAttemptLatencyHistogramRow, error) {
	rows, err := q.db.Query(ctx, getAttemptLatencyHistogram,
		arg.SiteID,
		arg.SupplierID,
		arg.Model,
		arg.Source,
		arg.Metric,
		arg.BucketStart,
		arg.BucketStart_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAttemptLatencyHistogramRow{}
	for rows.Next() {
		var i GetAttemptLatencyHistogramRow
		if err := rows.Scan(&i.UpperBoundMs, &i.SampleCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAttemptWindowMetrics = `-- name: GetAttemptWindowMetrics :one
SELECT
    COALESCE(SUM(attempt_count), 0)::bigint AS attempt_count,
    COALESCE(SUM(sla_attempt_count), 0)::bigint AS sla_attempt_count,
    COALESCE(SUM(success_count), 0)::bigint AS success_count,
    COALESCE(SUM(failure_count), 0)::bigint AS failure_count,
    COALESCE(SUM(sla_failure_count), 0)::bigint AS sla_failure_count,
    COALESCE(SUM(rate_limited_count), 0)::bigint AS rate_limited_count,
    COALESCE(SUM(authentication_count), 0)::bigint AS authentication_count,
    COALESCE(SUM(balance_count), 0)::bigint AS balance_count,
    COALESCE(SUM(timeout_count), 0)::bigint AS timeout_count,
    COALESCE(SUM(transport_count), 0)::bigint AS transport_count,
    COALESCE(SUM(upstream_count), 0)::bigint AS upstream_count,
    COALESCE(SUM(stream_count), 0)::bigint AS stream_count,
    COALESCE(SUM(stream_completed_count), 0)::bigint AS stream_completed_count,
    COALESCE(SUM(ttft_sum_ms), 0)::bigint AS ttft_sum_ms,
    COALESCE(SUM(ttft_count), 0)::bigint AS ttft_count,
    COALESCE(SUM(success_duration_sum_ms), 0)::bigint AS success_duration_sum_ms,
    COALESCE(SUM(success_duration_count), 0)::bigint AS success_duration_count,
    COALESCE(SUM(failure_duration_sum_ms), 0)::bigint AS failure_duration_sum_ms,
    COALESCE(SUM(failure_duration_count), 0)::bigint AS failure_duration_count,
    COALESCE(SUM(coarse_duration_count), 0)::bigint AS coarse_duration_count,
    COALESCE(MAX(bucket_start), '-infinity'::timestamptz)::timestamptz AS facts_through
FROM attempt_metrics_1m
WHERE site_id = $1 AND supplier_id = $2 AND model = $3 AND source = $4
  AND bucket_start >= $5 AND bucket_start < $6
`

type GetAttemptWindowMetricsParams struct {
	SiteID        uuid.UUID          `json:"site_id"`
	SupplierID    uuid.UUID          `json:"supplier_id"`
	Model         string             `json:"model"`
	Source        string             `json:"source"`
	BucketStart   pgtype.Timestamptz `json:"bucket_start"`
	BucketStart_2 pgtype.Timestamptz `json:"bucket_start_2"`
}

type GetAttemptWindowMetricsRow struct {
	AttemptCount         int64              `json:"attempt_count"`
	SlaAttemptCount      int64              `json:"sla_attempt_count"`
	SuccessCount         int64              `json:"success_count"`
	FailureCount         int64              `json:"failure_count"`
	SlaFailureCount      int64              `json:"sla_failure_count"`
	RateLimitedCount     int64              `json:"rate_limited_count"`
	AuthenticationCount  int64              `json:"authentication_count"`
	BalanceCount         int64              `json:"balance_count"`
	TimeoutCount         int64              `json:"timeout_count"`
	TransportCount       int64              `json:"transport_count"`
	UpstreamCount        int64              `json:"upstream_count"`
	StreamCount          int64              `json:"stream_count"`
	StreamCompletedCount int64              `json:"stream_completed_count"`
	TtftSumMs            int64              `json:"ttft_sum_ms"`
	TtftCount            int64              `json:"ttft_count"`
	SuccessDurationSumMs int64              `json:"success_duration_sum_ms"`
	SuccessDurationCount int64              `json:"success_duration_count"`
	FailureDurationSumMs int64              `json:"failure_duration_sum_ms"`
	FailureDurationCount int64              `json:"failure_duration_count"`
	CoarseDurationCount  int64              `json:"coarse_duration_count"`
	FactsThrough         pgtype.Timestamptz `json:"facts_through"`
}

func (q *Queries) GetAttemptWindowMetrics(ctx context.Context, arg GetAttemptWindowMetricsParams) (GetAttemptWindowMetricsRow, error) {
	row := q.db.QueryRow(ctx, getAttemptWindowMetrics,
		arg.SiteID,
		arg.SupplierID,
		arg.Model,
		arg.Source,
		arg.BucketStart,
		arg.BucketStart_2,
	)
	var i GetAttemptWindowMetricsRow
	err := row.Scan(
		&i.AttemptCount,
		&i.SlaAttemptCount,
		&i.SuccessCount,
		&i.FailureCount,
		&i.SlaFailureCount,
		&i.RateLimitedCount,
		&i.AuthenticationCount,
		&i.BalanceCount,
		&i.TimeoutCount,
		&i.TransportCount,
		&i.UpstreamCount,
		&i.StreamCount,
		&i.StreamCompletedCount,
		&i.TtftSumMs,
		&i.TtftCount,
		&i.SuccessDurationSumMs,
		&i.SuccessDurationCount,
		&i.FailureDurationSumMs,
		&i.FailureDurationCount,
		&i.CoarseDurationCount,
		&i.FactsThrough,
	)
	return i, err
}

const getFailureStreak = `-- name: GetFailureStreak :one
WITH request_outcomes AS (
    SELECT
        request.id,
        BOOL_OR(attempt.outcome = 'succeeded') AS succeeded,
        MAX(attempt.observed_at) FILTER (WHERE attempt.outcome = 'succeeded') AS succeeded_at,
        MAX(attempt.observed_at) FILTER (
            WHERE attempt.outcome <> 'succeeded'
              AND attempt.error_responsibility = 'supplier'
        ) AS failed_at,
        BOOL_OR(
            attempt.outcome <> 'succeeded'
            AND attempt.error_category = 'authentication'
            AND attempt.error_responsibility = 'supplier'
        ) AS authentication,
        BOOL_OR(
            attempt.outcome <> 'succeeded'
            AND attempt.error_category = 'balance_exhausted'
            AND attempt.error_responsibility = 'supplier'
        ) AS balance
    FROM measurement_attempts attempt
    JOIN measurement_requests request ON request.id = attempt.request_measurement_id
    WHERE request.site_id = $1
      AND request.is_current
      AND request.source = 'real_traffic'
      AND attempt.supplier_id = $2
      AND attempt.model = $3
      AND attempt.observed_at < $4
    GROUP BY request.id
    HAVING BOOL_OR(attempt.outcome = 'succeeded')
        OR BOOL_OR(
            attempt.outcome <> 'succeeded'
            AND attempt.error_responsibility = 'supplier'
        )
), last_success AS (
    SELECT MAX(candidate.succeeded_at) AS succeeded_at
    FROM (
        SELECT MAX(succeeded_at) AS succeeded_at
        FROM request_outcomes
        WHERE succeeded

        UNION ALL

        SELECT MAX(attempt.observed_at) AS succeeded_at
        FROM measurement_attempts attempt
        JOIN measurement_requests request ON request.id = attempt.request_measurement_id
        WHERE request.site_id IS NULL
          AND request.is_current
          AND request.source = 'direct_probe'
          AND attempt.supplier_id = $2
          AND attempt.model = $3
          AND attempt.outcome = 'succeeded'
          AND attempt.observed_at < $4
    ) candidate
)
SELECT
    COUNT(*) FILTER (
        WHERE NOT outcome.succeeded
          AND outcome.failed_at > COALESCE(success.succeeded_at, '-infinity'::timestamptz)
    )::bigint AS total,
    COUNT(*) FILTER (
        WHERE NOT outcome.succeeded
          AND outcome.authentication
          AND outcome.failed_at > COALESCE(success.succeeded_at, '-infinity'::timestamptz)
    )::bigint AS authentication,
    COUNT(*) FILTER (
        WHERE NOT outcome.succeeded
          AND outcome.balance
          AND outcome.failed_at > COALESCE(success.succeeded_at, '-infinity'::timestamptz)
    )::bigint AS balance
FROM request_outcomes outcome
CROSS JOIN last_success success
`

type GetFailureStreakParams struct {
	SiteID     pgtype.UUID        `json:"site_id"`
	SupplierID pgtype.UUID        `json:"supplier_id"`
	Model      string             `json:"model"`
	BeforeTime pgtype.Timestamptz `json:"before_time"`
}

type GetFailureStreakRow struct {
	Total          int64 `json:"total"`
	Authentication int64 `json:"authentication"`
	Balance        int64 `json:"balance"`
}

func (q *Queries) GetFailureStreak(ctx context.Context, arg GetFailureStreakParams) (GetFailureStreakRow, error) {
	row := q.db.QueryRow(ctx, getFailureStreak,
		arg.SiteID,
		arg.SupplierID,
		arg.Model,
		arg.BeforeTime,
	)
	var i GetFailureStreakRow
	err := row.Scan(&i.Total, &i.Authentication, &i.Balance)
	return i, err
}

const getLowestPeerCost = `-- name: GetLowestPeerCost :one
SELECT COALESCE(MIN((model.input_price + model.output_price) / 2), 0)::numeric(20, 10)
FROM site_suppliers relation
JOIN sites site ON site.id = relation.site_id
JOIN suppliers supplier ON supplier.id = relation.supplier_id
JOIN supplier_models model ON model.supplier_id = supplier.id
WHERE relation.site_id = $1
  AND model.model = $2
  AND model.currency = $3
  AND site.status = 'enabled'
  AND supplier.status = 'enabled'
  AND model.enabled
  AND relation.desired_status = 'enabled'
  AND relation.sync_status = 'active'
`

type GetLowestPeerCostParams struct {
	SiteID   uuid.UUID `json:"site_id"`
	Model    string    `json:"model"`
	Currency string    `json:"currency"`
}

func (q *Queries) GetLowestPeerCost(ctx context.Context, arg GetLowestPeerCostParams) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, getLowestPeerCost, arg.SiteID, arg.Model, arg.Currency)
	var column_1 decimal.Decimal
	err := row.Scan(&column_1)
	return column_1, err
}

const getWindowRecoveryMillis = `-- name: GetWindowRecoveryMillis :one
WITH attempt_events AS (
    SELECT
        attempt.id,
        attempt.request_measurement_id,
        attempt.attempt_index,
        attempt.outcome = 'succeeded' AS succeeded,
        attempt.observed_at AS event_at
    FROM measurement_attempts attempt
    JOIN measurement_requests request ON request.id = attempt.request_measurement_id
    WHERE request.site_id = $1
      AND request.is_current
      AND request.source = 'real_traffic'
      AND attempt.supplier_id = $2
      AND attempt.model = $3
      AND attempt.observed_at >= $4
      AND attempt.observed_at < $5
      AND (
          attempt.outcome = 'succeeded'
          OR attempt.error_responsibility = 'supplier'
      )
), ordered AS (
    SELECT
        id,
        succeeded,
        event_at,
        MIN(event_at) FILTER (WHERE succeeded) OVER (
            ORDER BY event_at, request_measurement_id, attempt_index, id
            ROWS BETWEEN 1 FOLLOWING AND UNBOUNDED FOLLOWING
        ) AS recovered_at
    FROM attempt_events
), failure_episodes AS (
    SELECT recovered_at, MIN(event_at) AS failure_at
    FROM ordered
    WHERE NOT succeeded
    GROUP BY recovered_at
), recovery_durations AS (
    SELECT ROUND(EXTRACT(EPOCH FROM (
        (CASE
            WHEN recovered_at IS NULL THEN $5
            ELSE recovered_at
        END) - failure_at
    )) * 1000) AS recovery_millis
    FROM failure_episodes
    WHERE failure_at < $5
      AND (recovered_at IS NULL OR recovered_at > $4)
)
SELECT COALESCE(
    MAX(recovery_millis),
    0
)::bigint AS recovery_millis
FROM recovery_durations
`

type GetWindowRecoveryMillisParams struct {
	SiteID      pgtype.UUID        `json:"site_id"`
	SupplierID  pgtype.UUID        `json:"supplier_id"`
	Model       string             `json:"model"`
	WindowStart pgtype.Timestamptz `json:"window_start"`
	WindowEnd   pgtype.Timestamptz `json:"window_end"`
}

func (q *Queries) GetWindowRecoveryMillis(ctx context.Context, arg GetWindowRecoveryMillisParams) (int64, error) {
	row := q.db.QueryRow(ctx, getWindowRecoveryMillis,
		arg.SiteID,
		arg.SupplierID,
		arg.Model,
		arg.WindowStart,
		arg.WindowEnd,
	)
	var recovery_millis int64
	err := row.Scan(&recovery_millis)
	return recovery_millis, err
}

const listLatestScoreSnapshots = `-- name: ListLatestScoreSnapshots :many
SELECT
    snapshot.id, snapshot.site_id, snapshot.supplier_id, snapshot.model, snapshot.policy_version, snapshot.window_start, snapshot.window_end, snapshot.facts_through, snapshot.passive_samples, snapshot.active_samples, snapshot.price_score, snapshot.latency_score, snapshot.sla_score, snapshot.quality_score, snapshot.total_score, snapshot.confidence, snapshot.eligibility, snapshot.hard_reasons, snapshot.explanation, snapshot.authenticity_assessment_id, snapshot.capability_assessment_id, snapshot.created_at, snapshot.score_run_id,
    supplier.name AS supplier_name,
    COALESCE(authenticity.verdict, 'insufficient')::text AS authenticity_verdict,
    COUNT(*) OVER()::bigint AS total_count
FROM score_snapshots snapshot
JOIN suppliers supplier ON supplier.id = snapshot.supplier_id
LEFT JOIN authenticity_assessments authenticity ON authenticity.id = snapshot.authenticity_assessment_id
WHERE snapshot.id IN (
    SELECT DISTINCT ON (site_id, supplier_id, model) id
    FROM score_snapshots
    ORDER BY site_id, supplier_id, model, created_at DESC, id DESC
)
  AND ($1::uuid IS NULL OR snapshot.site_id = $1::uuid)
  AND ($2::uuid IS NULL OR snapshot.supplier_id = $2::uuid)
  AND ($3::text IS NULL OR snapshot.model = $3::text)
ORDER BY snapshot.created_at DESC, snapshot.id DESC
LIMIT $5 OFFSET $4
`

type ListLatestScoreSnapshotsParams struct {
	SiteID     pgtype.UUID `json:"site_id"`
	SupplierID pgtype.UUID `json:"supplier_id"`
	Model      pgtype.Text `json:"model"`
	PageOffset int32       `json:"page_offset"`
	PageLimit  int32       `json:"page_limit"`
}

type ListLatestScoreSnapshotsRow struct {
	ID                       uuid.UUID          `json:"id"`
	SiteID                   uuid.UUID          `json:"site_id"`
	SupplierID               uuid.UUID          `json:"supplier_id"`
	Model                    string             `json:"model"`
	PolicyVersion            string             `json:"policy_version"`
	WindowStart              pgtype.Timestamptz `json:"window_start"`
	WindowEnd                pgtype.Timestamptz `json:"window_end"`
	FactsThrough             pgtype.Timestamptz `json:"facts_through"`
	PassiveSamples           int64              `json:"passive_samples"`
	ActiveSamples            int64              `json:"active_samples"`
	PriceScore               pgtype.Numeric     `json:"price_score"`
	LatencyScore             pgtype.Numeric     `json:"latency_score"`
	SlaScore                 pgtype.Numeric     `json:"sla_score"`
	QualityScore             pgtype.Numeric     `json:"quality_score"`
	TotalScore               pgtype.Numeric     `json:"total_score"`
	Confidence               string             `json:"confidence"`
	Eligibility              string             `json:"eligibility"`
	HardReasons              []byte             `json:"hard_reasons"`
	Explanation              []byte             `json:"explanation"`
	AuthenticityAssessmentID pgtype.UUID        `json:"authenticity_assessment_id"`
	CapabilityAssessmentID   pgtype.UUID        `json:"capability_assessment_id"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	ScoreRunID               pgtype.UUID        `json:"score_run_id"`
	SupplierName             string             `json:"supplier_name"`
	AuthenticityVerdict      string             `json:"authenticity_verdict"`
	TotalCount               int64              `json:"total_count"`
}

func (q *Queries) ListLatestScoreSnapshots(ctx context.Context, arg ListLatestScoreSnapshotsParams) ([]ListLatestScoreSnapshotsRow, error) {
	rows, err := q.db.Query(ctx, listLatestScoreSnapshots,
		arg.SiteID,
		arg.SupplierID,
		arg.Model,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLatestScoreSnapshotsRow{}
	for rows.Next() {
		var i ListLatestScoreSnapshotsRow
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.SupplierID,
			&i.Model,
			&i.PolicyVersion,
			&i.WindowStart,
			&i.WindowEnd,
			&i.FactsThrough,
			&i.PassiveSamples,
			&i.ActiveSamples,
			&i.PriceScore,
			&i.LatencyScore,
			&i.SlaScore,
			&i.QualityScore,
			&i.TotalScore,
			&i.Confidence,
			&i.Eligibility,
			&i.HardReasons,
			&i.Explanation,
			&i.AuthenticityAssessmentID,
			&i.CapabilityAssessmentID,
			&i.CreatedAt,
			&i.ScoreRunID,
			&i.SupplierName,
			&i.AuthenticityVerdict,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScoringTargets = `-- name: ListScoringTargets :many
SELECT
    relation.site_id,
    relation.id AS relation_id,
    relation.supplier_id,
    supplier.name AS supplier_name,
    model.model,
    model.input_price,
    model.output_price,
    model.currency,
    relation.desired_status,
    relation.sync_status,
    COALESCE(
        ARRAY_AGG(DISTINCT strategy.kind) FILTER (
            WHERE member.relation_id IS NOT NULL AND strategy.enabled
        ),
        '{}'
    )::text[] AS current_strategies
FROM site_suppliers relation
JOIN sites site ON site.id = relation.site_id
JOIN suppliers supplier ON supplier.id = relation.supplier_id
JOIN supplier_models model ON model.supplier_id = supplier.id
LEFT JOIN strategy_members member ON member.relation_id = relation.id
LEFT JOIN site_strategies strategy ON strategy.id = member.strategy_id AND strategy.site_id = relation.site_id
WHERE site.status = 'enabled'
  AND supplier.status = 'enabled'
  AND model.enabled
  AND relation.desired_status = 'enabled'
  AND relation.sync_status = 'active'
GROUP BY relation.site_id, relation.id, relation.supplier_id, supplier.name,
         model.model, model.input_price, model.output_price, model.currency,
         relation.desired_status, relation.sync_status
ORDER BY relation.site_id, model.model, supplier.name
`

type ListScoringTargetsRow struct {
	SiteID            uuid.UUID       `json:"site_id"`
	RelationID        uuid.UUID       `json:"relation_id"`
	SupplierID        uuid.UUID       `json:"supplier_id"`
	SupplierName      string          `json:"supplier_name"`
	Model             string          `json:"model"`
	InputPrice        decimal.Decimal `json:"input_price"`
	OutputPrice       decimal.Decimal `json:"output_price"`
	Currency          string          `json:"currency"`
	DesiredStatus     string          `json:"desired_status"`
	SyncStatus        string          `json:"sync_status"`
	CurrentStrategies []string        `json:"current_strategies"`
}

func (q *Queries) ListScoringTargets(ctx context.Context) ([]ListScoringTargetsRow, error) {
	rows, err := q.db.Query(ctx, listScoringTargets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScoringTargetsRow{}
	for rows.Next() {
		var i ListScoringTargetsRow
		if err := rows.Scan(
			&i.SiteID,
			&i.RelationID,
			&i.SupplierID,
			&i.SupplierName,
			&i.Model,
			&i.InputPrice,
			&i.OutputPrice,
			&i.Currency,
			&i.DesiredStatus,
			&i.SyncStatus,
			&i.CurrentStrategies,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShadowRecommendationsForSnapshot = `-- name: ListShadowRecommendationsForSnapshot :many
SELECT id, score_snapshot_id, site_id, supplier_id, model, strategy_kind, action, current_member, score, confidence, reasons, created_at
FROM shadow_recommendations
WHERE score_snapshot_id = $1
ORDER BY strategy_kind
`

func (q *Queries) ListShadowRecommendationsForSnapshot(ctx context.Context, scoreSnapshotID uuid.UUID) ([]ShadowRecommendation, error) {
	rows, err := q.db.Query(ctx, listShadowRecommendationsForSnapshot, scoreSnapshotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ShadowRecommendation{}
	for rows.Next() {
		var i ShadowRecommendation
		if err := rows.Scan(
			&i.ID,
			&i.ScoreSnapshotID,
			&i.SiteID,
			&i.SupplierID,
			&i.Model,
			&i.StrategyKind,
			&i.Action,
			&i.CurrentMember,
			&i.Score,
			&i.Confidence,
			&i.Reasons,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSupplierModelPriceHistory = `-- name: ListSupplierModelPriceHistory :many
SELECT supplier_id, model, version, input_price, output_price, currency, valid_from, valid_to
FROM supplier_model_price_history
WHERE supplier_id = $1
  AND model = $2
  AND valid_from <= $3
  AND (valid_to IS NULL OR valid_to >= $4)
ORDER BY valid_from, version
`

type ListSupplierModelPriceHistoryParams struct {
	SupplierID  uuid.UUID          `json:"supplier_id"`
	Model       string             `json:"model"`
	WindowEnd   pgtype.Timestamptz `json:"window_end"`
	WindowStart pgtype.Timestamptz `json:"window_start"`
}

func (q *Queries) ListSupplierModelPriceHistory(ctx context.Context, arg ListSupplierModelPriceHistoryParams) ([]SupplierModelPriceHistory, error) {
	rows, err := q.db.Query(ctx, listSupplierModelPriceHistory,
		arg.SupplierID,
		arg.Model,
		arg.WindowEnd,
		arg.WindowStart,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SupplierModelPriceHistory{}
	for rows.Next() {
		var i SupplierModelPriceHistory
		if err := rows.Scan(
			&i.SupplierID,
			&i.Model,
			&i.Version,
			&i.InputPrice,
			&i.OutputPrice,
			&i.Currency,
			&i.ValidFrom,
			&i.ValidTo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockScoringAggregationState = `-- name: LockScoringAggregationState :one
SELECT name, initialized_at, facts_through, updated_at
FROM scoring_aggregation_state
WHERE name = 'minute_metrics_v1'
FOR UPDATE
`

func (q *Queries) LockScoringAggregationState(ctx context.Context) (ScoringAggregationState, error) {
	row := q.db.QueryRow(ctx, lockScoringAggregationState)
	var i ScoringAggregationState
	err := row.Scan(
		&i.Name,
		&i.InitializedAt,
		&i.FactsThrough,
		&i.UpdatedAt,
	)
	return i, err
}

const updateScoringAggregationState = `-- name: UpdateScoringAggregationState :execrows
UPDATE scoring_aggregation_state
SET initialized_at = COALESCE(initialized_at, $1),
    facts_through = GREATEST(COALESCE(facts_through, $2), $2),
    updated_at = $3
WHERE name = 'minute_metrics_v1'
`

type UpdateScoringAggregationStateParams struct {
	InitializedAt pgtype.Timestamptz `json:"initialized_at"`
	FactsThrough  pgtype.Timestamptz `json:"facts_through"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateScoringAggregationState(ctx context.Context, arg UpdateScoringAggregationStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateScoringAggregationState, arg.InitializedAt, arg.FactsThrough, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
