// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sites.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSite = `-- name: CreateSite :one
INSERT INTO sites (
    id, code, name, new_api_base_url, admin_credential_id,
    status, compatibility_status, version, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10
)
RETURNING id, code, name, new_api_base_url, admin_credential_id, status, compatibility_status, version, created_at, updated_at, admin_user_id
`

type CreateSiteParams struct {
	ID                  uuid.UUID          `json:"id"`
	Code                string             `json:"code"`
	Name                string             `json:"name"`
	NewApiBaseUrl       string             `json:"new_api_base_url"`
	AdminCredentialID   uuid.UUID          `json:"admin_credential_id"`
	Status              string             `json:"status"`
	CompatibilityStatus string             `json:"compatibility_status"`
	Version             int64              `json:"version"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateSite(ctx context.Context, arg CreateSiteParams) (Site, error) {
	row := q.db.QueryRow(ctx, createSite,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.NewApiBaseUrl,
		arg.AdminCredentialID,
		arg.Status,
		arg.CompatibilityStatus,
		arg.Version,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.NewApiBaseUrl,
		&i.AdminCredentialID,
		&i.Status,
		&i.CompatibilityStatus,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AdminUserID,
	)
	return i, err
}

const getSite = `-- name: GetSite :one
SELECT id, code, name, new_api_base_url, admin_credential_id, status, compatibility_status, version, created_at, updated_at, admin_user_id
FROM sites
WHERE id = $1
`

func (q *Queries) GetSite(ctx context.Context, id uuid.UUID) (Site, error) {
	row := q.db.QueryRow(ctx, getSite, id)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.NewApiBaseUrl,
		&i.AdminCredentialID,
		&i.Status,
		&i.CompatibilityStatus,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AdminUserID,
	)
	return i, err
}

const setSiteCompatibility = `-- name: SetSiteCompatibility :exec
UPDATE sites
SET compatibility_status = $2,
    updated_at = $3,
    version = version + 1
WHERE id = $1
`

type SetSiteCompatibilityParams struct {
	ID                  uuid.UUID          `json:"id"`
	CompatibilityStatus string             `json:"compatibility_status"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) SetSiteCompatibility(ctx context.Context, arg SetSiteCompatibilityParams) error {
	_, err := q.db.Exec(ctx, setSiteCompatibility, arg.ID, arg.CompatibilityStatus, arg.UpdatedAt)
	return err
}
