// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: suppliers.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const createSupplier = `-- name: CreateSupplier :one
INSERT INTO suppliers (
    id, code, name, protocol, upstream_base_url, credential_id,
    credential_version, status, version, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11
)
RETURNING id, code, name, protocol, upstream_base_url, credential_id, credential_version, status, version, created_at, updated_at
`

type CreateSupplierParams struct {
	ID                uuid.UUID          `json:"id"`
	Code              string             `json:"code"`
	Name              string             `json:"name"`
	Protocol          string             `json:"protocol"`
	UpstreamBaseUrl   string             `json:"upstream_base_url"`
	CredentialID      uuid.UUID          `json:"credential_id"`
	CredentialVersion int32              `json:"credential_version"`
	Status            string             `json:"status"`
	Version           int64              `json:"version"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateSupplier(ctx context.Context, arg CreateSupplierParams) (Supplier, error) {
	row := q.db.QueryRow(ctx, createSupplier,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.Protocol,
		arg.UpstreamBaseUrl,
		arg.CredentialID,
		arg.CredentialVersion,
		arg.Status,
		arg.Version,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Protocol,
		&i.UpstreamBaseUrl,
		&i.CredentialID,
		&i.CredentialVersion,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSupplierModel = `-- name: CreateSupplierModel :one
INSERT INTO supplier_models (
    supplier_id, model, upstream_model, input_price, output_price,
    currency, enabled, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9
)
RETURNING supplier_id, model, upstream_model, input_price, output_price, currency, enabled, created_at, updated_at
`

type CreateSupplierModelParams struct {
	SupplierID    uuid.UUID          `json:"supplier_id"`
	Model         string             `json:"model"`
	UpstreamModel string             `json:"upstream_model"`
	InputPrice    decimal.Decimal    `json:"input_price"`
	OutputPrice   decimal.Decimal    `json:"output_price"`
	Currency      string             `json:"currency"`
	Enabled       bool               `json:"enabled"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateSupplierModel(ctx context.Context, arg CreateSupplierModelParams) (SupplierModel, error) {
	row := q.db.QueryRow(ctx, createSupplierModel,
		arg.SupplierID,
		arg.Model,
		arg.UpstreamModel,
		arg.InputPrice,
		arg.OutputPrice,
		arg.Currency,
		arg.Enabled,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i SupplierModel
	err := row.Scan(
		&i.SupplierID,
		&i.Model,
		&i.UpstreamModel,
		&i.InputPrice,
		&i.OutputPrice,
		&i.Currency,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSupplier = `-- name: GetSupplier :one
SELECT id, code, name, protocol, upstream_base_url, credential_id, credential_version, status, version, created_at, updated_at
FROM suppliers
WHERE id = $1
`

func (q *Queries) GetSupplier(ctx context.Context, id uuid.UUID) (Supplier, error) {
	row := q.db.QueryRow(ctx, getSupplier, id)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Protocol,
		&i.UpstreamBaseUrl,
		&i.CredentialID,
		&i.CredentialVersion,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSupplierModels = `-- name: ListSupplierModels :many
SELECT supplier_id, model, upstream_model, input_price, output_price, currency, enabled, created_at, updated_at
FROM supplier_models
WHERE supplier_id = $1
ORDER BY model
`

func (q *Queries) ListSupplierModels(ctx context.Context, supplierID uuid.UUID) ([]SupplierModel, error) {
	rows, err := q.db.Query(ctx, listSupplierModels, supplierID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SupplierModel{}
	for rows.Next() {
		var i SupplierModel
		if err := rows.Scan(
			&i.SupplierID,
			&i.Model,
			&i.UpstreamModel,
			&i.InputPrice,
			&i.OutputPrice,
			&i.Currency,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
