// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const confirmM1Channel = `-- name: ConfirmM1Channel :exec
UPDATE site_supplier_channels
SET external_channel_id = $1::bigint,
    last_confirmed_plan_version = $2::bigint,
    last_confirmed_enabled = $3::boolean,
    last_confirmed_credential_id = CASE WHEN $4::boolean
        THEN $5::uuid ELSE last_confirmed_credential_id END,
    last_confirmed_credential_version = CASE WHEN $4::boolean
        THEN $6::integer ELSE last_confirmed_credential_version END,
    updated_at = $7
WHERE id = $8
`

type ConfirmM1ChannelParams struct {
	ExternalChannelID pgtype.Int8        `json:"external_channel_id"`
	PlanVersion       pgtype.Int8        `json:"plan_version"`
	Enabled           bool               `json:"enabled"`
	CredentialApplied bool               `json:"credential_applied"`
	CredentialID      pgtype.UUID        `json:"credential_id"`
	CredentialVersion pgtype.Int4        `json:"credential_version"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	ID                uuid.UUID          `json:"id"`
}

func (q *Queries) ConfirmM1Channel(ctx context.Context, arg ConfirmM1ChannelParams) error {
	_, err := q.db.Exec(ctx, confirmM1Channel,
		arg.ExternalChannelID,
		arg.PlanVersion,
		arg.Enabled,
		arg.CredentialApplied,
		arg.CredentialID,
		arg.CredentialVersion,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const createIdempotencyRecord = `-- name: CreateIdempotencyRecord :one
INSERT INTO idempotency_records (
    scope, idempotency_key, request_hash, status_code,
    response_body, created_at, expires_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7
)
ON CONFLICT (scope, idempotency_key) DO NOTHING
RETURNING scope, idempotency_key, request_hash, status_code, response_body, created_at, expires_at
`

type CreateIdempotencyRecordParams struct {
	Scope          string             `json:"scope"`
	IdempotencyKey string             `json:"idempotency_key"`
	RequestHash    string             `json:"request_hash"`
	StatusCode     int32              `json:"status_code"`
	ResponseBody   []byte             `json:"response_body"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateIdempotencyRecord(ctx context.Context, arg CreateIdempotencyRecordParams) (IdempotencyRecord, error) {
	row := q.db.QueryRow(ctx, createIdempotencyRecord,
		arg.Scope,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.StatusCode,
		arg.ResponseBody,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i IdempotencyRecord
	err := row.Scan(
		&i.Scope,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.StatusCode,
		&i.ResponseBody,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const createSyncOperation = `-- name: CreateSyncOperation :one
INSERT INTO sync_operations (
    id, site_id, site_supplier_id, route_plan_id, status,
    attempt, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, 'pending',
    0, $5, $5
)
ON CONFLICT (route_plan_id) DO UPDATE
SET route_plan_id = EXCLUDED.route_plan_id
RETURNING id, site_id, site_supplier_id, route_plan_id, status, current_step, attempt, last_error_code, last_error_message, next_attempt_at, created_at, updated_at, completed_at
`

type CreateSyncOperationParams struct {
	ID             uuid.UUID          `json:"id"`
	SiteID         uuid.UUID          `json:"site_id"`
	SiteSupplierID uuid.UUID          `json:"site_supplier_id"`
	RoutePlanID    uuid.UUID          `json:"route_plan_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateSyncOperation(ctx context.Context, arg CreateSyncOperationParams) (SyncOperation, error) {
	row := q.db.QueryRow(ctx, createSyncOperation,
		arg.ID,
		arg.SiteID,
		arg.SiteSupplierID,
		arg.RoutePlanID,
		arg.CreatedAt,
	)
	var i SyncOperation
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.SiteSupplierID,
		&i.RoutePlanID,
		&i.Status,
		&i.CurrentStep,
		&i.Attempt,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.NextAttemptAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getIdempotencyRecord = `-- name: GetIdempotencyRecord :one
SELECT scope, idempotency_key, request_hash, status_code, response_body, created_at, expires_at
FROM idempotency_records
WHERE scope = $1 AND idempotency_key = $2 AND expires_at > $3
`

type GetIdempotencyRecordParams struct {
	Scope          string             `json:"scope"`
	IdempotencyKey string             `json:"idempotency_key"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) GetIdempotencyRecord(ctx context.Context, arg GetIdempotencyRecordParams) (IdempotencyRecord, error) {
	row := q.db.QueryRow(ctx, getIdempotencyRecord, arg.Scope, arg.IdempotencyKey, arg.ExpiresAt)
	var i IdempotencyRecord
	err := row.Scan(
		&i.Scope,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.StatusCode,
		&i.ResponseBody,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getSyncOperation = `-- name: GetSyncOperation :one
SELECT id, site_id, site_supplier_id, route_plan_id, status, current_step, attempt, last_error_code, last_error_message, next_attempt_at, created_at, updated_at, completed_at
FROM sync_operations
WHERE id = $1
`

func (q *Queries) GetSyncOperation(ctx context.Context, id uuid.UUID) (SyncOperation, error) {
	row := q.db.QueryRow(ctx, getSyncOperation, id)
	var i SyncOperation
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.SiteSupplierID,
		&i.RoutePlanID,
		&i.Status,
		&i.CurrentStep,
		&i.Attempt,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.NextAttemptAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getSyncOperationByPlan = `-- name: GetSyncOperationByPlan :one
SELECT id, site_id, site_supplier_id, route_plan_id, status, current_step, attempt, last_error_code, last_error_message, next_attempt_at, created_at, updated_at, completed_at
FROM sync_operations
WHERE route_plan_id = $1
`

func (q *Queries) GetSyncOperationByPlan(ctx context.Context, routePlanID uuid.UUID) (SyncOperation, error) {
	row := q.db.QueryRow(ctx, getSyncOperationByPlan, routePlanID)
	var i SyncOperation
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.SiteSupplierID,
		&i.RoutePlanID,
		&i.Status,
		&i.CurrentStep,
		&i.Attempt,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.NextAttemptAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const insertAuditEvent = `-- name: InsertAuditEvent :exec
INSERT INTO audit_events (
    id, actor_type, actor_id, site_id, object_type, object_id,
    action, reason, operation_id, old_summary, new_summary, result, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11, $12, $13
)
`

type InsertAuditEventParams struct {
	ID          uuid.UUID          `json:"id"`
	ActorType   string             `json:"actor_type"`
	ActorID     string             `json:"actor_id"`
	SiteID      pgtype.UUID        `json:"site_id"`
	ObjectType  string             `json:"object_type"`
	ObjectID    string             `json:"object_id"`
	Action      string             `json:"action"`
	Reason      string             `json:"reason"`
	OperationID pgtype.UUID        `json:"operation_id"`
	OldSummary  []byte             `json:"old_summary"`
	NewSummary  []byte             `json:"new_summary"`
	Result      string             `json:"result"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertAuditEvent,
		arg.ID,
		arg.ActorType,
		arg.ActorID,
		arg.SiteID,
		arg.ObjectType,
		arg.ObjectID,
		arg.Action,
		arg.Reason,
		arg.OperationID,
		arg.OldSummary,
		arg.NewSummary,
		arg.Result,
		arg.CreatedAt,
	)
	return err
}

const latestFullSitePlanID = `-- name: LatestFullSitePlanID :one
SELECT id FROM route_plan_versions
WHERE site_id = $1 AND snapshot->>'schema_version' = '2'
ORDER BY version DESC LIMIT 1
`

func (q *Queries) LatestFullSitePlanID(ctx context.Context, siteID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, latestFullSitePlanID, siteID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const lockSupplierRotation = `-- name: LockSupplierRotation :one
SELECT id FROM suppliers WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockSupplierRotation(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockSupplierRotation, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const markSitePriceApplied = `-- name: MarkSitePriceApplied :exec
UPDATE price_versions SET status = 'applied', applied_at = $3, route_plan_id = $4
WHERE id = $1 AND site_id = $2 AND status = 'published'
`

type MarkSitePriceAppliedParams struct {
	ID          uuid.UUID          `json:"id"`
	SiteID      uuid.UUID          `json:"site_id"`
	AppliedAt   pgtype.Timestamptz `json:"applied_at"`
	RoutePlanID pgtype.UUID        `json:"route_plan_id"`
}

func (q *Queries) MarkSitePriceApplied(ctx context.Context, arg MarkSitePriceAppliedParams) error {
	_, err := q.db.Exec(ctx, markSitePriceApplied,
		arg.ID,
		arg.SiteID,
		arg.AppliedAt,
		arg.RoutePlanID,
	)
	return err
}

const markSyncFailed = `-- name: MarkSyncFailed :exec
UPDATE sync_operations
SET status = $2,
    current_step = $3,
    last_error_code = $4,
    last_error_message = $5,
    next_attempt_at = $6,
    updated_at = $7
WHERE id = $1
`

type MarkSyncFailedParams struct {
	ID               uuid.UUID          `json:"id"`
	Status           string             `json:"status"`
	CurrentStep      pgtype.Text        `json:"current_step"`
	LastErrorCode    pgtype.Text        `json:"last_error_code"`
	LastErrorMessage pgtype.Text        `json:"last_error_message"`
	NextAttemptAt    pgtype.Timestamptz `json:"next_attempt_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) MarkSyncFailed(ctx context.Context, arg MarkSyncFailedParams) error {
	_, err := q.db.Exec(ctx, markSyncFailed,
		arg.ID,
		arg.Status,
		arg.CurrentStep,
		arg.LastErrorCode,
		arg.LastErrorMessage,
		arg.NextAttemptAt,
		arg.UpdatedAt,
	)
	return err
}

const markSyncRunning = `-- name: MarkSyncRunning :exec
UPDATE sync_operations
SET status = 'running',
    current_step = $2,
    attempt = attempt + 1,
    last_error_code = NULL,
    last_error_message = NULL,
    next_attempt_at = NULL,
    updated_at = $3
WHERE id = $1
`

type MarkSyncRunningParams struct {
	ID          uuid.UUID          `json:"id"`
	CurrentStep pgtype.Text        `json:"current_step"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) MarkSyncRunning(ctx context.Context, arg MarkSyncRunningParams) error {
	_, err := q.db.Exec(ctx, markSyncRunning, arg.ID, arg.CurrentStep, arg.UpdatedAt)
	return err
}

const markSyncSucceeded = `-- name: MarkSyncSucceeded :exec
UPDATE sync_operations
SET status = 'succeeded',
    current_step = 'confirmed',
    last_error_code = NULL,
    last_error_message = NULL,
    next_attempt_at = NULL,
    updated_at = $2,
    completed_at = $2
WHERE id = $1
`

type MarkSyncSucceededParams struct {
	ID        uuid.UUID          `json:"id"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) MarkSyncSucceeded(ctx context.Context, arg MarkSyncSucceededParams) error {
	_, err := q.db.Exec(ctx, markSyncSucceeded, arg.ID, arg.UpdatedAt)
	return err
}

const markSyncSuperseded = `-- name: MarkSyncSuperseded :exec
UPDATE sync_operations
SET status = 'superseded', current_step = 'superseded', next_attempt_at = NULL,
    updated_at = $2, completed_at = $2
WHERE id = $1
`

type MarkSyncSupersededParams struct {
	ID        uuid.UUID          `json:"id"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) MarkSyncSuperseded(ctx context.Context, arg MarkSyncSupersededParams) error {
	_, err := q.db.Exec(ctx, markSyncSuperseded, arg.ID, arg.UpdatedAt)
	return err
}

const promoteConfirmedSupplierCredential = `-- name: PromoteConfirmedSupplierCredential :exec
UPDATE suppliers s
SET credential_id = pending_credential_id,
    credential_version = pending_credential_version,
    pending_credential_id = NULL,
    pending_credential_version = NULL,
    updated_at = $2
WHERE s.id = $1 AND s.pending_credential_id IS NOT NULL
AND NOT EXISTS (
    SELECT 1 FROM site_suppliers r
    JOIN site_supplier_channels c ON c.site_supplier_id = r.id
    WHERE r.supplier_id = s.id AND c.external_channel_id IS NOT NULL
      AND (c.last_confirmed_credential_id IS DISTINCT FROM s.pending_credential_id
        OR c.last_confirmed_credential_version IS DISTINCT FROM s.pending_credential_version)
)
`

type PromoteConfirmedSupplierCredentialParams struct {
	ID        uuid.UUID          `json:"id"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) PromoteConfirmedSupplierCredential(ctx context.Context, arg PromoteConfirmedSupplierCredentialParams) error {
	_, err := q.db.Exec(ctx, promoteConfirmedSupplierCredential, arg.ID, arg.UpdatedAt)
	return err
}

const setPlanRelationsSyncFailure = `-- name: SetPlanRelationsSyncFailure :exec
UPDATE site_suppliers SET sync_status = $2, updated_at = $3
WHERE current_plan_id = $1 AND sync_status = 'syncing'
`

type SetPlanRelationsSyncFailureParams struct {
	CurrentPlanID pgtype.UUID        `json:"current_plan_id"`
	SyncStatus    string             `json:"sync_status"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) SetPlanRelationsSyncFailure(ctx context.Context, arg SetPlanRelationsSyncFailureParams) error {
	_, err := q.db.Exec(ctx, setPlanRelationsSyncFailure, arg.CurrentPlanID, arg.SyncStatus, arg.UpdatedAt)
	return err
}

const setPlanRelationsSyncing = `-- name: SetPlanRelationsSyncing :exec
UPDATE site_suppliers SET sync_status = 'syncing', updated_at = $2
WHERE current_plan_id = $1
`

type SetPlanRelationsSyncingParams struct {
	CurrentPlanID pgtype.UUID        `json:"current_plan_id"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) SetPlanRelationsSyncing(ctx context.Context, arg SetPlanRelationsSyncingParams) error {
	_, err := q.db.Exec(ctx, setPlanRelationsSyncing, arg.CurrentPlanID, arg.UpdatedAt)
	return err
}

const setRelationSyncFailure = `-- name: SetRelationSyncFailure :exec
UPDATE site_suppliers SET sync_status = $2, updated_at = $3
WHERE id = $1 AND current_plan_id = $4
`

type SetRelationSyncFailureParams struct {
	ID            uuid.UUID          `json:"id"`
	SyncStatus    string             `json:"sync_status"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	CurrentPlanID pgtype.UUID        `json:"current_plan_id"`
}

func (q *Queries) SetRelationSyncFailure(ctx context.Context, arg SetRelationSyncFailureParams) error {
	_, err := q.db.Exec(ctx, setRelationSyncFailure,
		arg.ID,
		arg.SyncStatus,
		arg.UpdatedAt,
		arg.CurrentPlanID,
	)
	return err
}

const setSyncStep = `-- name: SetSyncStep :exec
INSERT INTO sync_steps (
    operation_id, step_key, status, before_summary, after_summary,
    error_code, error_message, started_at, finished_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9
)
ON CONFLICT (operation_id, step_key) DO UPDATE
SET status = EXCLUDED.status,
    before_summary = EXCLUDED.before_summary,
    after_summary = EXCLUDED.after_summary,
    error_code = EXCLUDED.error_code,
    error_message = EXCLUDED.error_message,
    started_at = COALESCE(sync_steps.started_at, EXCLUDED.started_at),
    finished_at = EXCLUDED.finished_at
`

type SetSyncStepParams struct {
	OperationID   uuid.UUID          `json:"operation_id"`
	StepKey       string             `json:"step_key"`
	Status        string             `json:"status"`
	BeforeSummary []byte             `json:"before_summary"`
	AfterSummary  []byte             `json:"after_summary"`
	ErrorCode     pgtype.Text        `json:"error_code"`
	ErrorMessage  pgtype.Text        `json:"error_message"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	FinishedAt    pgtype.Timestamptz `json:"finished_at"`
}

func (q *Queries) SetSyncStep(ctx context.Context, arg SetSyncStepParams) error {
	_, err := q.db.Exec(ctx, setSyncStep,
		arg.OperationID,
		arg.StepKey,
		arg.Status,
		arg.BeforeSummary,
		arg.AfterSummary,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.StartedAt,
		arg.FinishedAt,
	)
	return err
}
