/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["opAuthStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["opAuthSetup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["opAuthLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["opAuthSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["opAuthLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ops/sites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["opListSites"];
        put?: never;
        post: operations["opCreateSite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ops/sites/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["OpID"];
            };
            cookie?: never;
        };
        get?: never;
        put: operations["opUpdateSite"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ops/sites/{id}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["OpID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["opSyncSite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ops/suppliers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["opListSuppliers"];
        put?: never;
        post: operations["opCreateSupplier"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ops/suppliers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["OpID"];
            };
            cookie?: never;
        };
        get?: never;
        put: operations["opUpdateSupplier"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ops/suppliers/{id}/credentials": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["OpID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["opRotateCredential"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ops/deployments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["opDeploySupplier"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ops/suppliers/{id}/credentials/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["OpID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["opCancelCredential"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ops/relations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["opListRelations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ops/relations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["OpID"];
            };
            cookie?: never;
        };
        get?: never;
        put: operations["opUpdateRelation"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ops/strategies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["opListStrategies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ops/sites/{id}/strategies/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["OpID"];
                kind: components["schemas"]["OpStrategyKind"];
            };
            cookie?: never;
        };
        get?: never;
        put: operations["opSaveStrategy"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ops/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["opListPrices"];
        put?: never;
        post: operations["opDraftPrice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ops/prices/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["OpID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["opPublishPrice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ops/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["opListPlans"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ops/plans/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["OpID"];
            };
            cookie?: never;
        };
        get: operations["opGetPlan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ops/plans/{id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["OpID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["opRestorePlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ops/sync-operations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["opListSyncOperations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ops/sync-operations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["OpID"];
            };
            cookie?: never;
        };
        get: operations["opGetSyncOperation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ops/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["opListAudit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ops/collection-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["opListCollectionStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ops/collection-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["opRunCollection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ops/evaluation-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["opListEvaluationRuns"];
        put?: never;
        post: operations["opRequestEvaluationRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ops/evaluation-runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["OpID"];
            };
            cookie?: never;
        };
        get: operations["opGetEvaluationRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ops/evaluation-runs/{id}/reference": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["OpID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["opPromoteEvaluationReference"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ops/score-insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["opListScoreInsights"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ops/score-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["opRefreshScores"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        OpCollectionRunInput: {
            /** Format: uuid */
            site_id: string;
        };
        OpCollectionRunResult: {
            /** Format: uuid */
            site_id: string;
            site_name: string;
            read_records: number;
            saved_requests: number;
            saved_attempts: number;
            /** Format: date-time */
            cursor_time?: string | null;
            /** Format: date-time */
            scanned_through?: string | null;
            /** Format: date-time */
            source_latest?: string | null;
            data_gap: boolean;
            error_code?: string;
        };
        OpCollectionStatus: {
            /** Format: uuid */
            site_id: string;
            site_name: string;
            source_kind: string;
            contract_version: string;
            /** Format: date-time */
            cursor_time?: string | null;
            /** Format: date-time */
            scanned_through?: string | null;
            /** Format: date-time */
            source_latest?: string | null;
            /** Format: date-time */
            last_read_at?: string | null;
            /** Format: date-time */
            last_success_at?: string | null;
            /** Format: date-time */
            last_error_at?: string | null;
            last_error_code?: string;
            last_error_message?: string;
            consecutive_failures: number;
            data_gap: boolean;
            /** Format: date-time */
            updated_at?: string | null;
        };
        OpCollectionStatusList: {
            items: components["schemas"]["OpCollectionStatus"][];
        };
        OpEvaluationRunInput: {
            /** Format: uuid */
            supplier_id: string;
            model: string;
            /** @enum {string} */
            purpose: "health" | "authenticity" | "quality" | "recovery";
            /**
             * @default supplier_direct
             * @enum {string}
             */
            target_kind: "supplier_direct";
            reason: string;
        };
        OpEvaluationRun: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            supplier_id: string;
            supplier_name?: string;
            /** Format: uuid */
            relation_id?: string | null;
            /** Format: uuid */
            site_id?: string | null;
            model: string;
            upstream_model: string;
            /** @enum {string} */
            target_kind: "supplier_direct" | "site_route";
            /** @enum {string} */
            purpose: "health" | "authenticity" | "quality" | "recovery";
            /** @enum {string} */
            status: "pending" | "running" | "succeeded" | "failed" | "uncertain" | "cancelled";
            suite_version: string;
            algorithm_version: string;
            /** Format: uuid */
            reference_id?: string | null;
            planned_samples: number;
            completed_samples: number;
            requested_by: string;
            request_reason: string;
            error_code?: string;
            error_message?: string;
            /** Format: date-time */
            requested_at: string;
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            completed_at?: string | null;
            /** Format: date-time */
            next_retry_at?: string | null;
        };
        OpEvaluationRunPage: components["schemas"]["OpPagination"] & {
            items: components["schemas"]["OpEvaluationRun"][];
        };
        OpTrustedReferenceInput: {
            /** @enum {string} */
            trust: "official" | "operator_trusted" | "community";
            reason: string;
            valid_days: number;
        };
        OpTrustedReference: {
            /** Format: uuid */
            id: string;
            model: string;
            /** Format: uuid */
            supplier_id: string;
            /** @enum {string} */
            trust: "official" | "operator_trusted" | "community";
            /** Format: date-time */
            expires_at: string;
        };
        OpShadowRecommendation: {
            /** @enum {string} */
            strategy_kind: "lowest_price" | "low_latency" | "high_sla" | "high_quality" | "balanced";
            /** @enum {string} */
            action: "join" | "keep" | "exit" | "watch" | "exclude";
            current_member: boolean;
            score?: number | null;
            /** @enum {string} */
            confidence: "high" | "medium" | "low" | "insufficient";
            reasons: string[];
        };
        OpScoreInsight: {
            /** Format: uuid */
            snapshot_id: string;
            policy_version: string;
            /** Format: uuid */
            site_id: string;
            /** Format: uuid */
            supplier_id: string;
            supplier_name: string;
            model: string;
            /** Format: int64 */
            passive_samples: number;
            /** Format: int64 */
            active_samples: number;
            price_score?: number | null;
            latency_score?: number | null;
            sla_score?: number | null;
            quality_score?: number | null;
            total_score?: number | null;
            /** @enum {string} */
            confidence: "high" | "medium" | "low" | "insufficient";
            /** @enum {string} */
            eligibility: "eligible" | "excluded" | "insufficient";
            hard_reasons: string[];
            /** @enum {string} */
            authenticity_verdict: "consistent" | "suspicious" | "inconsistent" | "insufficient";
            /** Format: date-time */
            facts_through?: string | null;
            /** Format: date-time */
            window_start: string;
            /** Format: date-time */
            window_end: string;
            /** Format: date-time */
            created_at: string;
            explanation: {
                [key: string]: unknown;
            };
            recommendations: components["schemas"]["OpShadowRecommendation"][];
        };
        OpScoreInsightPage: components["schemas"]["OpPagination"] & {
            items: components["schemas"]["OpScoreInsight"][];
        };
        OpError: {
            code: string;
            message: string;
            request_id: string;
        };
        OpAuthStatus: {
            initialized: boolean;
        };
        OpAuthUser: {
            /** Format: uuid */
            id: string;
            username: string;
            /** @enum {string} */
            role: "owner";
        };
        OpAuthSession: {
            user: components["schemas"]["OpAuthUser"];
            csrf_token: string;
        };
        OpLoginInput: {
            username: string;
            password: string;
        };
        OpSetupInput: {
            username: string;
            password: string;
            setup_token: string;
        };
        /** @enum {string} */
        OpStrategyKind: "lowest_price" | "low_latency" | "high_sla" | "high_quality" | "balanced";
        OpModelInput: {
            model: string;
            upstream_model: string;
            /** @description Nonnegative decimal with at most ten fractional digits */
            input_price: string;
            /** @description Nonnegative decimal with at most ten fractional digits */
            output_price: string;
            /** @enum {string} */
            currency: "USD" | "CNY";
            enabled: boolean;
        };
        OpCreateSiteInput: {
            code: string;
            name: string;
            /** Format: uri */
            new_api_base_url: string;
            new_api_access_token: string;
            /**
             * Format: int64
             * @default 1
             */
            admin_user_id: number;
            /** @enum {string} */
            status?: "enabled" | "disabled";
            /** Format: int64 */
            version?: number;
            reason?: string;
        };
        OpUpdateSiteInput: {
            code?: string;
            name: string;
            /** Format: uri */
            new_api_base_url: string;
            new_api_access_token?: string;
            /**
             * Format: int64
             * @default 1
             */
            admin_user_id: number;
            /** @enum {string} */
            status: "enabled" | "disabled";
            /** Format: int64 */
            version: number;
            reason: string;
        };
        OpCreateSupplierInput: {
            code: string;
            name: string;
            /** Format: uri */
            upstream_base_url: string;
            upstream_api_key: string;
            models: components["schemas"]["OpModelInput"][];
            /** @enum {string} */
            status?: "enabled" | "disabled";
            /** Format: int64 */
            version?: number;
            reason?: string;
        };
        OpUpdateSupplierInput: {
            code?: string;
            name: string;
            /** Format: uri */
            upstream_base_url: string;
            upstream_api_key?: string;
            models: components["schemas"]["OpModelInput"][];
            /** @enum {string} */
            status: "enabled" | "disabled";
            /** Format: int64 */
            version: number;
            reason: string;
        };
        OpCredentialInput: {
            /** Format: int64 */
            version: number;
            api_key: string;
            reason: string;
        };
        OpDeploymentTarget: {
            /** Format: uuid */
            site_id: string;
            group_display_name: string;
            /** @description Positive decimal up to 999999.999999 */
            sale_ratio: string;
            /** @description Open the dedicated group entry when true. False closes the entry and rejects subsequent requests from existing API keys bound to this group after synchronization; the supplier can still serve other open Auto groups. */
            visible: boolean;
        };
        OpCredentialCancelInput: {
            /** Format: int64 */
            version: number;
            reason: string;
        };
        OpDeploymentInput: {
            /** Format: uuid */
            supplier_id: string;
            sites: components["schemas"]["OpDeploymentTarget"][];
            reason: string;
        };
        OpRelationInput: {
            /** Format: int64 */
            version: number;
            group_display_name: string;
            /** @description Desired dedicated entry access. False closes the entry and rejects subsequent requests from existing group-bound API keys after synchronization, while preserving the channel and participation in other open Auto groups. */
            visible: boolean;
            /** @enum {string} */
            desired_status: "enabled" | "disabled";
            /** @description Explicitly restore a stopped deployment */
            resume: boolean;
            reason: string;
        };
        OpStrategyInput: {
            /**
             * Format: int64
             * @description Zero when creating a site strategy
             */
            version: number;
            enabled: boolean;
            /** @description Desired Auto entry access. False closes the entry and rejects subsequent requests from existing API keys bound to this Auto group after synchronization. Opening also requires an enabled strategy with eligible members. */
            visible: boolean;
            display_name: string;
            member_relation_ids: string[];
            reason: string;
        };
        OpPriceInput: {
            /** Format: uuid */
            site_id: string;
            group_key: string;
            /** @description Positive decimal up to 999999.999999 */
            sale_ratio: string;
            reason: string;
        };
        OpPublishInput: {
            /** Format: int64 */
            version: number;
        };
        OpRestoreInput: {
            reason: string;
        };
        OpSite: {
            /** Format: uuid */
            id: string;
            code: string;
            name: string;
            new_api_base_url: string;
            /** Format: int64 */
            admin_user_id: number;
            /** @enum {string} */
            status: "enabled" | "disabled";
            /** @enum {string} */
            compatibility_status: "unknown" | "compatible" | "incompatible";
            /** Format: int64 */
            version: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        OpSupplier: {
            /** Format: uuid */
            id: string;
            code: string;
            name: string;
            /** @enum {string} */
            protocol: "openai_compatible";
            upstream_base_url: string;
            credential_version: number;
            pending_credential_version?: number | null;
            /** @enum {string} */
            status: "draft" | "enabled" | "disabled";
            /** Format: int64 */
            version: number;
            models: components["schemas"]["OpModelInput"][];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        OpRelation: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            site_id: string;
            /** Format: uuid */
            supplier_id: string;
            group_key: string;
            group_display_name: string;
            sale_ratio: string;
            /** @description Desired dedicated group entry access, including existing group-bound API keys. Inspect synchronization state for whether the access change has completed. */
            visible: boolean;
            /** @enum {string} */
            desired_status: "observing" | "enabled" | "disabled";
            /** @enum {string} */
            sync_status: "pending" | "syncing" | "active" | "failed" | "manual_locked";
            /** Format: int64 */
            version: number;
            /** Format: uuid */
            current_plan_id?: string | null;
            /** Format: date-time */
            last_confirmed_at?: string | null;
            site_name: string;
            supplier_name: string;
            credential_version?: number | null;
            last_confirmed_enabled?: boolean | null;
            /** Format: int64 */
            external_channel_id?: number | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        OpStrategy: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            site_id: string;
            kind: components["schemas"]["OpStrategyKind"];
            group_key: string;
            display_name: string;
            enabled: boolean;
            /** @description Desired Auto group entry access, including existing group-bound API keys. Effective opening also requires an enabled strategy and eligible members. */
            visible: boolean;
            /** Format: int64 */
            version: number;
            member_relation_ids: string[];
            sale_ratio?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        OpPrice: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            site_id: string;
            group_key: string;
            /** Format: int64 */
            version: number;
            sale_ratio: string;
            reason: string;
            /** @enum {string} */
            status: "draft" | "published" | "applied" | "superseded";
            /** @description Pricing settings and New API version observed for this price; this historical evidence does not assert that an external administrator has left the live settings unchanged. */
            billing_basis: {
                [key: string]: unknown;
            };
            /** @description Digest of the observed pricing settings and New API version, used for configuration reconciliation. */
            basis_hash: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            published_at?: string | null;
            /**
             * Format: date-time
             * @description Historical time when this price version first passed group-ratio and pricing-basis reconciliation; subsequent external changes or partial writes may require fresh confirmation.
             */
            applied_at?: string | null;
            /** @description True for the most recently confirmed version recorded for this site and group. A pending or partially applied newer plan can leave the current external price unknown. */
            is_last_confirmed: boolean;
            /** Format: uuid */
            route_plan_id?: string | null;
        };
        OpPlan: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            site_id: string;
            /** Format: uuid */
            site_supplier_id: string;
            /** Format: int64 */
            version: number;
            /** Format: uuid */
            previous_plan_id?: string | null;
            reason: string;
            snapshot: {
                [key: string]: unknown;
            };
            previous_snapshot?: {
                [key: string]: unknown;
            } | null;
            content_hash: string;
            /** @enum {string} */
            status: "pending" | "applying" | "confirmed" | "failed" | "uncertain" | "superseded";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            confirmed_at?: string | null;
        };
        OpPlanReference: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            site_id: string;
            /** Format: int64 */
            version: number;
            status: string;
        } & {
            [key: string]: unknown;
        };
        OpPlanResult: {
            plans: components["schemas"]["OpPlanReference"][];
        };
        OpSyncStep: {
            /** Format: uuid */
            operation_id: string;
            step_key: string;
            /** @enum {string} */
            status: "pending" | "running" | "succeeded" | "failed" | "uncertain";
            before_summary?: {
                [key: string]: unknown;
            } | null;
            after_summary?: {
                [key: string]: unknown;
            } | null;
            error_code?: string | null;
            error_message?: string | null;
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            finished_at?: string | null;
        };
        OpSyncOperation: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            site_id: string;
            /** Format: uuid */
            site_supplier_id: string;
            /** Format: uuid */
            route_plan_id: string;
            /** @enum {string} */
            status: "pending" | "running" | "uncertain" | "succeeded" | "retryable_failed" | "manual_required" | "superseded";
            current_step?: string | null;
            attempt: number;
            last_error_code?: string | null;
            last_error_message?: string | null;
            /** Format: date-time */
            next_attempt_at?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: date-time */
            completed_at?: string | null;
            steps: components["schemas"]["OpSyncStep"][];
        };
        OpAudit: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            actor_type: "operator" | "system";
            actor_id: string;
            /** Format: uuid */
            site_id?: string | null;
            object_type: string;
            object_id: string;
            action: string;
            reason: string;
            /** Format: uuid */
            operation_id?: string | null;
            old_summary?: {
                [key: string]: unknown;
            } | null;
            new_summary?: {
                [key: string]: unknown;
            } | null;
            result: string;
            /** Format: date-time */
            created_at: string;
        };
        OpPagination: {
            /** Format: int64 */
            total: number;
            limit: number;
            offset: number;
        };
        OpSitePage: components["schemas"]["OpPagination"] & {
            items: components["schemas"]["OpSite"][];
        };
        OpSupplierPage: components["schemas"]["OpPagination"] & {
            items: components["schemas"]["OpSupplier"][];
        };
        OpRelationPage: components["schemas"]["OpPagination"] & {
            items: components["schemas"]["OpRelation"][];
        };
        OpStrategyPage: components["schemas"]["OpPagination"] & {
            items: components["schemas"]["OpStrategy"][];
        };
        OpPricePage: components["schemas"]["OpPagination"] & {
            items: components["schemas"]["OpPrice"][];
        };
        OpPlanPage: components["schemas"]["OpPagination"] & {
            items: components["schemas"]["OpPlan"][];
        };
        OpSyncOperationPage: components["schemas"]["OpPagination"] & {
            items: components["schemas"]["OpSyncOperation"][];
        };
        OpAuditPage: components["schemas"]["OpPagination"] & {
            items: components["schemas"]["OpAudit"][];
        };
    };
    responses: {
        /** @description Validation, authentication, conflict, downstream, or server failure */
        OpError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["OpError"];
            };
        };
        /** @description Configuration accepted with its affected site plans; inspect synchronization for actual completion */
        OpPlans: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["OpPlanResult"];
            };
        };
    };
    parameters: {
        OpID: string;
        OpIdempotencyKey: string;
        OpQuery: string;
        OpSiteFilter: string;
        OpSupplierFilter: string;
        OpLimit: number;
        OpOffset: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    opAuthStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Owner initialization status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpAuthStatus"];
                };
            };
            default: components["responses"]["OpError"];
        };
    };
    opAuthSetup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpSetupInput"];
            };
        };
        responses: {
            /** @description Owner created and session cookie issued */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpAuthSession"];
                };
            };
            default: components["responses"]["OpError"];
        };
    };
    opAuthLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpLoginInput"];
            };
        };
        responses: {
            /** @description Authenticated and session cookie issued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpAuthSession"];
                };
            };
            default: components["responses"]["OpError"];
        };
    };
    opAuthSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current operator and CSRF token */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpAuthSession"];
                };
            };
            default: components["responses"]["OpError"];
        };
    };
    opAuthLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session revoked and cookie removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["OpError"];
        };
    };
    opListSites: {
        parameters: {
            query?: {
                q?: components["parameters"]["OpQuery"];
                site_id?: components["parameters"]["OpSiteFilter"];
                supplier_id?: components["parameters"]["OpSupplierFilter"];
                limit?: components["parameters"]["OpLimit"];
                offset?: components["parameters"]["OpOffset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Site page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpSitePage"];
                };
            };
            default: components["responses"]["OpError"];
        };
    };
    opCreateSite: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["OpIdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpCreateSiteInput"];
            };
        };
        responses: {
            /** @description Site created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpSite"];
                };
            };
            default: components["responses"]["OpError"];
        };
    };
    opUpdateSite: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["OpIdempotencyKey"];
            };
            path: {
                id: components["parameters"]["OpID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpUpdateSiteInput"];
            };
        };
        responses: {
            /** @description Site updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpSite"];
                };
            };
            default: components["responses"]["OpError"];
        };
    };
    opSyncSite: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["OpIdempotencyKey"];
            };
            path: {
                id: components["parameters"]["OpID"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            202: components["responses"]["OpPlans"];
            default: components["responses"]["OpError"];
        };
    };
    opListSuppliers: {
        parameters: {
            query?: {
                q?: components["parameters"]["OpQuery"];
                site_id?: components["parameters"]["OpSiteFilter"];
                supplier_id?: components["parameters"]["OpSupplierFilter"];
                limit?: components["parameters"]["OpLimit"];
                offset?: components["parameters"]["OpOffset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Supplier page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpSupplierPage"];
                };
            };
            default: components["responses"]["OpError"];
        };
    };
    opCreateSupplier: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["OpIdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpCreateSupplierInput"];
            };
        };
        responses: {
            /** @description Supplier created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpSupplier"];
                };
            };
            default: components["responses"]["OpError"];
        };
    };
    opUpdateSupplier: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["OpIdempotencyKey"];
            };
            path: {
                id: components["parameters"]["OpID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpUpdateSupplierInput"];
            };
        };
        responses: {
            /** @description Supplier updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpSupplier"];
                };
            };
            default: components["responses"]["OpError"];
        };
    };
    opRotateCredential: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["OpIdempotencyKey"];
            };
            path: {
                id: components["parameters"]["OpID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpCredentialInput"];
            };
        };
        responses: {
            200: components["responses"]["OpPlans"];
            default: components["responses"]["OpError"];
        };
    };
    opDeploySupplier: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["OpIdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpDeploymentInput"];
            };
        };
        responses: {
            202: components["responses"]["OpPlans"];
            default: components["responses"]["OpError"];
        };
    };
    opCancelCredential: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["OpIdempotencyKey"];
            };
            path: {
                id: components["parameters"]["OpID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpCredentialCancelInput"];
            };
        };
        responses: {
            200: components["responses"]["OpPlans"];
            default: components["responses"]["OpError"];
        };
    };
    opListRelations: {
        parameters: {
            query?: {
                q?: components["parameters"]["OpQuery"];
                site_id?: components["parameters"]["OpSiteFilter"];
                supplier_id?: components["parameters"]["OpSupplierFilter"];
                limit?: components["parameters"]["OpLimit"];
                offset?: components["parameters"]["OpOffset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Site supplier relation page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpRelationPage"];
                };
            };
            default: components["responses"]["OpError"];
        };
    };
    opUpdateRelation: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["OpIdempotencyKey"];
            };
            path: {
                id: components["parameters"]["OpID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpRelationInput"];
            };
        };
        responses: {
            200: components["responses"]["OpPlans"];
            default: components["responses"]["OpError"];
        };
    };
    opListStrategies: {
        parameters: {
            query?: {
                q?: components["parameters"]["OpQuery"];
                site_id?: components["parameters"]["OpSiteFilter"];
                supplier_id?: components["parameters"]["OpSupplierFilter"];
                limit?: components["parameters"]["OpLimit"];
                offset?: components["parameters"]["OpOffset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Site strategy page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpStrategyPage"];
                };
            };
            default: components["responses"]["OpError"];
        };
    };
    opSaveStrategy: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["OpIdempotencyKey"];
            };
            path: {
                id: components["parameters"]["OpID"];
                kind: components["schemas"]["OpStrategyKind"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpStrategyInput"];
            };
        };
        responses: {
            /** @description Strategy saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpStrategy"];
                };
            };
            default: components["responses"]["OpError"];
        };
    };
    opListPrices: {
        parameters: {
            query?: {
                q?: components["parameters"]["OpQuery"];
                site_id?: components["parameters"]["OpSiteFilter"];
                supplier_id?: components["parameters"]["OpSupplierFilter"];
                limit?: components["parameters"]["OpLimit"];
                offset?: components["parameters"]["OpOffset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Price history page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpPricePage"];
                };
            };
            default: components["responses"]["OpError"];
        };
    };
    opDraftPrice: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["OpIdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpPriceInput"];
            };
        };
        responses: {
            /** @description Price draft created with the current site billing basis */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpPrice"];
                };
            };
            default: components["responses"]["OpError"];
        };
    };
    opPublishPrice: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["OpIdempotencyKey"];
            };
            path: {
                id: components["parameters"]["OpID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpPublishInput"];
            };
        };
        responses: {
            200: components["responses"]["OpPlans"];
            default: components["responses"]["OpError"];
        };
    };
    opListPlans: {
        parameters: {
            query?: {
                q?: components["parameters"]["OpQuery"];
                site_id?: components["parameters"]["OpSiteFilter"];
                supplier_id?: components["parameters"]["OpSupplierFilter"];
                limit?: components["parameters"]["OpLimit"];
                offset?: components["parameters"]["OpOffset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Route plan history page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpPlanPage"];
                };
            };
            default: components["responses"]["OpError"];
        };
    };
    opGetPlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["OpID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Complete route plan and previous snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpPlan"];
                };
            };
            default: components["responses"]["OpError"];
        };
    };
    opRestorePlan: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["OpIdempotencyKey"];
            };
            path: {
                id: components["parameters"]["OpID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpRestoreInput"];
            };
        };
        responses: {
            200: components["responses"]["OpPlans"];
            default: components["responses"]["OpError"];
        };
    };
    opListSyncOperations: {
        parameters: {
            query?: {
                q?: components["parameters"]["OpQuery"];
                site_id?: components["parameters"]["OpSiteFilter"];
                supplier_id?: components["parameters"]["OpSupplierFilter"];
                limit?: components["parameters"]["OpLimit"];
                offset?: components["parameters"]["OpOffset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Synchronization operations with step results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpSyncOperationPage"];
                };
            };
            default: components["responses"]["OpError"];
        };
    };
    opGetSyncOperation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["OpID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Synchronization operation and its steps */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpSyncOperation"];
                };
            };
            default: components["responses"]["OpError"];
        };
    };
    opListAudit: {
        parameters: {
            query?: {
                q?: components["parameters"]["OpQuery"];
                site_id?: components["parameters"]["OpSiteFilter"];
                supplier_id?: components["parameters"]["OpSupplierFilter"];
                limit?: components["parameters"]["OpLimit"];
                offset?: components["parameters"]["OpOffset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Operator audit history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpAuditPage"];
                };
            };
            default: components["responses"]["OpError"];
        };
    };
    opListCollectionStatus: {
        parameters: {
            query?: {
                site_id?: components["parameters"]["OpSiteFilter"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Per-site measurement collection freshness and cursor state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpCollectionStatusList"];
                };
            };
            default: components["responses"]["OpError"];
        };
    };
    opRunCollection: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["OpIdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpCollectionRunInput"];
            };
        };
        responses: {
            /** @description Completed idempotent collection pass for one site */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpCollectionRunResult"];
                };
            };
            default: components["responses"]["OpError"];
        };
    };
    opListEvaluationRuns: {
        parameters: {
            query?: {
                site_id?: components["parameters"]["OpSiteFilter"];
                supplier_id?: components["parameters"]["OpSupplierFilter"];
                model?: string;
                purpose?: "health" | "authenticity" | "quality" | "recovery";
                limit?: components["parameters"]["OpLimit"];
                offset?: components["parameters"]["OpOffset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Evaluation runs without private prompts or raw answers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpEvaluationRunPage"];
                };
            };
            default: components["responses"]["OpError"];
        };
    };
    opRequestEvaluationRun: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["OpIdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpEvaluationRunInput"];
            };
        };
        responses: {
            /** @description Durable evaluation run accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpEvaluationRun"];
                };
            };
            default: components["responses"]["OpError"];
        };
    };
    opGetEvaluationRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["OpID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Evaluation run progress and safe summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpEvaluationRun"];
                };
            };
            default: components["responses"]["OpError"];
        };
    };
    opPromoteEvaluationReference: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["OpIdempotencyKey"];
            };
            path: {
                id: components["parameters"]["OpID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpTrustedReferenceInput"];
            };
        };
        responses: {
            /** @description Fingerprint promoted to a versioned trusted reference */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpTrustedReference"];
                };
            };
            default: components["responses"]["OpError"];
        };
    };
    opListScoreInsights: {
        parameters: {
            query?: {
                site_id?: components["parameters"]["OpSiteFilter"];
                supplier_id?: components["parameters"]["OpSupplierFilter"];
                model?: string;
                limit?: components["parameters"]["OpLimit"];
                offset?: components["parameters"]["OpOffset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Latest explainable shadow score for each site supplier model */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpScoreInsightPage"];
                };
            };
            default: components["responses"]["OpError"];
        };
    };
    opRefreshScores: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["OpIdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Measurement aggregates and shadow scores refreshed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "completed";
                    };
                };
            };
            default: components["responses"]["OpError"];
        };
    };
}
