export const stepNames: Record<string, string> = {
  load_resources: "读取供应商配置",
  decrypt_admin: "读取站点凭证",
  verify_billing_basis: "核对模型计价",
  read_before_groups: "读取分组价格",
  plan_group_prices: "准备分组价格",
  set_group_prices: "更新分组价格",
  read_group_prices: "读取已更新价格",
  verify_group_prices: "核对价格生效",
  read_before_visibility: "读取用户入口",
  verify_site: "核对站点配置",
  verify_final_billing_basis: "确认模型计价",
  ownership: "检查渠道归属",
  disable: "停用渠道",
  disabled: "已确认下线",
  apply: "更新供应商配置",
  confirmed: "已确认供应商配置",
  validate_site: "检查站点",
  probe: "检查兼容性",
  read_actual: "读取当前配置",
  locate_channel: "定位渠道",
  manual_lock: "检查人工停用",
  merge_group_ratio: "核对分组价格",
  set_group_ratio: "更新分组价格",
  set_group_visibility: "更新用户入口",
  create_channel: "创建渠道",
  update_channel: "更新渠道",
  read_after_channel_write: "读取渠道配置",
  locate_channel_after_write: "核对渠道归属",
  test_channel: "测试渠道",
  prepare_channel_activation: "准备上线",
  enable_channel: "启用渠道",
  disable_channel: "停用渠道",
  final_read: "读取最终配置",
  verify: "核对结果",
  verify_unmanaged_groups: "核对其他分组",
  verify_unmanaged_user_groups: "核对其他用户入口",
  complete: "确认生效",
  check_current_plan: "检查配置版本",
  decrypt_credentials: "读取凭证",
  create_gateway: "连接站点",
};

export function stepLabel(value?: string | null): string {
  if (!value) return "等待执行";
  return (
    stepNames[value] ??
    stepNames[value.split(":").at(-1) ?? ""] ??
    "核对同步结果"
  );
}

export const actionNames: Record<string, string> = {
  create_site: "创建站点",
  update_site: "修改站点",
  create_supplier: "创建供应商",
  update_supplier: "修改供应商",
  rotate_credential: "更换上游密钥",
  cancel_credential: "取消候选密钥",
  deploy: "投放供应商",
  relation: "修改投放",
  strategy: "修改 Auto",
  draft_price: "创建售价草案",
  publish_price: "发布售价",
  restore: "恢复线路",
  sync: "提交同步",
  "site.created": "创建站点",
  "site.updated": "修改站点",
  "site.credential_rotated": "更换站点凭证",
  "supplier.created": "创建供应商",
  "supplier.updated": "修改供应商",
  "supplier.credential_rotated": "更换上游密钥",
  "site_supplier.created": "投放供应商",
  "site_supplier.updated": "修改投放",
  "relation.updated": "修改投放",
  "strategy.updated": "修改 Auto",
  "strategy.saved": "保存 Auto",
  "price.created": "创建售价草案",
  "price.drafted": "创建售价草案",
  "price.published": "发布售价",
  "route_plan.created": "创建线路版本",
  "route_plan.confirmed": "确认线路生效",
  "route_plan.restored": "恢复线路",
  "route_plan.sync_failed": "线路同步失败",
  "owner.initialized": "初始化所有者",
  "owner.login": "所有者登录",
  "owner.logout": "所有者退出",
};

export const objectNames: Record<string, string> = {
  site: "站点",
  supplier: "供应商",
  site_supplier: "投放",
  relation: "投放",
  strategy: "Auto",
  price: "售价",
  price_version: "售价",
  route_plan: "线路",
  sync_operation: "同步",
  owner: "所有者",
};
